#!/usr/bin/env python3
"""Batch 1 of the admin panel's own string table: the chrome.

Tabs, buttons, table headers, form labels, status words and the short
captions beside them -- the words an operator reads on every screen. Written
as data here and merged into admin-src/index.html by build-admin-rows.py, so
the rows can be reviewed as a table rather than as JavaScript.

[english, lg, sw, fr, rw, nyn]
"""
ROWS = [
    # ── the tabs ──
    ['Dashboard', 'Olutimbe', 'Dashibodi', 'Tableau de bord', 'Imbonerahamwe', 'Orubaju rw\'ebikuru'],
    ['Analytics', 'Okwekenneenya', 'Uchanganuzi', 'Analyses', 'Isesengura', 'Okucondooza'],
    ['Users', 'Abakozesa', 'Watumiaji', 'Utilisateurs', 'Abakoresha', 'Abakozesa'],
    ['Deposits', 'Ssente eziteekebwamu', 'Amana', 'Dépôts', 'Ubwishyu bwinjiye', 'Sente ezitairwemu'],
    ['Withdrawals', 'Okuggyamu ssente', 'Utoaji', 'Retraits', 'Kubikuza', 'Okwihamu sente'],
    ['Transactions', 'Emirimu gy\'ssente', 'Miamala', '=', 'Ibikorwa by\'amafaranga', 'Emirimo ya sente'],
    ['Referrals', 'Okuyita', 'Mialiko', 'Parrainages', 'Gutumira', 'Okweta'],
    ['Gift Codes', 'Koodi z\'ebirabo', 'Misimbo ya Zawadi', 'Codes cadeaux', 'Kode z\'impano', 'Koodi z\'ebiconco'],
    ['Gift codes', 'Koodi z\'ebirabo', 'Misimbo ya zawadi', 'Codes cadeaux', 'Kode z\'impano', 'Koodi z\'ebiconco'],
    ['Countries', 'Amawanga', 'Nchi', 'Pays', 'Ibihugu', 'Amahanga'],
    ['Admins', 'Abaduumizi', 'Wasimamizi', 'Administrateurs', 'Abayobozi', 'Abebembezi'],
    ['Activity Log', 'Ekitabo ky\'ebikolwa', 'Kumbukumbu ya shughuli', 'Journal d\'activité', 'Igitabo cy\'ibikorwa', 'Ekitabo ky\'ebikorwa'],
    ['Activity log', 'Ekitabo ky\'ebikolwa', 'Kumbukumbu ya shughuli', 'Journal d\'activité', 'Igitabo cy\'ibikorwa', 'Ekitabo ky\'ebikorwa'],
    ['Overview', 'Okulabako', 'Muhtasari', 'Aperçu', 'Incamake', 'Okureeberera'],

    # ── the topbar ──
    ['Notify', 'Manyisa', 'Arifa', 'Notifier', 'Menyesha', 'Manyisa'],
    ['Sign in', 'Yingira', 'Ingia', 'Se connecter', 'Injira', 'Taaha'],
    ['Which country this panel is showing', 'Ggwanga ki lino olupapula lye lulaga', 'Ni nchi gani paneli hii inaonyesha', 'Quel pays ce panneau affiche', 'Ni igihugu iki iyi paneli yerekana', 'N\'ihanga ki eri orupapura eri rirukworeka'],
    ['The language this panel is shown in', 'Olulimi lino olupapula lwe lulagibwamu', 'Lugha ambayo paneli hii inaonyeshwa', 'La langue dans laquelle ce panneau est affiché', 'Ururimi iyi paneli yerekanwamo', 'Orurimi eri orupapura rirukworekwamu'],
    ['All countries', 'Amawanga gonna', 'Nchi zote', 'Tous les pays', 'Ibihugu byose', 'Amahanga goona'],
    ['This screen is the same for every country.', 'Olupapula luno lwe lumu eri buli ggwanga.', 'Skrini hii ni sawa kwa kila nchi.', 'Cet écran est le même pour chaque pays.', 'Uru rupapuro ni rumwe kuri buri gihugu.', 'Orupapura ruru nirwo rumwe ahari buri ihanga.'],

    # ── dashboard ──
    ['Total users', 'Omuwendo gw\'abakozesa', 'Jumla ya watumiaji', 'Total des utilisateurs', 'Umubare w\'abakoresha', 'Omubaro gw\'abakozesa'],
    ['Active users', 'Abakozesa abakola', 'Watumiaji hai', 'Utilisateurs actifs', 'Abakoresha bakora', 'Abakozesa abarikukora'],
    ['Banned users', 'Abakozesa abagaanibwa', 'Watumiaji waliozuiwa', 'Utilisateurs bloqués', 'Abakoresha babujijwe', 'Abakozesa abarikuzibirwa'],
    ['Wallet balances', 'Ssente eziri mu nsawo', 'Salio za pochi', 'Soldes des portefeuilles', 'Amafaranga ari mu mifuka', 'Sente eziri omu nsaho'],
    ['Total deposited', 'Ssente zonna eziteekeddwamu', 'Jumla iliyowekwa', 'Total déposé', 'Amafaranga yose yabitswe', 'Sente zoona ezitairwemu'],
    ['Total withdrawn', 'Ssente zonna eziggiddwamu', 'Jumla iliyotolewa', 'Total retiré', 'Amafaranga yose yabikujwe', 'Sente zoona ezihiirwemu'],
    ['Total invested', 'Ssente zonna eziteekeddwa mu bizinensi', 'Jumla iliyowekezwa', 'Total investi', 'Amafaranga yose yashowe', 'Sente zoona ezitairwemu omu byamaguzi'],
    ['Active plans', 'Enteekateeka ezikola', 'Mipango hai', 'Plans actifs', 'Gahunda zikora', 'Enteekateeka ezirikukora'],
    ['Pending deposits', 'Ssente eziteekeddwamu ezirindiridde', 'Amana yanayosubiri', 'Dépôts en attente', 'Ubwishyu butegereje', 'Sente ezitairwemu ezirikutegyereza'],
    ['Pending withdrawals', 'Okuggyamu ssente okurindiridde', 'Utoaji unaosubiri', 'Retraits en attente', 'Kubikuza gutegereje', 'Okwihamu sente okurikutegyereza'],
    ['Recent transactions', 'Emirimu gy\'ssente egiyise', 'Miamala ya hivi karibuni', 'Transactions récentes', 'Ibikorwa bya vuba', 'Emirimo ya sente ey\'obwire obuhingwire'],
    ['MarzPay available balance', 'Ssente eziriwo ku MarzPay', 'Salio linalopatikana la MarzPay', 'Solde disponible MarzPay', 'Amafaranga aboneka kuri MarzPay', 'Sente eziriho aha MarzPay'],
    ['Crunching numbers…', 'Tubala emiwendo…', 'Tunahesabu namba…', 'Calcul en cours…', 'Kubara imibare…', 'Nitubara emibaro…'],

    # ── table headers and row labels ──
    ['Type', 'Ekika', 'Aina', '=', 'Ubwoko', 'Ekika'],
    ['Status', 'Embeera', 'Hali', 'Statut', 'Imimerere', 'Embeera'],
    ['Reason', 'Ensonga', 'Sababu', 'Motif', 'Impamvu', 'Enshonga'],
    ['Reference', 'Namba y\'okujuliza', 'Kumbukumbu', 'Référence', 'Inomero y\'icyitegererezo', 'Namba y\'okwijuka'],
    ['Description', 'Ennyinyonnyola', 'Maelezo', '=', 'Ibisobanuro', 'Okushoboorora'],
    ['Details', 'Ebisingawo', 'Maelezo zaidi', 'Détails', 'Ibisobanuro birambuye', 'Ebindi ebirikukiraho'],
    ['Action', 'Ekikolwa', 'Kitendo', '=', 'Igikorwa', 'Ekikorwa'],
    ['Who', 'Ani', 'Nani', 'Qui', 'Nde', 'Oha'],
    ['When', 'Ddi', 'Lini', 'Quand', 'Ryari', 'Ryari'],
    ['Phone', 'Essimu', 'Simu', 'Téléphone', 'Telefone', 'Esimu'],
    ['Phone number', 'Namba y\'essimu', 'Namba ya simu', 'Numéro de téléphone', 'Nomero ya telefone', 'Namba ya esimu'],
    ['Number', 'Namba', 'Namba', 'Numéro', 'Nomero', 'Namba'],
    ['Network', 'Ekitongole ky\'essimu', 'Mtandao', 'Réseau', 'Uruhererekane', 'Ekitongore kya esimu'],
    ['Country', 'Eggwanga', 'Nchi', 'Pays', 'Igihugu', 'Ihanga'],
    ['Currency', 'Ssente z\'eggwanga', 'Sarafu', 'Devise', 'Ifaranga', 'Sente z\'ihanga'],
    ['Clock', 'Essaawa', 'Saa', 'Horloge', 'Isaha', 'Eshaaha'],
    ['Web address', 'Endagiriro y\'omukutu', 'Anwani ya tovuti', 'Adresse web', 'Aderesi ya interineti', 'Endagiriro y\'orubuga'],
    ['Created', 'Yatondebwa', 'Iliundwa', 'Créé', 'Yaremwe', 'Ekahangwa'],
    ['Last login', 'Okuyingira okusembayo', 'Kuingia mara ya mwisho', 'Dernière connexion', 'Kwinjira kwa nyuma', 'Okutaaha okwa buhereeru'],
    ['Never', 'Tewali', 'Kamwe', 'Jamais', 'Nta na rimwe', 'Tikirimu'],
    ['Not set', 'Tekitereddwa', 'Haijawekwa', 'Non défini', 'Ntibyashyizweho', 'Tikitairweho'],
    ['Nothing set', 'Tewali kitereddwa', 'Hakuna kilichowekwa', 'Rien de défini', 'Nta cyashyizweho', 'Tihariho ekitairweho'],
    ['None', 'Tewali', 'Hakuna', 'Aucun', 'Nta na kimwe', 'Tihariho'],
    ['None saved.', 'Tewali kitereddwa.', 'Hakuna iliyohifadhiwa.', 'Aucun enregistré.', 'Nta cyabitswe.', 'Tihariho ekibiikirwe.'],
    ['No transactions', 'Tewali mirimu gy\'ssente', 'Hakuna miamala', 'Aucune transaction', 'Nta bikorwa', 'Tihariho mirimo ya sente'],
    ['On', 'Kikola', 'Imewashwa', 'Activé', 'Birakora', 'Nikikora'],
    ['Off', 'Tekikola', 'Imezimwa', 'Désactivé', 'Ntibikora', 'Tikirikukora'],
    ['Enabled', 'Kisobozesebbwa', 'Imewezeshwa', 'Activé', 'Birakoreshwa', 'Nikikozesibwa'],
    ['Upcoming', 'Kijja mu maaso', 'Inakuja', 'À venir', 'Biri hafi kuza', 'Nikiija omu maisho'],
    ['Used', 'Kikozeseddwa', 'Imetumika', 'Utilisé', 'Byakoreshejwe', 'Kikakozesibwa'],
    ['Expires', 'Kiggwaako', 'Muda wake unaisha', 'Expire', 'Birangira', 'Nikihwaho'],
    ['Code', 'Koodi', 'Msimbo', '=', 'Kode', 'Koodi'],
    ['Codes', 'Koodi', 'Misimbo', '=', 'Kode', 'Koodi'],
    ['Copy code', 'Koppa koodi', 'Nakili msimbo', 'Copier le code', 'Gukoporora kode', 'Koppa koodi'],
    ['Title', 'Omutwe', 'Kichwa', 'Titre', 'Umutwe', 'Omutwe'],
    ['Message', 'Obubaka', 'Ujumbe', '=', 'Ubutumwa', 'Obutumwa'],
    ['Invested', 'Ssente eziteekeddwamu', 'Iliyowekezwa', 'Investi', 'Yashowe', 'Sente ezitairwemu'],
    ['Referred user', 'Omukozesa ayitiddwa', 'Mtumiaji aliyealikwa', 'Utilisateur parrainé', 'Umukoresha watumiwe', 'Omukozesa oyetsirwe'],
    ["Referrer's code", 'Koodi y\'oyo ayise', 'Msimbo wa mwalikaji', 'Code du parrain', 'Kode y\'uwatumiye', 'Koodi y\'oworikweta'],
    ['Referred by', 'Yayitibwa', 'Alialikwa na', 'Parrainé par', 'Yatumiwe na', 'Yayetsirwe'],
    ['Paid from', 'Yasasulwa okuva', 'Imelipwa kutoka', 'Payé depuis', 'Byishyuwe biva', 'Kishashuriirwe kuruga'],
    ['Paid to', 'Yasasulwa eri', 'Imelipwa kwa', 'Payé à', 'Byishyuwe kuri', 'Kishashuriirwe ahari'],
    ['Processing', 'Kirongoosebwa', 'Inashughulikiwa', 'En traitement', 'Birimo gutunganywa', 'Nikikorwaho'],
    ['Check-in', 'Okukyalira', 'Kuhudhuria', 'Pointage', 'Kwiyandikisha', 'Okwoleka'],
    ['Commissions', 'Ssente z\'okuyita', 'Kamisheni', '=', 'Komisiyo', 'Sente z\'okweta'],
    ['Plans', 'Enteekateeka', 'Mipango', '=', 'Gahunda', 'Enteekateeka'],
    ['L1 commission', 'Ssente ez\'omutendera 1', 'Kamisheni ya ngazi 1', 'Commission niveau 1', 'Komisiyo y\'urwego rwa 1', 'Sente z\'omurengo 1'],
    ['l1 commission', 'ssente ez\'omutendera 1', 'kamisheni ya ngazi 1', 'commission niveau 1', 'komisiyo y\'urwego rwa 1', 'sente z\'omurengo 1'],
    ['turntable', 'nnamuziga', 'gurudumu', 'roue', 'uruziga', 'orupiira'],
    ['Turntable win', 'Okuwangula ku nnamuziga', 'Ushindi wa gurudumu', 'Gain à la roue', 'Gutsindira ku ruziga', 'Okusingura aha rupiira'],
    ['Deposit: Paid', 'Okuteekamu: Kisasuddwa', 'Amana: Imelipwa', 'Dépôt : Payé', 'Ubwishyu: Byishyuwe', 'Okuteeramu: Kishashuriirwe'],
    ['Withdrawal: Processing', 'Okuggyamu: Kirongoosebwa', 'Utoaji: Inashughulikiwa', 'Retrait : En traitement', 'Kubikuza: Birimo gutunganywa', 'Okwihamu: Nikikorwaho'],
]
