#!/usr/bin/env python3
"""Batch 10 of the admin panel's string table: the OPERATOR INSTRUCTIONS, part 3.

The image-slot and brand explanations, the auth screen, the sign-in rules and
the remaining Settings copy. Continues admin-rows-8.py -- read its header for
the caution about the three Bantu columns.

Sizes, ratios, file formats and brand names (Android, PNG, WhatsApp, Telegram,
Facebook, MarzPay, LOGIN / SIGN UP as the members see them) stay as they are.

[english, lg, sw, fr, rw, nyn]
"""
ROWS = [
    ['The full-screen picture behind the Download button, on the screen a member reaches from Account → Download APP. Portrait, 1080 × 1920 (any size works — it is cropped to fill). A dark overlay is drawn on top so the white heading and the button stay readable, so a bright picture is fine. An empty slot shows the brand gradient.',
     'Ekifaananyi ekijjuza olupapula emabega wa bbaatani ya Download, ku lupapula omuntu lw\'atuukako okuva ku Akaawunti → Download APP. Eky\'obuwanvu, 1080 × 1920 (obunene bwonna bukola — kisalibwa okujjuza). Ekibikka ekiddugavu kiteekebwa waggulu omutwe omweru ne bbaatani bisobole okusomeka, kale ekifaananyi ekitangaavu tekiriiko kabi. Ekifo ekyereere kiraga langi z\'ekitongole.',
     'Picha ya skrini nzima nyuma ya kitufe cha Download, kwenye skrini mwanachama anayofikia kutoka Akaunti → Download APP. Wima, 1080 × 1920 (ukubwa wowote unafaa — hukatwa ili kujaza). Kifuniko cheusi huchorwa juu ili kichwa cheupe na kitufe vibaki vinasomeka, kwa hivyo picha nyangavu haina shida. Nafasi tupu huonyesha upinde rangi wa chapa.',
     'L\'image plein écran derrière le bouton Download, sur l\'écran que le membre atteint depuis Compte → Download APP. Portrait, 1080 × 1920 (toute taille convient — elle est recadrée pour remplir). Un voile sombre est dessiné par-dessus pour que le titre blanc et le bouton restent lisibles, donc une image claire ne pose pas de problème. Un emplacement vide affiche le dégradé de la marque.',
     'Ishusho yuzuye ipaji iri inyuma ya buto ya Download, ku ipaji umunyamuryango agera kuva kuri Konti → Download APP. Ihagaritse, 1080 × 1920 (ingano iyo ari yo yose irakora — icibwa kugira ngo yuzure). Igipfukisho cyijimye gishyirwa hejuru kugira ngo umutwe wera na buto bisomeke, bityo ishusho imurika nta kibazo. Umwanya usa ugaragaza amabara y\'ikirango.',
     'Ekishushani ekirikwijuza orupapura enyima ya akabatuni ka Download, aha rupapura omuntu arikuhikaho kuruga aha Akaunti → Download APP. Ekya kwemeera, 1080 × 1920 (obungi bwoona nibukora — nikicwa kugira ngo kiijuze). Ekibundikiro ekikwatsiire nikitebekwa haiguru kugira ngo omutwe omwera n\'akabatuni bishoboke kushomwa, n\'ahabw\'ekyo ekishushani ekyakire tikirikubaho kibi. Omwanya ogwo busha nigworeka amabara g\'ekitongore.'],

    ['The icon members see on their phone\'s home screen after they install the app, and in the browser tab. Upload a square PNG, 1024 × 1024 (512 × 512 also works — anything square does; it is resized here to the exact 512 and 192 sizes Android asks for). Transparency is kept, and the corners are rounded for you — upload a plain square and it comes out with the rounded shape an app icon has. Keep the logo away from the very edges so the rounding does not cut into it.',
     'Akafaananyi abantu ke balaba ku lupapula lwa ssimu zaabwe nga bamaze okuteekawo app, ne ku ttabu lya bbulawuza. Teeka PNG ey\'enjuyi enkanaanya, 1024 × 1024 (512 × 512 nayo ekola — kyonna ekikanaanya kikola; kikyusibwa wano okutuuka ku bunene bwa 512 ne 192 Android bw\'esaba). Obwereere bukuumibwa, era ensonda zizingululwa — teeka ekifaananyi ekikanaanya kifuluma nga kirina enkula enzingulule ey\'akafaananyi ka app. Teeka akabonero wala n\'ensonda enkulu okusobola obutasalibwako.',
     'Aikoni wanachama wanayoona kwenye skrini ya nyumbani ya simu zao baada ya kusakinisha programu, na kwenye kichupo cha kivinjari. Pakia PNG ya mraba, 1024 × 1024 (512 × 512 pia inafaa — chochote cha mraba kinafaa; hubadilishwa hapa kuwa ukubwa kamili wa 512 na 192 ambao Android huomba). Uwazi huhifadhiwa, na pembe huzungushwa kwa ajili yako — pakia mraba tu na hutoka na umbo la mviringo ambalo aikoni ya programu inalo. Weka nembo mbali na pembezoni kabisa ili mviringo usiikate.',
     'L\'icône que les membres voient sur l\'écran d\'accueil de leur téléphone après avoir installé l\'application, et dans l\'onglet du navigateur. Téléversez un PNG carré, 1024 × 1024 (512 × 512 fonctionne aussi — tout carré convient ; il est redimensionné ici aux tailles exactes 512 et 192 demandées par Android). La transparence est conservée et les coins sont arrondis pour vous — téléversez un simple carré et il ressort avec la forme arrondie d\'une icône d\'application. Gardez le logo loin des bords pour que l\'arrondi ne l\'entame pas.',
     'Agashushondanga abanyamuryango babona kuri ecran y\'ibanze ya telefoni zabo nyuma yo gushyiraho porogaramu, no ku gice cy\'umushakisha. Shyiraho PNG ifite impande zingana, 1024 × 1024 (512 × 512 na yo irakora — ikintu cyose gifite impande zingana kirakora; ihindurwa hano ikagira ingano nyayo ya 512 na 192 Android isaba). Ububonerane burabikwa, kandi impera zirazingurutswa — shyiraho igishushanyo gisanzwe kigire impande zingana kikazasohoka gifite isura izengurutse agashushondanga ka porogaramu kagira. Shyira ikirango kure y\'impera kugira ngo kuzingurutsa bitagice.',
     'Akashushani abantu ka barikureeba aha rupapura rw\'omuka rwa nyabarugo zaabo bwanyima y\'okuteeka puroguramu, n\'aha kacweka ka buraawuza. Ta PNG ey\'empande ezirikwingana, 1024 × 1024 (512 × 512 nayo neekora — kyoona ekirikwingana nikikora; nikihindurwa hanu kikahika aha bungi bwa 512 na 192 Android eri kushaba). Obwereere nibukuumwa, kandi ensonda nizizingurutswa — ta ekirikwingana kwonka kandi nikiija kiine enshusha ezingurukire ei akashushani ka puroguramu karikugira. Ta ekirango hare n\'empera kugira ngo okuzingurutsa kutakicwaho.'],

    ['The lower banner on the app\'s Home tab, carrying the Go spin button that opens the turntable. It replaced the product list that used to sit there — products now live on their own tab. Full width, roughly 3:1 (for example 1200×400). An empty slot shows the brand gradient behind the button.',
     'Akabaawo ak\'ewansi ku ttabu lya Home, akalina bbaatani ya Go spin eggula akanyoolera. Kaddira mu kifo ky\'olukalala lw\'ebyamaguzi olwalibangawo — ebyamaguzi kati biri ku ttabu lyabyo. Obugazi bwonna, nga 3:1 (ng\'ekyokulabirako 1200×400). Ekifo ekyereere kiraga langi z\'ekitongole emabega wa bbaatani.',
     'Bango la chini kwenye kichupo cha Nyumbani cha programu, lenye kitufe cha Go spin kinachofungua gurudumu. Lilichukua nafasi ya orodha ya bidhaa iliyokuwa hapo — bidhaa sasa ziko kwenye kichupo chao. Upana kamili, takriban 3:1 (mfano 1200×400). Nafasi tupu huonyesha upinde rangi wa chapa nyuma ya kitufe.',
     'La bannière du bas sur l\'onglet Accueil de l\'application, portant le bouton Go spin qui ouvre la roue. Elle a remplacé la liste de produits qui s\'y trouvait — les produits ont maintenant leur propre onglet. Pleine largeur, environ 3:1 (par exemple 1200×400). Un emplacement vide affiche le dégradé de la marque derrière le bouton.',
     'Ikirango cyo hasi ku gice cy\'Ahabanza cya porogaramu, gifite buto ya Go spin ifungura uruziga. Cyasimbuye urutonde rw\'ibicuruzwa rwahoze aho — ibicuruzwa ubu bifite igice cyabyo bwite. Ubugari bwose, hafi 3:1 (urugero 1200×400). Umwanya usa ugaragaza amabara y\'ikirango inyuma ya buto.',
     'Ekirango eky\'ahansi aha kacweka ka Home, ekiine akabatuni ka Go spin akarikwigura akanyoorera. Kyatwaire omwanya gw\'orutonde rw\'ebyamaguzi orwabaire ruriho — ebyamaguzi hati biri aha kacweka kaabyo. Obugazi bwoona, nka 3:1 (nk\'eky\'okureeberaho 1200×400). Omwanya ogwo busha nigworeka amabara g\'ekitongore enyima y\'akabatuni.'],

    ['The orange area. Landscape, about 1200 × 700. An empty slot shows the brand gradient. The picture sits over the gradient, so lowering opacity blends it back toward the orange rather than toward nothing.',
     'Ekitundu ekya langi ya oranji. Eky\'obugazi, nga 1200 × 700. Ekifo ekyereere kiraga langi z\'ekitongole. Ekifaananyi kiteekebwa ku langi, kale okukendeeza ku bulabikirwa kikitabula okudda eri langi ya oranji so si eri bwereere.',
     'Eneo la rangi ya machungwa. Mlalo, takriban 1200 × 700. Nafasi tupu huonyesha upinde rangi wa chapa. Picha hukaa juu ya upinde rangi, kwa hivyo kupunguza uwazi huichanganya kurudi kwenye rangi ya machungwa badala ya kuelekea utupu.',
     'La zone orange. Paysage, environ 1200 × 700. Un emplacement vide affiche le dégradé de la marque. L\'image repose sur le dégradé, donc baisser l\'opacité la fond vers l\'orange plutôt que vers le vide.',
     'Ahantu h\'ibara ry\'icunga. Iryambitse, hafi 1200 × 700. Umwanya usa ugaragaza amabara y\'ikirango. Ishusho iri hejuru y\'amabara, bityo kugabanya ukubonerana biyivanga isubira ku ibara ry\'icunga aho kujya ku busa.',
     'Akacweka ak\'erangi ya oranje. Aka kugazire, nka 1200 × 700. Omwanya ogwo busha nigworeka amabara g\'ekitongore. Ekishushani nikitebekwa aha mabara, n\'ahabw\'ekyo okukyendeza aha kureeberwa nikikitaburamu kikagaruka aha rangi ya oranje ti aha busha.'],

    ['The picture that appears when the app\'s link is pasted into WhatsApp, Telegram or Facebook. Upload 1200 × 630 (landscape, just under 2:1). Any size is accepted and centre-cropped to fit, but anything far off that shape loses its edges. Put the logo and any words in the middle — WhatsApp crops the sides on some phones.',
     'Ekifaananyi ekirabika ng\'ekkubo lya app liteekeddwa mu WhatsApp, Telegram oba Facebook. Teeka 1200 × 630 (eky\'obugazi, wansi wa 2:1). Obunene bwonna bukkirizibwa era busalibwa wakati okutuukagana, naye ekitali kya nkula eyo kifiirwa ensonda zaakyo. Teeka akabonero n\'ebigambo byonna wakati — WhatsApp esala embiriizi ku ssimu ezimu.',
     'Picha inayoonekana wakati kiungo cha programu kinapobandikwa kwenye WhatsApp, Telegram au Facebook. Pakia 1200 × 630 (mlalo, chini kidogo ya 2:1). Ukubwa wowote hukubaliwa na hukatwa katikati ili kutoshea, lakini kitu kilicho mbali na umbo hilo hupoteza pembezoni mwake. Weka nembo na maneno yoyote katikati — WhatsApp hukata pembeni kwenye simu nyingine.',
     'L\'image qui apparaît quand le lien de l\'application est collé dans WhatsApp, Telegram ou Facebook. Téléversez 1200 × 630 (paysage, juste en dessous de 2:1). Toute taille est acceptée et recadrée au centre pour s\'ajuster, mais tout ce qui s\'éloigne de cette forme perd ses bords. Mettez le logo et les mots au milieu — WhatsApp rogne les côtés sur certains téléphones.',
     'Ishusho igaragara iyo umurongo wa porogaramu ukomekwe muri WhatsApp, Telegram cyangwa Facebook. Shyiraho 1200 × 630 (iryambitse, munsi gato ya 2:1). Ingano iyo ari yo yose iremerwa igacibwa hagati kugira ngo ikwire, ariko ikintu kitandukanye cyane n\'iyo sura kibura impera zacyo. Shyira ikirango n\'amagambo hagati — WhatsApp iceta impande kuri zimwe muri telefoni.',
     'Ekishushani ekirikureeberwa ku omuhanda gwa puroguramu gurikutwarwa omu WhatsApp, Telegram nari Facebook. Ta 1200 × 630 (eki kugazire, ahansi ya 2:1). Obungi bwoona nibwikirizibwa kandi nibucwa ahagati kugira ngo buhikaane, kwonka ekitari kya nshusha egyo nikifeerwa empera zaakyo. Ta ekirango n\'ebigambo byoona ahagati — WhatsApp neecwa empande aha nyabarugo ezimwe.'],

    ['The PIN is one-way hashed -- it can never be viewed, only replaced. Sets the 6-digit trade password below directly; give it to the member so they can withdraw. They can also change it themselves in the app (Account -> Trade Password).',
     'PIN ekwekebwa mu ngeri etaddayo -- teyinza kulabika, wabula esobola okuddizibwa. Eteeka ekisumuluzo eky\'obusuubuzi eky\'ennamba 6 ekiri wansi butereevu; kiwe omuntu asobole okuggyamu ssente. Era asobola okukikyusa yekka mu app (Akaawunti -> Trade Password).',
     'PIN imefichwa kwa njia isiyorudi nyuma -- haiwezi kamwe kuonekana, inaweza tu kubadilishwa. Huweka nenosiri la biashara la tarakimu 6 lililo hapa chini moja kwa moja; mpe mwanachama ili aweze kutoa pesa. Anaweza pia kulibadilisha mwenyewe kwenye programu (Akaunti -> Trade Password).',
     'Le code PIN est haché à sens unique -- il ne peut jamais être consulté, seulement remplacé. Il définit directement le mot de passe de transaction à 6 chiffres ci-dessous ; donnez-le au membre pour qu\'il puisse retirer. Il peut aussi le changer lui-même dans l\'application (Compte -> Trade Password).',
     'PIN ihishwe mu buryo budasubirwaho -- ntishobora na rimwe kurebwa, ishobora gusa gusimburwa. Ishyiraho ijambobanga ry\'ubucuruzi ry\'imibare 6 riri hasi ako kanya; rihe umunyamuryango kugira ngo abashe kubikuza. Ashobora no kurihindura ubwe muri porogaramu (Konti -> Trade Password).',
     'PIN neeshereekwa omu muringo ogutarikugaruka -- tekirikubaasa kureeberwa, kirikubaasa kwonka kugaruzibwamu. Nekita ekishumuruzo ky\'obushuubuzi eky\'ebibaro 6 ekiri ahansi ahonaaho; kihe omuntu kugira ngo abaase kwihamu sente. Naabaasa kandi kukihindura we omwene omu puroguramu (Akaunti -> Trade Password).'],

    ['The screen a member sees before signing in. It has two parts, and each takes its own picture. Both apply to the Log In tab and the Sign Up tab — they share this screen, so one image each keeps the background steady when a member switches between them.',
     'Olupapula omuntu lw\'alaba nga tannayingira. Lulina ebitundu bibiri, era buli kimu kitwala ekifaananyi kyakyo. Byombi bikola ku ttabu lya Log In ne Sign Up — bigabana olupapula luno, kale ekifaananyi kimu ku buli kimu kikuuma emabega nga tewali kukyuka ng\'omuntu akyuka wakati waabyo.',
     'Skrini mwanachama anayoiona kabla ya kuingia. Ina sehemu mbili, na kila moja huchukua picha yake. Zote hutumika kwenye kichupo cha Log In na kichupo cha Sign Up — vinashiriki skrini hii, kwa hivyo picha moja kila upande huweka mandharinyuma imara mwanachama anapobadilisha kati yao.',
     'L\'écran qu\'un membre voit avant de se connecter. Il a deux parties, et chacune prend sa propre image. Les deux s\'appliquent à l\'onglet Log In et à l\'onglet Sign Up — ils partagent cet écran, donc une image chacun garde le fond stable quand un membre passe de l\'un à l\'autre.',
     'Ipaji umunyamuryango abona mbere yo kwinjira. Rifite ibice bibiri, kandi buri kimwe gifata ishusho yacyo. Byombi bikoreshwa ku gice cya Log In n\'icya Sign Up — bisangira iri paji, bityo ishusho imwe kuri buri kimwe ituma inyuma iguma idahindagurika iyo umunyamuryango ahinduranya.',
     'Orupapura omuntu arikureeba atakataahire. Ruine ebicweka bibiri, kandi buri kimwe nikitwara ekishushani kyakyo. Byombi nibikora aha kacweka ka Log In n\'aka Sign Up — nibigabana orupapura oru, n\'ahabw\'ekyo ekishushani kimwe aha buri kimwe nikikuuma enyima etarikuhinduka obu omuntu arikuhindura ahagati yaabyo.'],

    ['The video replaces the image on Home and runs on its own — muted, looping, no play button, and nothing to tap or pause. The image above is its still frame while it loads.',
     'Vidiyo eddira mu kifo ky\'ekifaananyi ku Home era etambula yokka — nga tesirika, ediza, nga terina bbaatani ya kuzannya, era nga tewali kya kukwatako oba okuyimiriza. Ekifaananyi ekiri waggulu kye kifaananyi kyayo ekiyimiridde nga ekyakkakkanya.',
     'Video huchukua nafasi ya picha kwenye Nyumbani na hucheza yenyewe — imenyamazishwa, hujirudia, hakuna kitufe cha kucheza, wala hakuna cha kugusa au kusimamisha. Picha iliyo juu ndiyo fremu yake tuli inapopakia.',
     'La vidéo remplace l\'image sur l\'Accueil et se joue toute seule — sans son, en boucle, sans bouton de lecture, et rien à toucher ni à mettre en pause. L\'image ci-dessus est son image fixe pendant le chargement.',
     'Videwo isimbura ishusho kuri Ahabanza kandi ikina yonyine — nta jwi, isubiramo, nta buto yo gukina, kandi nta cyo gukanda cyangwa guhagarika. Ishusho iri haruguru ni ishusho yayo ihamye mu gihe iracyapakirwa.',
     'Vidiyo neetwara omwanya gw\'ekishushani aha Home kandi neezaana yonka — etaine maraka, neegaruka, etaine kabatuni k\'okuzaana, kandi tihariho eky\'okukwataho nari okwemeza. Ekishushani ekiri haiguru n\'ekishushani kyayo ekyemiriire obu erikwija.'],

    ['The white panel carrying LOGIN / SIGN UP and the input boxes. Portrait, about 900 × 1200. It sits over the white card, so opacity blends it back toward white. Keep this one faint — try 20–35% opacity with some blur, or the text and the input boxes become hard to read.',
     'Akabaawo akeeru akalina LOGIN / SIGN UP n\'obubokisi obw\'okuwandiikamu. Eky\'obuwanvu, nga 900 × 1200. Kiteekebwa ku kaadi enjeru, kale obulabikirwa kikitabula okudda eri enjeru. Kireke kibe nga tekirabika nnyo — gezaako obulabikirwa 20–35% n\'akakoodozo katono, si ekyo ebiwandiiko n\'obubokisi bikaluba okusomeka.',
     'Paneli nyeupe yenye LOGIN / SIGN UP na visanduku vya kuandika. Wima, takriban 900 × 1200. Hukaa juu ya kadi nyeupe, kwa hivyo uwazi huichanganya kurudi kwenye weupe. Iache hii hafifu — jaribu uwazi wa 20–35% na ukungu kidogo, la sivyo maandishi na visanduku vya kuandika huwa vigumu kusoma.',
     'Le panneau blanc portant LOGIN / SIGN UP et les champs de saisie. Portrait, environ 900 × 1200. Il repose sur la carte blanche, donc l\'opacité le fond vers le blanc. Gardez celui-ci discret — essayez 20–35 % d\'opacité avec un peu de flou, sinon le texte et les champs deviennent difficiles à lire.',
     'Urubaho rwera rufite LOGIN / SIGN UP n\'utwanya two kwandikamo. Ruhagaritse, hafi 900 × 1200. Ruri hejuru y\'ikarita yera, bityo ukubonerana kuruvanga rugasubira ku bwera. Reka uru rube rutabonerana cyane — gerageza ukubonerana kwa 20–35% hamwe no kutabonerana gato, bitari ibyo inyandiko n\'utwanya two kwandikamo biragorana gusoma.',
     'Orubaaho orwera orwine LOGIN / SIGN UP n\'obubokisi bw\'okuhandiikamu. Oru kwemeera, nka 900 × 1200. Niruteekwa aha kaadi eyera, n\'ahabw\'ekyo okureeberwa nikirutabuura rikagaruka aha bwera. Reka oru rube rutarikureeberwa munonga — geezaho okureeberwa 20–35% hamwe n\'okwijwaijwa kukye, kutari ekyo ebihandiiko n\'obubokisi nibigumira kushomwa.'],

    ['This account has no referrer. If you later learn who invited them, attach it here -- their upline gets team credit, and if this member already made their first purchase, commission on it is paid now. Works once only; an account that already has a referrer can\'t be changed here.',
     'Akaawunti kano terina yaakuyita. Bw\'oluvannyuma omanya ani eyamuyita, mugatte wano -- oyo amuyita afuna ebibalirwa by\'ekibiina, era singa omuntu ono yamaze okugula omulundi ogusooka, ekitundu kyakyo kisasulwa kati. Kikola omulundi gumu gwokka; akaawunti akalina dda eyaakuyita tekakyusibwa wano.',
     'Akaunti hii haina mwalikaji. Ukija kujua baadaye ni nani aliyemwalika, mwambatanishe hapa -- mstari wake wa juu hupata sifa ya timu, na ikiwa mwanachama huyu tayari alinunua mara ya kwanza, kamisheni yake hulipwa sasa. Hufanya kazi mara moja tu; akaunti ambayo tayari ina mwalikaji haiwezi kubadilishwa hapa.',
     'Ce compte n\'a pas de parrain. Si vous apprenez plus tard qui l\'a invité, rattachez-le ici -- son parrain reçoit le crédit d\'équipe, et si ce membre a déjà fait son premier achat, la commission dessus est versée maintenant. Ne fonctionne qu\'une fois ; un compte qui a déjà un parrain ne peut pas être modifié ici.',
     'Iyi konti nta wayitumiye ifite. Nurangiza kumenya uwamutumiye, umuhuze hano -- uwamutumiye abona inyungu z\'itsinda, kandi niba uyu munyamuryango yamaze kugura bwa mbere, komisiyo yabyo yishyurwa nonaha. Bikora rimwe gusa; konti isanzwe ifite uwayitumiye ntishobora guhindurwa hano.',
     'Akaunti egi tiine owaayeeta. Ku oraamanye bwanyima ou yaamweta, mugambise hanu -- ou yaamweta naatunga ebibarwa by\'ekibiina, kandi ku omuntu ogu yaaba yaagwire omurundi gw\'okubanza, ekicweka kyakyo nikishashurwa hati. Nikikora omurundi gumwe gwonka; akaunti eine owaayeeta tekirikubaasa kuhindurwa hanu.'],

    ['What you upload here is the picture shared links show, on every address. Remove it and they go back to the card built into the app. Two delays to expect, neither a fault: a fresh share can keep showing the previous picture for up to five minutes, and WhatsApp and Facebook remember the old picture for a link that has already been shared — they keep the preview they first fetched. Sharing the link with anything after it — for example ?x=2 on the end — forces them to fetch it again.',
     'Ky\'oteeka wano kye kifaananyi amakubo agagabanibwa kye galaga, ku ndagiriro zonna. Kiggyeewo galiddayo ku kaadi eri mu app. Waliwo okulwawo kubiri okusuubirwa, era tekuli nsobi: okugabana okupya kuyinza okusigala nga kulaga ekifaananyi eky\'edda okumala eddakiika ttaano, era WhatsApp ne Facebook bajjukira ekifaananyi eky\'edda ku kkubo eryamala okugabanibwa — bakuuma kye baasooka okufuna. Okugabana ekkubo n\'akantu akakugoberera — ng\'ekyokulabirako ?x=2 ku nkomerero — kibawaliriza okuddamu okukifuna.',
     'Unachopakia hapa ndiyo picha ambayo viungo vinavyoshirikiwa huonyesha, kwenye kila anwani. Iondoe navyo hurudi kwenye kadi iliyojengwa ndani ya programu. Kuna ucheleweshaji wa aina mbili wa kutarajia, hakuna kati yake ni hitilafu: kushiriki kupya kunaweza kuendelea kuonyesha picha ya awali kwa hadi dakika tano, na WhatsApp na Facebook hukumbuka picha ya zamani kwa kiungo kilichokwisha shirikiwa — huhifadhi hakikisho walilochukua kwanza. Kushiriki kiungo na kitu chochote baada yake — mfano ?x=2 mwishoni — huwalazimisha kukichukua tena.',
     'Ce que vous téléversez ici est l\'image que montrent les liens partagés, sur toutes les adresses. Retirez-la et ils reviennent à la carte intégrée à l\'application. Deux délais à prévoir, aucun n\'est une panne : un nouveau partage peut continuer à montrer l\'image précédente pendant jusqu\'à cinq minutes, et WhatsApp et Facebook se souviennent de l\'ancienne image pour un lien déjà partagé — ils gardent l\'aperçu qu\'ils ont récupéré en premier. Partager le lien avec quelque chose après — par exemple ?x=2 à la fin — les oblige à le récupérer de nouveau.',
     'Icyo ushyizeho hano ni ishusho imirongo isangirwa yerekana, kuri buri aderesi. Uyikureho isubira ku ikarita yubatswe muri porogaramu. Hari gutinda kubiri byo kwitega, nta na kimwe ari ikibazo: gusangira gushya gushobora gukomeza kwerekana ishusho ya mbere kugeza ku iminota itanu, kandi WhatsApp na Facebook bibuka ishusho ya kera ku murongo wamaze gusangirwa — babika icyo babonye bwa mbere. Gusangira umurongo hiyongereyeho ikintu — urugero ?x=2 ku mpera — bibahatira kongera kubifata.',
     'Eki orikuta hanu n\'ekishushani emihanda erikugabanwa ei erikworeka, aha ndagiriro zoona. Kiihaho reero egaruke aha kaadi eri omu puroguramu. Hariho okuguma kubiri okw\'okwetegyereza, kandi tikuri kishobi: okugabana okusya nikubaasa kuguma nikworeka ekishushani ekya ira okuhitsya edakiika ishaanu, kandi WhatsApp na Facebook nibaijuka ekishushani ekya ira aha muhanda ogwamazire kugabanwa — nibakuuma eki baabandize kutunga. Okugabana omuhanda n\'ekintu ekigukuratira — nk\'eky\'okureeberaho ?x=2 aha muheru — nikibahatsya kugarukamu kukitunga.'],

    ['While enabled and this time is still in the future, every user (new or existing) sees the countdown instead of the login/app -- it turns off on its own once the time passes, or uncheck it here to open early.',
     'Nga kikola era ng\'ekiseera kino kikyali mu maaso, buli muntu (omuggya oba ow\'edda) alaba okubala okudda emabega mu kifo ky\'okuyingira/app -- kizikira kyokka ng\'ekiseera kiyiseeko, oba kiggyeko wano okuggulawo amangu.',
     'Ikiwa imewashwa na wakati huu bado uko mbele, kila mtumiaji (mpya au aliyepo) huona hesabu ya kurudi nyuma badala ya kuingia au programu -- huzimika yenyewe wakati unapopita, au uondoe alama hapa ili kufungua mapema.',
     'Tant que c\'est activé et que cette heure est encore à venir, chaque utilisateur (nouveau ou existant) voit le compte à rebours à la place de la connexion ou de l\'application -- il se désactive tout seul une fois l\'heure passée, ou décochez ici pour ouvrir plus tôt.',
     'Igihe bikoresha kandi iki gihe kikiri imbere, buri ukoresha (mushya cyangwa usanzweho) abona kubara manuka aho kwinjira cyangwa porogaramu -- bihagarara byonyine iyo igihe gishize, cyangwa ukureho akamenyetso hano kugira ngo ufungure hakiri kare.',
     'Ku erikuba erikukora kandi obu obwire obu bukiri omu maisho, buri murikukoresa (omusya nari orikubaho) naareeba okubara okugaruka enyima omu mwanya gw\'okutaaha nari puroguramu -- nikyezimya ku obwire burikuhwa, nari oihemu akamanyiso hanu kugira ngo oigure kare.'],

    ['Withdrawals are separate from the toggles above -- payouts still use exactly one method at a time, set below. On Manual, no automatic gateway is in the payout path: you send each cash-out yourself from an admin phone and then tap Mark as paid on the Withdrawals tab to record it. Auto-approve is ignored whenever payouts are manual, since nothing should be marked paid without a person actually sending the money.',
     'Okuggyamu ssente kwawukana ku bikyusibwa waggulu -- okusasula kukozesa engeri emu yokka mu kiseera, nga eteekeddwa wansi. Ku Manual, tewali mulyango gwekolera mu kkubo ly\'okusasula: buli kuggyamu osindika ggwe kennyini okuva ku ssimu y\'omukulembeze n\'oluvannyuma onyige Laga nga kisasuddwa ku ttabu lya Okuggyamu okukiwandiika. Okukkiriza okwekolera tekussibwako mmere buli lwe okusasula kuba kwa ngalo, kubanga tewali kirina kulagibwa nga kisasuddwa nga tewali muntu asindise ssente.',
     'Utoaji ni tofauti na vishikizo vilivyo hapo juu -- malipo bado hutumia njia moja tu kwa wakati, iliyowekwa hapa chini. Kwenye Manual, hakuna lango la kiotomatiki kwenye njia ya malipo: unatuma kila utoaji wewe mwenyewe kutoka simu ya msimamizi kisha unagusa Weka alama kuwa imelipwa kwenye kichupo cha Utoaji ili kurekodi. Kuidhinisha kiotomatiki hupuuzwa kila malipo yanapokuwa ya mkono, kwa sababu hakuna kinachopaswa kuwekwa alama kuwa kimelipwa bila mtu kutuma pesa kweli.',
     'Les retraits sont indépendants des interrupteurs ci-dessus -- les versements utilisent toujours exactement une seule méthode à la fois, réglée ci-dessous. En Manuel, aucune passerelle automatique n\'est dans le chemin de versement : vous envoyez chaque retrait vous-même depuis un téléphone d\'administrateur puis touchez Marquer comme payé dans l\'onglet Retraits pour l\'enregistrer. L\'approbation automatique est ignorée dès que les versements sont manuels, car rien ne doit être marqué payé sans qu\'une personne ait réellement envoyé l\'argent.',
     'Kubikuza bitandukanye n\'utubuto two haruguru -- kwishyura gukoresha uburyo bumwe gusa icyarimwe, bushyizweho hasi. Kuri Manual, nta irembo ryikora riri mu nzira yo kwishyura: wowe ubwawe wohereza buri kubikuza uvuye kuri telefoni y\'ubuyobozi hanyuma ugakanda Shyiraho ko byishyuwe ku gice cy\'Ukubikuza kugira ngo ubyandike. Kwemeza byikora ntibyitabwaho igihe cyose kwishyura ari ukw\'intoki, kuko nta kigomba gushyirwaho ko cyishyuwe umuntu atohereje amafaranga koko.',
     'Okwihamu sente nikwahukana n\'ebirikuhindurwa haiguru -- okushashura nikukoresa omuringo gumwe gwonka aha mwanya, ogutairweho ahansi. Aha Manual, tihariho muryango gurikwekorera omu muhanda gw\'okushashura: iwe omwene notuma buri kwihamu kuruga aha simu y\'omwebembezi reero okakanda Manyisa ngu kishashwiirwe aha kacweka k\'Okwihamu kugira ngo okihandiike. Okwikiriza kwenka tikurikutwarwaho obwiraaboona okushashura kuri okw\'engaro, ahakuba tihariho ekishemereire kumanyisibwa ngu kishashwiirwe omuntu atatumire sente buzima.'],

    ['You (the owner) always sign in with the master admin key. It\'s never given to anyone below. Create a separate username + password for each other person who needs access.',
     'Ggwe (nannyini yo) bulijjo oyingira n\'ekisumuluzo ekikulu eky\'obukulembeze. Tekiweebwa muntu yenna ali wansi. Kolera buli muntu omulala ayetaaga okuyingira erinnya n\'ekisumuluzo ebyayo.',
     'Wewe (mmiliki) huingia daima kwa ufunguo mkuu wa msimamizi. Hautolewi kamwe kwa mtu yeyote aliye chini. Tengeneza jina la mtumiaji na nenosiri tofauti kwa kila mtu mwingine anayehitaji kuingia.',
     'Vous (le propriétaire) vous connectez toujours avec la clé administrateur principale. Elle n\'est jamais donnée à quelqu\'un en dessous. Créez un nom d\'utilisateur et un mot de passe distincts pour chaque autre personne ayant besoin d\'un accès.',
     'Wowe (nyir\'ubwite) buri gihe winjira ukoresheje urufunguzo rukuru rw\'ubuyobozi. Ntiruhabwa na rimwe umuntu uri hasi. Korera buri wundi muntu ukeneye kwinjira izina n\'ijambobanga bye.',
     'Iwe (nyineyo) obutoosha notaaha n\'ekishumuruzo ekikuru eky\'obwebembezi. Tikirikuheebwa muntu weena ori ahansi. Korera buri muntu ondiijo orikwetenga kutaaha eiziina n\'ekishumuruzo ebye.'],

    ['Your root domain and www are not closed. "The root domain does not serve the app" can only recognise them once this setting names your real domain, so until then they serve the app like any other address.',
     'Root domain yo ne www tebiggaddwa. "The root domain does not serve the app" esobola okubimanya lwa ekiteeso kino nga kiwadde erinnya lya domain yo ey\'amazima, kale okutuusa olwo biweereza app nga endagiriro endala zonna.',
     'Kikoa chako cha msingi na www havijafungwa. "The root domain does not serve the app" inaweza kuvitambua tu pale mpangilio huu unapotaja kikoa chako halisi, kwa hivyo hadi wakati huo huhudumia programu kama anwani nyingine yoyote.',
     'Votre domaine racine et www ne sont pas fermés. "The root domain does not serve the app" ne peut les reconnaître qu\'une fois que ce réglage nomme votre vrai domaine, donc jusque-là ils servent l\'application comme n\'importe quelle autre adresse.',
     'Izina ryawe ry\'urufatiro na www ntibyafunzwe. "The root domain does not serve the app" ishobora kubimenya gusa iyo iri genamiterere ryanditse izina ryawe nyaryo, bityo kugeza icyo gihe bitanga porogaramu nk\'aderesi iyo ari yo yose.',
     'Root domain yaawe na www tibikingirwe. "The root domain does not serve the app" nebaasa kubimanya kwonka obu okuta oku kurikweta eiziina ryaawe eriyo buzima, n\'ahabw\'ekyo okuhitsya obwo nibiheereza puroguramu nk\'endagiriro yoona endiijo.'],
]
