#!/usr/bin/env python3
"""Batch 12: the last five.

Four instruction paragraphs the earlier batches skipped, plus the "Manual
payments" heading and the cash-out hours note as it reads after Round 172
corrected it (it used to say "East Africa Time" and give its example on a
12-hour clock, both wrong once there is more than one country).

The Countries paragraph is keyed on the ENGLISH "Settings and Products tabs".
The sweep reports it with those two words already in Swahili, because while no
row matches the whole sentence the per-node pass translates the <b> inside it
-- so copying what the sweep printed would produce a key that can never match.

[english, lg, sw, fr, rw, nyn]
"""
ROWS = [
    ['An animated GIF shown beside the profile icon at the top of the app\'s Account tab. Transparency is kept. Uploaded exactly as-is so the animation survives — every other image slot here is re-compressed, which would flatten a GIF to a single still frame. Keep it small: it loads on every member\'s phone, so aim for well under 400 KB (a 300×220 GIF of about 94 KB is ideal).',
     'GIF etambula eraga ku mabbali g\'akafaananyi k\'omuntu waggulu ku ttabu lya Akaawunti. Obwereere bukuumibwa. Eteekebwa nga bw\'eri okusobola okukuuma okutambula — buli kifo ky\'ebifaananyi ekirala wano kinyigirizibwa, ekyandifudde GIF ekifaananyi kimu ekiyimiridde. Gikuume ntono: ekkakkanyizibwa ku ssimu ya buli muntu, kale gezaako wansi wa 400 KB (GIF eya 300×220 eya 94 KB esinga obulungi).',
     'GIF inayosogea inayoonyeshwa kando ya aikoni ya wasifu juu ya kichupo cha Akaunti. Uwazi huhifadhiwa. Hupakiwa kama ilivyo ili uhuishaji uendelee — kila nafasi nyingine ya picha hapa hubanwa upya, jambo ambalo lingeifanya GIF kuwa fremu moja tuli. Iweke ndogo: hupakuliwa kwenye simu ya kila mwanachama, kwa hivyo lenga chini ya 400 KB (GIF ya 300×220 ya takriban 94 KB ndiyo bora).',
     'Un GIF animé affiché à côté de l\'icône de profil en haut de l\'onglet Compte de l\'application. La transparence est conservée. Téléversé tel quel pour que l\'animation survive — tous les autres emplacements d\'image ici sont recompressés, ce qui réduirait un GIF à une seule image fixe. Gardez-le petit : il se charge sur le téléphone de chaque membre, visez donc bien en dessous de 400 Ko (un GIF 300×220 d\'environ 94 Ko est idéal).',
     'GIF inyeganyega igaragara iruhande rw\'agashushondanga k\'umwirondoro hejuru ku gice cya Konti cya porogaramu. Ububonerane burabikwa. Ishyirwaho uko iri kugira ngo inyeganyega idapfa — ahandi hose h\'amashusho hano hongera guhindurwa hato, bigatuma GIF iba ishusho imwe ihagaze. Igire nto: imanurwa kuri telefoni ya buri munyamuryango, bityo ugerageze munsi ya 400 KB (GIF ya 300×220 ya hafi 94 KB ni yo nziza).',
     'GIF erikugyenda erikureeberwa aha rubaju rw\'akashushani k\'omuntu haiguru aha kacweka ka Akaunti. Obwereere nibukuumwa. Neetebekwa nk\'oku eri kugira ngo okugyenda kutafa — omwanya gwoona ogundi gw\'ebishushani hanu nigugarukamu kunyigwa, ekiraakuhindwire GIF ekishushani kimwe ekyemiriire. Gikuume enkye: neeihurwa aha nyabarugo ya buri muntu, n\'ahabw\'ekyo geezaho ahansi ya 400 KB (GIF ya 300×220 eya nka 94 KB niyo nungi.)'],

    ['Each country has its own subdomain, currency, dialling code and number shape. Its rates and its product prices are edited on the Settings and Products tabs with that country picked at the top. A member belongs to the country they signed up on, for good: they always see that country\'s currency and prices, even if they open another country\'s address. + 5 mints five short addresses at once. That is what Settings → Move arrivals to another address needs: it sends each new visitor on to a different one of this country\'s addresses, and with only one address there is nowhere to send them.',
     'Buli ggwanga lirina subdomain yaalyo, ssente zaalyo, koodi y\'okukuba n\'engeri ya nnamba. Emiwendo gyalyo n\'ebbeeyi z\'ebyamaguzi bikyusibwa ku ttabu lya Settings ne Products ng\'eggwanga eryo lirondeddwa waggulu. Omuntu aba wa ggwanga lye yeewandiisizzaako, emirembe gyonna: bulijjo alaba ssente n\'ebbeeyi z\'eggwanga eryo, ne bw\'aggula endagiriro y\'eggwanga eddala. + 5 ekola endagiriro ttaano empi omulundi gumu. Ekyo kye kyetaagisa mu Settings → Move arrivals to another address: kisindika buli mugenyi omuggya ku ndagiriro ya ggwanga lino endala, ate nga tewali ndagiriro ndala tewali gy\'ayinza kusindikibwa.',
     'Kila nchi ina kikoa chake kidogo, sarafu yake, msimbo wa kupiga simu na umbo la namba. Viwango vyake na bei za bidhaa zake huhaririwa kwenye vichupo vya Settings na Products nchi hiyo ikiwa imechaguliwa hapo juu. Mwanachama ni wa nchi aliyojisajili, milele: huona daima sarafu na bei za nchi hiyo, hata akifungua anwani ya nchi nyingine. + 5 hutengeneza anwani fupi tano kwa mara moja. Ndicho kinachohitajika na Settings → Move arrivals to another address: hupeleka kila mgeni mpya kwenye anwani nyingine ya nchi hii, na kwa anwani moja tu hakuna pa kumpeleka.',
     'Chaque pays a son propre sous-domaine, sa devise, son indicatif et sa forme de numéro. Ses taux et les prix de ses produits se modifient dans les onglets Settings et Products avec ce pays sélectionné en haut. Un membre appartient au pays où il s\'est inscrit, définitivement : il voit toujours la devise et les prix de ce pays, même s\'il ouvre l\'adresse d\'un autre pays. + 5 crée cinq adresses courtes d\'un coup. C\'est ce dont Settings → Move arrivals to another address a besoin : il envoie chaque nouveau visiteur vers une autre adresse de ce pays, et avec une seule adresse il n\'y a nulle part où l\'envoyer.',
     'Buri gihugu gifite urubuga rwacyo rwungirije, ifaranga ryacyo, kode yo guhamagara n\'isura ya nimero. Ibipimo byacyo n\'ibiciro by\'ibicuruzwa byacyo bihindurirwa ku bice bya Settings na Products icyo gihugu gitoranyijwe haruguru. Umunyamuryango ni uw\'igihugu yiyandikishijemo, burundu: ahora abona ifaranga n\'ibiciro by\'icyo gihugu, n\'iyo yafungura aderesi y\'ikindi gihugu. + 5 ikora aderesi ngufi eshanu icyarimwe. Ni byo Settings → Move arrivals to another address ikeneye: yohereza buri mushyitsi mushya ku yindi aderesi y\'iki gihugu, kandi iyo hari aderesi imwe gusa nta ho yoherezwa.',
     'Buri ihanga riine subdomain yaaryo, sente zaaryo, koodi y\'okuteera n\'enshusha ya namba. Emiihendo yaaryo n\'ebiihendo by\'ebyamaguzi byaryo nibihindurirwa aha bicweka bya Settings na Products eihanga eryo riracwiirwemu haiguru. Omuntu n\'ow\'eihanga eri yeeyandiisizemu, ebiro byoona: obutoosha naareeba sente n\'ebiihendo by\'eihanga eryo, n\'obu yaakwigura endagiriro y\'eihanga erindi. + 5 neekora endagiriro ishaanu enguufu omurundi gumwe. Ekyo nikyo Settings → Move arrivals to another address erikwetenga: neetuma buri mugyenyi omusya aha ndagiriro endiijo y\'eihanga eri, kandi ku hakubaho endagiriro emwe yonka tihariho ei arikubaasa kutumwa.'],

    ['Manual payments',
     'Okusasula n\'engalo',
     'Malipo ya mkono',
     'Paiements manuels',
     'Kwishyura n\'intoki',
     'Okushashura n\'engaro'],

    ['The platform\'s name. Changing it renames it everywhere inside the app — the Home wordmark, the profile badge, the loading and sign-in screens, About, Get the app, the browser tab, and the wording on admin credits from now on. Members see it the next time they open the app. Two places keep the old name until the frontend is re-uploaded: the name Android shows under the installed icon, and the title on a shared link — both are read out of files the phone downloads once, not from these settings. Up to 24 characters.',
     'Erinnya ly\'ekitongole. Okulikyusa kukyusa erinnya buli wantu mu app — akabonero ka Home, akapapula k\'omuntu, olupapula olw\'okutegeka n\'olw\'okuyingira, Ebikwata Ku Ffe, Funa app, ttabu lya bbulawuza, n\'ebigambo ku ssente ezongerwa bakulembeze okuva kati. Abantu baliraba omulundi oguddako lwe bajja okuggula app. Ebifo bibiri bisigala n\'erinnya ery\'edda okutuusa ng\'ebweru bwa app bizzeemu okuteekebwa: erinnya Android ly\'eraga wansi w\'akafaananyi, n\'omutwe ku kkubo erigabanibwa — byombi bisomebwa okuva mu fayiro essimu z\'ekkakkanya omulundi gumu, si okuva mu biteeso bino. Okutuuka ku nnukuta 24.',
     'Jina la jukwaa. Kulibadilisha hulibadilisha kila mahali ndani ya programu — nembo ya Nyumbani, beji ya wasifu, skrini za kupakia na kuingia, Kutuhusu, Pata programu, kichupo cha kivinjari, na maneno kwenye salio zinazoongezwa na msimamizi kuanzia sasa. Wanachama huliona wakati mwingine watakapofungua programu. Sehemu mbili hubaki na jina la zamani hadi sehemu ya mbele itakapopakiwa upya: jina Android inaloonyesha chini ya aikoni iliyosakinishwa, na kichwa kwenye kiungo kilichoshirikiwa — vyote husomwa kutoka faili ambazo simu hupakua mara moja, si kutoka mipangilio hii. Hadi herufi 24.',
     'Le nom de la plateforme. Le changer le renomme partout dans l\'application — le logotype de l\'Accueil, le badge du profil, les écrans de chargement et de connexion, À propos, Obtenir l\'application, l\'onglet du navigateur, et le libellé des crédits administrateur à partir de maintenant. Les membres le voient à la prochaine ouverture de l\'application. Deux endroits gardent l\'ancien nom jusqu\'au prochain téléversement du frontend : le nom qu\'Android affiche sous l\'icône installée, et le titre d\'un lien partagé — les deux sont lus dans des fichiers que le téléphone télécharge une fois, pas depuis ces réglages. Jusqu\'à 24 caractères.',
     'Izina ry\'urubuga. Kurihindura birihindura hose imbere muri porogaramu — ikirango cya Ahabanza, akarango k\'umwirondoro, amapaji yo gupakira no kwinjira, Ibyerekeye, Kubona porogaramu, igice cy\'umushakisha, n\'amagambo ku mafaranga ubuyobozi bwongera kuva ubu. Abanyamuryango barirebera ubutaha bafunguye porogaramu. Ahantu habiri hagumana izina rya kera kugeza igice cy\'imbere cyongeye gushyirwaho: izina Android yerekana munsi y\'agashushondanga kashyizweho, n\'umutwe ku murongo wasangiwe — byombi bisomwa muri dosiye telefoni imanura rimwe, atari muri aya magenamiterere. Kugeza ku nyuguti 24.',
     'Eiziina ry\'ekitongore. Okurihindura nikihindura eiziina hoona omunda ya puroguramu — akamanyiso ka Home, akapapura k\'omuntu, orupapura rw\'okutebeka n\'orw\'okutaaha, Ebirikutukwataho, Tunga puroguramu, akacweka ka buraawuza, n\'ebigambo aha sente ezirikwongyerwa abebembezi kuruga hati. Abantu nibaza kurireeba omurundi ogurikwija ku barikwigura puroguramu. Ebifo bibiri nibisigara n\'eiziina rya ira okuhitsya obu aha rubaju rw\'omu maisho harigaruka kutaho: eiziina Android eri kworeka ahansi y\'akashushani akatairweho, n\'omutwe aha muhanda ogurikugabanwa — byombi nibishomwa kuruga omu mafaira agu esimu erikwihura omurundi gumwe, ti kuruga omu ntebeka ezi. Okuhitsya aha buhandiiko 24.'],

    ['Times are 24-hour, in the selected country\'s own local time. The window may run past midnight — set 18:00 to 17:00 and cash-out is open all day except between 17:00 and 18:00. Members always see exactly these hours, and the server refuses a request outside them, not just the app.',
     'Ebiseera bya ssaawa 24, mu budde bw\'eggwanga eriroNdeddwa. Ekiseera kiyinza okuyita mu ttumbi — teeka 18:00 okutuuka 17:00 n\'okuggyamu ssente kuggulwa olunaku lwonna okuggyako wakati wa 17:00 ne 18:00. Abantu bulijjo balaba essaawa zino nga bwe ziri, era sseva egaana okusaba okuli ebweru waazo, si app yokka.',
     'Nyakati ni za saa 24, kwa saa za nchi iliyochaguliwa. Dirisha linaweza kupita usiku wa manane — weka 18:00 hadi 17:00 na utoaji hufunguka siku nzima isipokuwa kati ya 17:00 na 18:00. Wanachama huona daima saa hizi hasa, na seva hukataa ombi lililo nje yake, si programu tu.',
     'Les heures sont au format 24 heures, dans l\'heure locale du pays sélectionné. La fenêtre peut passer minuit — réglez 18:00 à 17:00 et le retrait est ouvert toute la journée sauf entre 17:00 et 18:00. Les membres voient toujours exactement ces heures, et le serveur refuse une demande en dehors, pas seulement l\'application.',
     'Amasaha ni ay\'amasaha 24, mu gihe cy\'igihugu cyatoranyijwe. Idirishya rishobora kurenga saa sita z\'ijoro — shyira 18:00 kugeza 17:00 maze kubikuza bigafungurwa umunsi wose usibye hagati ya 17:00 na 18:00. Abanyamuryango bahora babona neza aya masaha, kandi seriveri yanga ubusabe buri hanze yayo, atari porogaramu gusa.',
     'Obwire n\'obw\'eshaaha 24, omu bwire bw\'eihanga eryacwiirwemu. Obwire nibubaasa kuraba omu kiro — ta 18:00 okuhika 17:00 reero okwihamu sente kwigurwe eizooba ryoona kureka ahagati ya 17:00 na 18:00. Abantu obutoosha nibareeba eshaaha ezi nk\'oku ziri, kandi seeva neeyanga okushaba okuri aheeru yaazo, ti puroguramu yonka.'],
]
