#!/usr/bin/env python3
"""Batch 2 of the admin panel's own string table: the controls.

Buttons, form labels, field placeholders and the one-line captions under
them. [english, lg, sw, fr, rw, nyn]
"""
ROWS = [
    # ── buttons that act on a member ──
    ['Ban', 'Gaana', 'Zuia', 'Bloquer', 'Kubuza', 'Zibira'],
    ['Credit', 'Muwe ssente', 'Ongeza pesa', 'Créditer', 'Kongeraho amafaranga', 'Mumuhe sente'],
    ['Debit', 'Muggyeko ssente', 'Toa pesa', 'Débiter', 'Gukuraho amafaranga', 'Mwihyeho sente'],
    ['Attach', 'Gattako', 'Ambatisha', 'Rattacher', 'Gushyiraho', 'Gyemesa'],
    ['Attach referrer', 'Gattako oyo ayise', 'Ambatisha mwalikaji', 'Rattacher un parrain', 'Gushyiraho uwatumiye', 'Gyemesa oworikweta'],
    ['Set PIN', 'Teekawo PIN', 'Weka PIN', 'Définir le PIN', 'Shyiraho PIN', 'Taho PIN'],
    ['Reconcile', 'Tereeza', 'Linganisha', 'Réconcilier', 'Kuringaniza', 'Gyerenganisa'],
    ['Delete account', 'Sazaamu akawunti', 'Futa akaunti', 'Supprimer le compte', 'Gusiba konti', 'Rihamu akaunti'],
    ['View referral chain', 'Laba olunyiriri lw\'okuyita', 'Angalia mnyororo wa mialiko', 'Voir la chaîne de parrainage', 'Reba urunigi rwo gutumira', 'Reeba omunyororo gw\'okweta'],
    ['Integrity audit', 'Okukebera obutuufu', 'Ukaguzi wa usahihi', 'Audit d\'intégrité', 'Igenzura ry\'ukuri', 'Okucondooza obwesigwa'],
    ['Recalculate totals', 'Ddamu obale omugatte', 'Hesabu upya jumla', 'Recalculer les totaux', 'Kongera kubara ibiteranyo', 'Garuka obare omugatte'],
    ['Shorten account ids', 'Kendeeza namba z\'akawunti', 'Fupisha vitambulisho vya akaunti', 'Raccourcir les identifiants', 'Kugabanya indangamuntu za konti', 'Kyeeneza namba za akaunti'],
    ['Reset password (Firebase)', 'Kyusa ekisumuluzo (Firebase)', 'Weka upya nenosiri (Firebase)', 'Réinitialiser le mot de passe (Firebase)', 'Guhindura ijambobanga (Firebase)', 'Hindura ekisumuruzo (Firebase)'],
    ['Correct phone number', 'Tereeza namba y\'essimu', 'Rekebisha namba ya simu', 'Corriger le numéro de téléphone', 'Gukosora nomero ya telefone', 'Gyerurura namba ya esimu'],
    ['Save phone', 'Tereka essimu', 'Hifadhi simu', 'Enregistrer le téléphone', 'Bika telefone', 'Biika esimu'],
    ['Looks malformed', 'Kirabika tekituufu', 'Inaonekana si sahihi', 'Semble mal formé', 'Bisa nk\'aho ari bibi', 'Nikireebeka kitahikire'],
    ['Not set yet', 'Tekinnateekebwawo', 'Bado haijawekwa', 'Pas encore défini', 'Ntiryashyizweho', 'Tikirataho'],
    ['New 6-digit trade password', 'Ekisumuluzo eky\'okusuubula ekipya eky\'ennamba 6', 'Nenosiri jipya la malipo la tarakimu 6', 'Nouveau mot de passe de transaction à 6 chiffres', 'Ijambobanga rishya ry\'ubucuruzi ry\'imibare 6', 'Ekisumuruzo kisya eky\'okushuubura eky\'embaro 6'],
    ['New password (min 6 chars)', 'Ekisumuluzo ekipya (obutono nnukuta 6)', 'Nenosiri jipya (angalau herufi 6)', 'Nouveau mot de passe (6 caractères minimum)', 'Ijambobanga rishya (byibuze inyuguti 6)', 'Ekisumuruzo kisya (buriijo obuhandiiko 6)'],
    ['Note (optional)', 'Obubaka (si bwa buwaze)', 'Dokezo (si lazima)', 'Note (facultatif)', 'Inyandiko (ntabwo ari itegeko)', 'Ekiraburo (tikya buriijo)'],
    ['No plans purchased yet.', 'Tewali nteekateeka egguliddwa.', 'Hakuna mipango iliyonunuliwa bado.', 'Aucun plan acheté pour le moment.', 'Nta gahunda iraguzwa.', 'Tihariho nteekateeka egwiiribwe.'],
    ['Saved cash-out accounts', 'Akawunti z\'okuggyamu ssente eziterekeddwa', 'Akaunti za utoaji zilizohifadhiwa', 'Comptes de retrait enregistrés', 'Konti zo kubikuza zabitswe', 'Akaunti z\'okwihamu sente ezibiikirwe'],
    ['Search phone or referral code', 'Noonya essimu oba koodi y\'okuyita', 'Tafuta simu au msimbo wa mwaliko', 'Rechercher un téléphone ou un code de parrainage', 'Shakisha telefone cyangwa kode yo gutumira', 'Sherura esimu nari koodi y\'okweta'],
    ['Search any phone number or referral code', 'Noonya namba y\'essimu yonna oba koodi y\'okuyita', 'Tafuta namba yoyote ya simu au msimbo wa mwaliko', 'Rechercher n\'importe quel numéro ou code de parrainage', 'Shakisha nomero iyo ari yo yose ya telefone cyangwa kode yo gutumira', 'Sherura namba ya esimu yoona nari koodi y\'okweta'],
    ['Search description, type, user id, or a reference', 'Noonya ennyinyonnyola, ekika, namba y\'omukozesa, oba namba y\'okujuliza', 'Tafuta maelezo, aina, kitambulisho cha mtumiaji, au kumbukumbu', 'Rechercher une description, un type, un identifiant ou une référence', 'Shakisha ibisobanuro, ubwoko, indangamuntu y\'umukoresha, cyangwa icyitegererezo', 'Sherura okushoboorora, ekika, namba y\'omukozesa, nari namba y\'okwijuka'],

    # ── admin accounts ──
    ['Admin accounts', 'Akawunti z\'abaduumizi', 'Akaunti za wasimamizi', 'Comptes administrateurs', 'Konti z\'abayobozi', 'Akaunti z\'abebembezi'],
    ['Create admin account', 'Tondawo akawunti y\'omuduumizi', 'Tengeneza akaunti ya msimamizi', 'Créer un compte administrateur', 'Gukora konti y\'umuyobozi', 'Hanga akaunti y\'omwebembezi'],
    ['Username', 'Erinnya ly\'omukozesa', 'Jina la mtumiaji', 'Nom d\'utilisateur', 'Izina ry\'umukoresha', 'Eiziina ry\'omukozesa'],
    ['Password', 'Ekisumuluzo', 'Nenosiri', 'Mot de passe', 'Ijambobanga', 'Ekisumuruzo'],
    ['Admin key / password', 'Ekisumuluzo ky\'omuduumizi', 'Ufunguo wa msimamizi / nenosiri', 'Clé administrateur / mot de passe', 'Urufunguzo rw\'umuyobozi / ijambobanga', 'Ekisumuruzo ky\'omwebembezi'],
    ['At least 8 characters', 'Obutono nnukuta 8', 'Angalau herufi 8', 'Au moins 8 caractères', 'Byibuze inyuguti 8', 'Buriijo obuhandiiko 8'],
    ['e.g. mary', 'okugeza mary', 'mfano mary', 'ex. mary', 'urugero mary', 'nk\'okugyera mary'],
    ['Deactivate', 'Sirika', 'Zima', 'Désactiver', 'Guhagarika', 'Zimya'],
    ['Reactivate', 'Ddamu okuteeka mu nkola', 'Washa tena', 'Réactiver', 'Kongera gukoresha', 'Garuka okimu omu mirimo'],
    ['Deactivated', 'Kisiriddwa', 'Imezimwa', 'Désactivé', 'Byahagaritswe', 'Kizimirwe'],
    ['Reset password', 'Kyusa ekisumuluzo', 'Weka upya nenosiri', 'Réinitialiser le mot de passe', 'Guhindura ijambobanga', 'Hindura ekisumuruzo'],
    ['Delete', 'Sazaamu', 'Futa', 'Supprimer', 'Gusiba', 'Rihamu'],
    ['Edit', 'Kyusa', 'Hariri', 'Modifier', 'Guhindura', 'Hindura'],
    ['Log out', 'Fuluma', 'Toka', 'Se déconnecter', 'Gusohoka', 'Ruga omu'],
    ['new', 'kipya', 'mpya', 'nouveau', 'gishya', 'kisya'],
    ['Check', 'Kebera', 'Angalia', 'Vérifier', 'Kugenzura', 'Reeba'],
    ['Order', 'Entegeka', 'Mpangilio', 'Ordre', 'Urutonde', 'Entegyeka'],
    ['Clear all', 'Sazaamu byonna', 'Futa vyote', 'Tout effacer', 'Gusiba byose', 'Rihamu byona'],

    # ── products ──
    ['+ New product', '+ Ekyamaguzi ekipya', '+ Bidhaa mpya', '+ Nouveau produit', '+ Igicuruzwa gishya', '+ Ekyamaguzi kisya'],
    ['Fix duplicate keys', 'Tereeza ebisumuluzo ebyeddiŋŋana', 'Rekebisha funguo zinazorudiwa', 'Corriger les clés en double', 'Gukosora imfunguzo zisubiranamo', 'Gyerurura ebisumuruzo ebirikwegarukamu'],
    ['Sync pricing to defaults', 'Zzaayo ebbeeyi ku ntereka entongole', 'Rejesha bei kwa chaguo-msingi', 'Rétablir les prix par défaut', 'Gusubiza ibiciro ku byahoze', 'Garuza ebiingana aha bitairweho'],
    ['Cycle (days)', 'Ebbanga (ennaku)', 'Mzunguko (siku)', 'Cycle (jours)', 'Uruziga (iminsi)', 'Obwire (ebiro)'],
    ['Return multiple (×)', 'Emirundi gy\'okuddizibwa (×)', 'Kizidishi cha marejesho (×)', 'Multiplicateur de retour (×)', 'Inshuro z\'inyungu (×)', 'Emirundi y\'okugarurwa (×)'],

    # ── gift codes ──
    ['Generate codes', 'Kola koodi', 'Tengeneza misimbo', 'Générer des codes', 'Gukora kode', 'Hanga koodi'],
    ['How many', 'Mmeka', 'Ngapi', 'Combien', 'Zingahe', 'Ningahe'],
    ['Reward range', 'Ekigero ky\'empeera', 'Kiwango cha zawadi', 'Fourchette de récompense', 'Urwego rw\'ibihembo', 'Ekigyero ky\'empeera'],
    ['Min reward (UGX)', 'Empeera esinga obutono (UGX)', 'Zawadi ndogo (UGX)', 'Récompense minimale (UGX)', 'Igihembo gito (UGX)', 'Empeera erikukira obukye (UGX)'],
    ['Max reward (UGX)', 'Empeera esinga obunene (UGX)', 'Zawadi kubwa (UGX)', 'Récompense maximale (UGX)', 'Igihembo kinini (UGX)', 'Empeera erikukira obwingi (UGX)'],
    ['Max uses per code (optional)', 'Emirundi egisinga buli koodi (si kya buwaze)', 'Matumizi mengi kwa msimbo (si lazima)', 'Utilisations max par code (facultatif)', 'Inshuro ntarengwa kuri buri kode (ntabwo ari itegeko)', 'Emirundi erikukira aha buri koodi (tikya buriijo)'],
    ['Expires after (seconds, optional)', 'Kiggwaako oluvannyuma (obutundutundu, si kya buwaze)', 'Inaisha baada ya (sekunde, si lazima)', 'Expire après (secondes, facultatif)', 'Birangira nyuma ya (amasegonda, ntabwo ari itegeko)', 'Nikihwaho bwanyima ya (obucweka, tikya buriijo)'],
    ['e.g. 30 for a flash code', 'okugeza 30 ku koodi ey\'akaseera', 'mfano 30 kwa msimbo wa haraka', 'ex. 30 pour un code éclair', 'urugero 30 kuri kode y\'igihe gito', 'nk\'okugyera 30 aha koodi y\'akaanya'],
    ['Total claimed', 'Omugatte oguggiddwa', 'Jumla iliyodaiwa', 'Total réclamé', 'Igiteranyo cyafashwe', 'Omugatte ogutwiirwe'],

    # ── messages ──
    ['Post message', 'Teeka obubaka', 'Tuma ujumbe', 'Publier le message', 'Kohereza ubutumwa', 'Tuma obutumwa'],
    ['Posted messages', 'Obubaka obuweereddwa', 'Ujumbe uliotumwa', 'Messages publiés', 'Ubutumwa bwoherejwe', 'Obutumwa oburikuba butumirwe'],
    ['ID (blank = new)', 'Namba (bwe kiba kyereere = kipya)', 'Kitambulisho (tupu = mpya)', 'ID (vide = nouveau)', 'Indangamuntu (ubusa = gishya)', 'Namba (ku erikuba etariho = kisya)'],
    ['Title (optional)', 'Omutwe (si gwa buwaze)', 'Kichwa (si lazima)', 'Titre (facultatif)', 'Umutwe (ntabwo ari itegeko)', 'Omutwe (tigwa buriijo)'],
    ['Write the message members will read...', 'Wandiika obubaka abakozesa bwe banaasoma...', 'Andika ujumbe ambao wanachama watasoma...', 'Écrivez le message que les membres liront...', 'Andika ubutumwa abanyamuryango bazasoma...', 'Handiika obutumwa abakozesa abu baraashome...'],

    # ── settings: the big form ──
    ['Settings', 'Entegeka', 'Mipangilio', 'Paramètres', 'Igenamiterere', 'Entebeekanisa'],
    ['App name', 'Erinnya lya pulogulaamu', 'Jina la programu', 'Nom de l\'application', 'Izina rya porogaramu', 'Eiziina rya porogaraamu'],
    ['Save app name', 'Tereka erinnya lya pulogulaamu', 'Hifadhi jina la programu', 'Enregistrer le nom', 'Bika izina rya porogaramu', 'Biika eiziina rya porogaraamu'],
    ['App tagline (shown under the logo)', 'Akabonero k\'ebigambo (kalagibwa wansi w\'akabonero)', 'Kauli mbiu (inaonyeshwa chini ya nembo)', 'Slogan (affiché sous le logo)', 'Interuro ngufi (igaragara munsi y\'ikirango)', 'Ebigambo by\'obwesigwa (nibyorekwa ahansi y\'ekimanyiso)'],
    ['Save tagline', 'Tereka akabonero k\'ebigambo', 'Hifadhi kauli mbiu', 'Enregistrer le slogan', 'Bika interuro ngufi', 'Biika ebigambo by\'obwesigwa'],
    ['Min deposit', 'Ssente entono ez\'okuteekamu', 'Amana ya chini', 'Dépôt minimum', 'Ubwishyu buto', 'Sente enkye ez\'okuteeramu'],
    ['Min withdrawal', 'Ssente entono ez\'okuggyamu', 'Utoaji wa chini', 'Retrait minimum', 'Kubikuza guto', 'Sente enkye ez\'okwihamu'],
    ['Withdrawal fee (%)', 'Ssente z\'obuweereza ku kuggyamu (%)', 'Ada ya utoaji (%)', 'Frais de retrait (%)', 'Amafaranga ya serivisi yo kubikuza (%)', 'Sente z\'obuheereza aha kwihamu (%)'],
    ['Withdrawal multiple', 'Ekigero ky\'okuggyamu', 'Kizidishi cha utoaji', 'Multiple de retrait', 'Igipimo cyo kubikuza', 'Ekigyero ky\'okwihamu'],
    ['Max withdrawals per user per day', 'Okuggyamu okusinga buli mukozesa buli lunaku', 'Utoaji mkubwa kwa mtumiaji kwa siku', 'Retraits max par utilisateur par jour', 'Kubikuza ntarengwa kuri buri mukoresha ku munsi', 'Okwihamu okurikukira aha buri mukozesa aha izooba'],
    ['L1 commission (%)', 'Ssente z\'omutendera 1 (%)', 'Kamisheni ya ngazi 1 (%)', 'Commission niveau 1 (%)', 'Komisiyo y\'urwego rwa 1 (%)', 'Sente z\'omurengo 1 (%)'],
    ['L2 commission (%)', 'Ssente z\'omutendera 2 (%)', 'Kamisheni ya ngazi 2 (%)', 'Commission niveau 2 (%)', 'Komisiyo y\'urwego rwa 2 (%)', 'Sente z\'omurengo 2 (%)'],
    ['L3 commission (%)', 'Ssente z\'omutendera 3 (%)', 'Kamisheni ya ngazi 3 (%)', 'Commission niveau 3 (%)', 'Komisiyo y\'urwego rwa 3 (%)', 'Sente z\'omurengo 3 (%)'],
    ['Check-in bonus', 'Empeera y\'okukyalira', 'Bonasi ya kuhudhuria', 'Bonus de pointage', 'Igihembo cyo kwiyandikisha', 'Empeera y\'okwoleka'],
    ['Welcome bonus', 'Empeera y\'okwanirizibwa', 'Bonasi ya karibu', 'Bonus de bienvenue', 'Igihembo cyo kwakira', 'Empeera y\'okwakiirwa'],
    ['Save rates', 'Tereka ebigero', 'Hifadhi viwango', 'Enregistrer les taux', 'Bika ibipimo', 'Biika ebigyero'],
    ['0 = no limit', '0 = tewali kkomo', '0 = hakuna kikomo', '0 = pas de limite', '0 = nta mupaka', '0 = tihariho mugyendo'],
    ['Cash-out opens at', 'Okuggyamu ssente kutandika ku', 'Utoaji unafunguka saa', 'Les retraits ouvrent à', 'Kubikuza gutangira saa', 'Okwihamu sente nikutandika aha'],
    ['Cash-out closes at', 'Okuggyamu ssente kuggalawo ku', 'Utoaji unafungwa saa', 'Les retraits ferment à', 'Kubikuza gufunga saa', 'Okwihamu sente nikwizibwa aha'],
    ['Only allow cash-out between set hours', 'Kkiriza okuggyamu ssente mu ssaawa eziteereddwawo zokka', 'Ruhusu utoaji ndani ya saa zilizowekwa tu', 'N\'autoriser les retraits qu\'aux heures définies', 'Kwemerera kubikuza gusa mu masaha yashyizweho', 'Ikiriza okwihamu sente omu shaaha ezitairweho zoonka'],
    ['Auto-approve withdrawals', 'Kkiriza okuggyamu ssente mu bwetwaze', 'Idhinisha utoaji kiotomatiki', 'Approuver automatiquement les retraits', 'Kwemeza kubikuza mu buryo bwikora', 'Ikiriza okwihamu sente kwonka'],
    ['Enable auto-approve', 'Sobozesa okukkiriza okw\'obwetwaze', 'Wezesha idhini otomatiki', 'Activer l\'approbation automatique', 'Gukoresha kwemeza kwikora', 'Kozesa okwikirizibwa kwonka'],
    ['Max amount to auto-approve', 'Omuwendo ogusinga ogw\'okukkiriza mu bwetwaze', 'Kiasi kikubwa cha kuidhinisha kiotomatiki', 'Montant max à approuver automatiquement', 'Umubare ntarengwa wo kwemeza mu buryo bwikora', 'Omubaro ogurikukira ogw\'okwikiriza kwonka'],
    ['Wait after request before approving (seconds)', 'Lindako oluvannyuma lw\'okusaba nga tonnakkiriza (obutundutundu)', 'Subiri baada ya ombi kabla ya kuidhinisha (sekunde)', 'Attendre après la demande avant d\'approuver (secondes)', 'Tegereza nyuma yo gusaba mbere yo kwemeza (amasegonda)', 'Tegyereza bwanyima y\'okushaba otakaikiriza (obucweka)'],
    ['Save auto-approve settings', 'Tereka entegeka y\'okukkiriza okw\'obwetwaze', 'Hifadhi mipangilio ya idhini otomatiki', 'Enregistrer les paramètres d\'approbation automatique', 'Bika igenamiterere ryo kwemeza kwikora', 'Biika entebeekanisa y\'okwikiriza kwonka'],
    ['Turntable (spin wheel)', 'Nnamuziga (eddiba erizunguluka)', 'Gurudumu (la kuzungusha)', 'Roue (tourner)', 'Uruziga (ruzunguruka)', 'Orupiira (orurikuzengurutsa)'],
    ['Daily free spin', 'Okuzungusa okwa buli lunaku okw\'obwereere', 'Mzungusho bure wa kila siku', 'Tour gratuit quotidien', 'Kuzunguza k\'ubuntu kwa buri munsi', 'Okuzengurutsa kwa buri izooba okwa busha'],
    ['Minimum win (UGX)', 'Okuwangula okusinga obutono (UGX)', 'Ushindi mdogo (UGX)', 'Gain minimum (UGX)', 'Gutsinda guto (UGX)', 'Okusingura okurikukira obukye (UGX)'],
    ['Maximum win (UGX)', 'Okuwangula okusinga obunene (UGX)', 'Ushindi mkubwa (UGX)', 'Gain maximum (UGX)', 'Gutsinda kunini (UGX)', 'Okusingura okurikukira obwingi (UGX)'],
    ['Spins earned by buying products', 'Okuzungusa okufunibwa mu kugula ebyamaguzi', 'Mizungusho inayopatikana kwa kununua bidhaa', 'Tours gagnés en achetant des produits', 'Kuzunguza kuboneka mu kugura ibicuruzwa', 'Okuzengurutsa okurikutungwa omu kugura ebyamaguzi'],
    ['Save turntable settings', 'Tereka entegeka ya nnamuziga', 'Hifadhi mipangilio ya gurudumu', 'Enregistrer les paramètres de la roue', 'Bika igenamiterere ry\'uruziga', 'Biika entebeekanisa y\'orupiira'],
    ['Maintenance mode', 'Embeera y\'okuddaabiriza', 'Hali ya matengenezo', 'Mode maintenance', 'Uburyo bwo gusana', 'Embeera y\'okugyerurura'],
    ['Maintenance message (shown to users)', 'Obubaka bw\'okuddaabiriza (bulagibwa abakozesa)', 'Ujumbe wa matengenezo (unaonyeshwa kwa watumiaji)', 'Message de maintenance (affiché aux utilisateurs)', 'Ubutumwa bwo gusana (bugaragarira abakoresha)', 'Obutumwa bw\'okugyerurura (nibworekwa abakozesa)'],
    ['Opening countdown', 'Okubala ennaku ez\'okuggulawo', 'Kuhesabu siku za kufunguliwa', 'Compte à rebours d\'ouverture', 'Kubara iminsi yo gufungura', 'Okubara ebiro by\'okwigurwa'],
    ['Opening date & time', 'Olunaku n\'essaawa ez\'okuggulawo', 'Tarehe na saa ya kufunguliwa', 'Date et heure d\'ouverture', 'Itariki n\'isaha byo gufungura', 'Ekiro n\'eshaaha by\'okwigurwa'],
    ['Require a referral code to sign up', 'Kyetaagisa koodi y\'okuyita okwewandiisa', 'Hitaji msimbo wa mwaliko ili kujisajili', 'Exiger un code de parrainage à l\'inscription', 'Gusaba kode yo gutumira mu kwiyandikisha', 'Kyetengyesa koodi y\'okweta kwehandiisa'],
    ['Require a plan before withdrawing', 'Kyetaagisa enteekateeka nga tonnaggyamu ssente', 'Hitaji mpango kabla ya kutoa pesa', 'Exiger un plan avant tout retrait', 'Gusaba gahunda mbere yo kubikuza', 'Kyetengyesa enteekateeka otakaihamu sente'],
    ['Payment provider', 'Ekitongole ekisasula', 'Mtoa huduma ya malipo', 'Fournisseur de paiement', 'Utanga serivisi yo kwishyura', 'Ekitongore ekirikushashura'],
    ['Enable PAY A', 'Sobozesa PAY A', 'Wezesha PAY A', 'Activer PAY A', 'Gukoresha PAY A', 'Kozesa PAY A'],
    ['Enable PAY B', 'Sobozesa PAY B', 'Wezesha PAY B', 'Activer PAY B', 'Gukoresha PAY B', 'Kozesa PAY B'],
    ['Save payment method', 'Tereka engeri y\'okusasula', 'Hifadhi njia ya malipo', 'Enregistrer le mode de paiement', 'Bika uburyo bwo kwishyura', 'Biika omuringo gw\'okushashura'],
    ['Payment numbers', 'Namba z\'okusasulirako', 'Namba za malipo', 'Numéros de paiement', 'Nomero zo kwishyuriraho', 'Namba z\'okushashuriraho'],
    ['+ Add payment number', '+ Yongerako namba y\'okusasulirako', '+ Ongeza namba ya malipo', '+ Ajouter un numéro de paiement', '+ Ongeraho nomero yo kwishyuriraho', '+ Yongyeraho namba y\'okushashuriraho'],
    ['Account holder name', 'Erinnya ly\'nannyini akawunti', 'Jina la mwenye akaunti', 'Nom du titulaire du compte', 'Izina rya nyir\'ukonti', 'Eiziina rya nyineeka akaunti'],
    ['MTN steps', 'Amatendera ga MTN', 'Hatua za MTN', 'Étapes MTN', 'Intambwe za MTN', 'Emitwarize ya MTN'],
    ['Airtel steps', 'Amatendera ga Airtel', 'Hatua za Airtel', 'Étapes Airtel', 'Intambwe za Airtel', 'Emitwarize ya Airtel'],
    ['e.g. Dial *185#, Select Send Money…', 'okugeza Kuba *185#, Londa Sindika Ssente…', 'mfano Piga *185#, Chagua Tuma Pesa…', 'ex. Composez *185#, Choisissez Envoyer de l\'argent…', 'urugero Hamagara *185#, Hitamo Kohereza amafaranga…', 'nk\'okugyera Teera *185#, Toorana Tuma Sente…'],
    ['Save payment reminder', 'Tereka ekijjukizo ky\'okusasula', 'Hifadhi kikumbusho cha malipo', 'Enregistrer le rappel de paiement', 'Bika urwibutso rwo kwishyura', 'Biika ekiijukyo ky\'okushashura'],
    ['Support contacts', 'Endagiriro z\'obuyambi', 'Mawasiliano ya usaidizi', 'Contacts d\'assistance', 'Aho wahamagara ubufasha', 'Endagiriro z\'obuhwezi'],
    ['Support hours', 'Essaawa z\'obuyambi', 'Saa za usaidizi', 'Heures d\'assistance', 'Amasaha y\'ubufasha', 'Eshaaha z\'obuhwezi'],
    ['Every day, 8am – 9pm', 'Buli lunaku, ku ssaawa 2 ez\'oku makya okutuuka ku 3 ez\'ekiro', 'Kila siku, saa 2 asubuhi – saa 3 usiku', 'Tous les jours, 8h – 21h', 'Buri munsi, saa 2 za mu gitondo – saa 3 z\'ijoro', 'Buri izooba, shaaha 2 ez\'omu kasheeshe – shaaha 3 ez\'ekiro'],
    ['Telegram channel', 'Omukutu gwa Telegram', 'Chaneli ya Telegram', 'Canal Telegram', 'Umuyoboro wa Telegram', 'Omuyanja gwa Telegram'],
    ['Telegram group', 'Ekibiina kya Telegram', 'Kikundi cha Telegram', 'Groupe Telegram', 'Itsinda rya Telegram', 'Ekibiina kya Telegram'],
    ['WhatsApp contact', 'Endagiriro ya WhatsApp', 'Mawasiliano ya WhatsApp', 'Contact WhatsApp', 'Aho wahamagara kuri WhatsApp', 'Endagiriro ya WhatsApp'],
    ['WhatsApp group', 'Ekibiina kya WhatsApp', 'Kikundi cha WhatsApp', 'Groupe WhatsApp', 'Itsinda rya WhatsApp', 'Ekibiina kya WhatsApp'],
    ['Save support contacts', 'Tereka endagiriro z\'obuyambi', 'Hifadhi mawasiliano ya usaidizi', 'Enregistrer les contacts d\'assistance', 'Bika aho wahamagara ubufasha', 'Biika endagiriro z\'obuhwezi'],
    ['Regulation page', 'Olupapula lw\'amateeka', 'Ukurasa wa kanuni', 'Page du règlement', 'Urupapuro rw\'amabwiriza', 'Orupapura rw\'ebiragiro'],
    ['Platform rules and regulation…', 'Amateeka n\'ebiragiro bya pulatifoomu…', 'Sheria na kanuni za jukwaa…', 'Règles et règlement de la plateforme…', 'Amategeko n\'amabwiriza by\'urubuga…', 'Ebiragiro n\'ebiteekateeko by\'orubuga…'],
    ['Save regulation', 'Tereka amateeka', 'Hifadhi kanuni', 'Enregistrer le règlement', 'Bika amabwiriza', 'Biika ebiragiro'],
    ['Save about page', 'Tereka olupapula "Ku ffe"', 'Hifadhi ukurasa wa kuhusu', 'Enregistrer la page À propos', 'Bika urupapuro rwa "Abo turi bo"', 'Biika orupapura "Ahaitwe"'],
    ['+ Add text block', '+ Yongerako ekitundu ky\'ebiwandiike', '+ Ongeza kizuizi cha maandishi', '+ Ajouter un bloc de texte', '+ Ongeraho igice cy\'inyandiko', '+ Yongyeraho ekicweka ky\'ebihandiike'],
    ['+ Add image block', '+ Yongerako ekitundu ky\'ekifaananyi', '+ Ongeza kizuizi cha picha', '+ Ajouter un bloc image', '+ Ongeraho igice cy\'ifoto', '+ Yongyeraho ekicweka ky\'ekishushani'],
    ['Write a paragraph…', 'Wandiika akatundu…', 'Andika aya…', 'Rédigez un paragraphe…', 'Andika igika…', 'Handiika akacweka…'],
    ['Push notifications', 'Obubaka obuweerezebwa', 'Arifa za papo hapo', 'Notifications push', 'Ubutumwa buhita bugera', 'Obutumwa oburikutumwa'],
    ['Enable push notifications', 'Sobozesa obubaka obuweerezebwa', 'Wezesha arifa za papo hapo', 'Activer les notifications push', 'Gukoresha ubutumwa buhita bugera', 'Kozesa obutumwa oburikutumwa'],
    ['Reset all devices', 'Zzaayo ebyuma byonna', 'Weka upya vifaa vyote', 'Réinitialiser tous les appareils', 'Gusubiza ibikoresho byose', 'Garuza ebyoma byona'],
    ['Home activity ticker speed (px/second)', 'Sipiidi y\'olukalala lw\'ebikolwa ku lupapula olusooka (px/obutundutundu)', 'Kasi ya mkanda wa shughuli za ukurasa wa nyumbani (px/sekunde)', 'Vitesse du bandeau d\'activité de l\'accueil (px/seconde)', 'Umuvuduko w\'umurongo w\'ibikorwa ku rupapuro rw\'ahabanza (px/isegonda)', 'Obwiru bw\'orukoora rw\'ebikorwa aha rupapura rw\'omuka (px/akacweka)'],
]
