#!/usr/bin/env node
'use strict';
// Rename the app everywhere in one go.
//
//   node set-brand.js "New Name"          rewrite the source files, then rebuild
//   node set-brand.js "New Name" --dry    only list what would change
//
// The name members SEE is also an admin setting (Settings -> App name) that
// takes effect live; this tool is for the parts baked into files: page titles,
// install names, cache names, storage keys, identifiers. A phone that already
// installed the app keeps its old home-screen name until reinstalled.
//
// How it works: the current name/slug come from brand.config.json. Three
// spellings are replaced in the source files (not in built output, which is
// regenerated by the build scripts): the display name ("Soda"), the lowercase
// slug ("soda") and the upper-case form ("SODA"). Hosts are never touched.
const fs = require('fs'), path = require('path'), cp = require('child_process');
const root = __dirname;
const cfgPath = path.join(root, 'brand.config.json');
const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
const args = process.argv.slice(2);
const dry = args.includes('--dry');
const next = (args.find(a => !a.startsWith('--')) || '').trim();
if (!next) { console.error('Usage: node set-brand.js "New Name" [--dry]'); process.exit(1); }
if (!/^[A-Za-z][A-Za-z0-9 ]{1,23}$/.test(next)) { console.error('Name must be 2-24 characters: letters, digits and spaces, starting with a letter.'); process.exit(1); }
const nextSlug = next.toLowerCase().replace(/[^a-z0-9]/g, '');
if (nextSlug.length < 2) { console.error('Name needs at least two letters or digits.'); process.exit(1); }
if (next === cfg.name) { console.log('Already named', next); process.exit(0); }

// Rewrites the readable sources only; built bundles are regenerated below.
const SKIP = new Set(['CLAUDE.md', 'user/index.html', 'user/share.html', 'admin/index.html', 'package-lock.json', 'brand.config.json', 'set-brand.js']);
const EXT = /\.(js|html|json|sh|template|yaml|yml)$/;
const files = cp.execSync('git ls-files', { cwd: root, encoding: 'utf8' }).split('\n')
  .filter(f => f && !SKIP.has(f) && EXT.test(f) && !f.startsWith('docs/') && !f.includes('node_modules'));
// Keep whole words from being mangled: a slug that is a substring of another
// word would be replaced inside it, so refuse names whose slug collides.
if (nextSlug !== cfg.slug && files.some(f => fs.readFileSync(path.join(root, f), 'utf8').includes(nextSlug) && !fs.readFileSync(path.join(root, f), 'utf8').includes(cfg.slug)))
  console.warn('Note: "' + nextSlug + '" already appears in some files; review the diff before committing.');
// "Fizz Drinks" is fine as visible text but cannot go inside a code identifier
// (getSodaImage -> getFizz DrinksImage would not even parse). So the display
// name is replaced as a whole word with the spaced form, and wherever it is
// stuck to other characters (an identifier) with a spaceless PascalCase form.
const pascal = next.split(/\s+/).map(w => w[0].toUpperCase() + w.slice(1)).join('');
const esc = x => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const WHOLE = new RegExp('(?<![A-Za-z0-9_])' + esc(cfg.name) + '(?![A-Za-z0-9_])', 'g');
let changed = 0;
for (const f of files) {
  const p = path.join(root, f); let s = fs.readFileSync(p, 'utf8'), o = s;
  s = s.replace(WHOLE, '\u0000NAME\u0000').split(cfg.name).join(pascal).split('\u0000NAME\u0000').join(next);
  s = s.split(cfg.slug).join(nextSlug).split(cfg.slug.toUpperCase()).join(nextSlug.toUpperCase());
  if (s !== o) { changed++; console.log((dry ? 'would change ' : 'changed ') + f); if (!dry) fs.writeFileSync(p, s); }
}
if (!dry) {
  const lock = path.join(root, 'package-lock.json'); let l = fs.readFileSync(lock, 'utf8');
  fs.writeFileSync(lock, l.split('"' + cfg.slug + '-server"').join('"' + nextSlug + '-server"'));
  for (const [oldF, newF] of [['deploy/nginx-' + cfg.slug + '.conf.template', 'deploy/nginx-' + nextSlug + '.conf.template']])
    if (fs.existsSync(path.join(root, oldF)) && oldF !== newF) fs.renameSync(path.join(root, oldF), path.join(root, newF));
  fs.writeFileSync(cfgPath, JSON.stringify({ name: next, slug: nextSlug }, null, 2) + '\n');
}
console.log(`\n${dry ? 'Dry run: ' : ''}${changed} file(s) ${dry ? 'would change' : 'changed'}. ` +
  (dry ? '' : 'Now run: node build-core.js && node build-admin.js, bump user/sw.js and admin/sw.js cache versions, then deploy.'));
