'use strict';
// Start-up loader: admin-uploaded background + a bouncing "Loading . . ." (no letter animations);
// secondary pages end above the bottom navigation so their last card can be scrolled into view.
const fs = require('node:fs'), assert = require('node:assert/strict');
const built = process.argv.includes('--built');
const html = fs.readFileSync(__dirname + (built ? '/user/index.html' : '/user-src/index.html'), 'utf8');
const server = fs.readFileSync(__dirname + '/server.js', 'utf8');
const admin = fs.readFileSync(__dirname + '/admin-src/index.html', 'utf8');
let n = 0; const ok = (c, m) => { n++; assert.ok(c, m); };
ok(/<span class="ld-txt"[^>]*>Loading\.\.\.<\/span>/.test(html), 'the loader says "Loading..."');
ok(/#loadingScreen \.ld-bg\{[^}]*url\('\/api\/public\/loader-image'\)[^}]*opacity:var\(--ld-op,1\)[^}]*filter:blur\(var\(--ld-blur,0px\)\)/.test(html) && /id="ldBg"/.test(html), 'the loader background is the admin picture, on its own layer with the admin opacity and blur (never on the word)');
ok(/@keyframes ldBounce\{.*translateY\(-34px\)/.test(html) && /animation:ldBounce/.test(html), 'the word bounces in its original 34 px area');
ok((html.match(/ld-txt[^{]*\{[^}]*animation:/g) || []).length === 2, 'one bounce animation (plus its reduced-motion off switch), nothing else');
ok(/ld-txt\{[^}]*font-family:'Noto Serif'[^}]*font-size:24px[^}]*letter-spacing:\.02em/.test(html), 'bold serif, 24 px, letters and dots close together');
ok(/ld-txt\{[^}]*color:#fff/.test(html), 'colour stays white (not specified by the owner)');
ok(/\.sr-only\{/.test(html), 'the screen-reader word is hidden');
ok(/body\.sheet-open \.sheet-bg\{bottom:var\(--nav-h\);\}/.test(html), 'secondary pages end above the bottom navigation');
ok(/'profilelogo', 'loaderbg'\]/.test(server) && /app\.get\('\/public\/loader-image'/.test(server), 'server stores and serves the loader picture');
ok(/id="loaderBgFile"/.test(admin) && /wireSodaImageSlot\('loaderbg'/.test(admin), 'admin can upload and remove it');
const mod = fs.readFileSync(__dirname + '/user-src/original_module.js', 'utf8');
ok(!/type="password"/.test(html + mod), 'no masked password field anywhere: what a member types stays visible');
ok(!/toggleWitPin|toggleStyle|aria-label="Show password"/.test(html + mod), 'no show/hide eye');
ok(!/walOtpGroup|confirmWalletOtp|bankOtpRequired/.test(mod), 'saving a wallet has no OTP step');
ok(!/id="sOtpVerification"|id="sBankOtp"|id="sAnnEnabled"|id="sReturnMult"/.test(admin), 'admin no longer shows the OTP, announcement-switch and return-multiple settings');
ok(/setTimeout\(startArtwork, 8000\)/.test(mod) && !/_artPromise = Promise\.all\(\[ api\('\/public\/announcement-image'\), api\('\/public\/soda-images'\) \]\)\n/.test(mod.split('async function boot()')[1].split('async function')[0]), 'pictures are fetched after the loading screen, not beside the account request');
ok(/const s = await pSettings;/.test(mod) && !/Promise\.all\(\[ pSettings, pProducts, pBanner \]\)/.test(mod), 'the loading screen waits for the settings only, not for the asset pictures or the banner');
ok(!/fileToLogoPng|background connected to the image edge/.test(admin) && /wireSodaImageSlot\('logo', 'brandLogoFile'/.test(admin), 'the brand logo is uploaded as it is (no background removal)');
ok(/var NAV_LOADER = '<span class="nav-loading">Loading\.\.\.<\/span>'/.test(mod) && /\.nav-loading\{[^}]*font-size:15px[^}]*letter-spacing:\.03em/.test(html) && !/MINI_RING_LOADER|mini-ring-loader|ringSweep/.test(html + mod), 'pages show a small "Loading..." word while data arrives, no ring spinner is left');
ok((mod.match(/NAV_LOADER/g) || []).length >= 6, 'Income, Team, Team members, Balance Record and Messages all use it');
ok(/showAuthTab\('login'\);\n  stopLiveRefresh\(\);/.test(mod), 'signing out always lands on Login, not on a Sign Up form left open');
ok(/\.v-ann-img\{[^}]*object-fit:contain[^}]*\}/.test(html) && !/\.v-ann-img\{[^}]*object-fit:cover/.test(html), 'the announcement picture is shown whole (contain), never cropped');
ok(/function vFitCard\(img\)/.test(mod) && /onload="vFitCard\(this\)"/.test(mod) && /\.v-card-img\.has-img img\{[^}]*height:auto/.test(html) && !/\.v-card-img\.has-img img\{[^}]*object-fit:cover/.test(html), 'asset pictures are shown whole in their own shape (portrait in the column, wide or square across the top)');
ok(!/fileToFramedDataUrl|PRODUCT_IMG_W/.test(admin) && /fileToDataUrl\(f,900,0\.82\)/.test(admin), 'the admin no longer crops asset pictures to 16:9');
ok(/--img-w/.test(mod) && /grid-template-columns:var\(--img-w,112\.5px\) 1fr/.test(html), 'a portrait picture gets a column of its own shape (a 2:3 photo is 133 px wide at the 200 px card height)');
ok(/<script data-soda-loader>/.test(html) && /localStorage\.getItem\(KEY\)/.test(html) && /bg\.style\.backgroundImage = layer\(kept\)/.test(html) && /window\._sodaLoaderStart = Date\.now\(\)/.test(html), 'the kept loading picture is painted inline on the first frame, before any network request');
ok(/fetch\('\/api\/public\/loader-image', \{ cache: 'no-cache' \}\)/.test(html) && /localStorage\.setItem\(KEY, u\)/.test(html), 'and refreshed in the background for the next visit');
ok(/var LOADER_MIN_MS = 2500/.test(mod) && /function hideLoadingScreen\(\)/.test(mod) && !/\$\('loadingScreen'\)\.style\.display = 'none'/.test(mod), 'the loading screen stays for 2.5 seconds before the page opens, through one function');
ok(/var PAY_OK_SVG = '<svg viewBox="0 0 696 696" class="draw-ok"/.test(mod) && /var PAY_FAIL_SVG = '<svg viewBox="0 0 313 313" class="draw-fail"/.test(mod) && /innerHTML = PAY_OK_SVG/.test(mod) && /innerHTML = PAY_FAIL_SVG/.test(mod), 'deposit success and failed use the traced green tick and red cross');
ok(/var DEPOSIT_POLL_FLOW = /.test(mod) && /innerHTML = DEPOSIT_POLL_FLOW/.test(mod) && !/dep-poll|pspin|DEPOSIT_POLL_SPIN|depPollRotate/.test(html + mod), 'the payment wait is the phone-to-wallet dots; the rotating rings and orbiting chips are gone');
ok(!/Congratulations! \u{1F389}|🎉/u.test(mod), 'no emoji in the success title');
ok(/loaderBgOpacity: \[0, 100\], loaderBgBlur: \[0, 40\]/.test(server) && /'X-Loader-Opacity'/.test(server) && /'X-Loader-Blur'/.test(server), 'the server limits the loader opacity 0-100 and blur 0-40 and sends them with the picture');
ok(/id="loaderBgOp"/.test(admin) && /id="loaderBgBlur"/.test(admin) && /id="saveLoaderBg"/.test(admin) && /loaderBgOpacity:\+\$\('loaderBgOp'\)\.value/.test(admin), 'admin can edit the loader picture opacity and blur');
ok(/localStorage\.setItem\(FX/.test(html) && /r\.headers\.get\('X-Loader-Opacity'\)/.test(html) && /function applyLoaderFx\(\)/.test(mod), 'the values are remembered for the first frame and follow the settings');
ok(/#loadingScreen \.ld-txt\{position:relative;z-index:1;/.test(html), 'the word stays above the picture layer');
ok(/window\._sodaAuthFired = true;\s*window\.dispatchEvent\(new CustomEvent\('snow-auth'/.test(html), 'the sign-in script records that it has announced who is signed in');
ok(/window\.addEventListener\('snow-auth', ev => onMemberAuth\(ev\.detail\)\);[\s\S]{0,700}if \(window\._sodaAuthFired && window\.fbAuth\) onMemberAuth\(window\.fbAuth\.currentUser\);/.test(mod), 'and the app picks that announcement up itself when its own code unpacks later (otherwise the loading screen stays for ever)');
ok(/function waitForBootSettings\(ms\)/.test(mod) && !/withTimeout\(_bootPromise, 6000\)/.test(mod), 'the settings are waited for once in total (6 s from page start), not once per start-up step');
ok(!/fireConfetti|confettiCanvas/.test(mod + html), 'no confetti or sparkles anywhere: success is the tick drawing itself');
ok(/@keyframes drDraw/.test(html) && /\.draw-ok \.dm-tick\{animation:drDraw/.test(html) && /\.draw-fail \.dm-x2\{animation:drDraw/.test(html), 'the owner\'s green tick and red cross (deposit result page) draw themselves: ring, disc, then the mark');
ok(/#42af3c/.test(mod) && /M316\.5 694\.5C292\.9 692\.3/.test(mod) && /<rect x="81\.5" y="141\.5" width="150" height="30" rx="7" transform="rotate\(45 156\.5 156\.5\)"/.test(mod), 'and the artwork itself is the owner\'s traced tick and cross, untouched (masks only reveal it)');
ok(!/\.notify-ic svg (circle|path)\{[^}]*animation/.test(html), 'the notice cards keep their plain icons (only the deposit result tick and cross animate)');
ok(/prefers-reduced-motion:reduce\)\{\s*\.draw-ok \.dm-ring/.test(html), 'with reduced motion they appear already drawn');
console.log(`PASS: loader and page bottom (${n} checks${built ? ', built bundle' : ''})`);
