'use strict';
// Start-up loader: admin-uploaded background + a bouncing "Loading . . ." (no letter animations);
// secondary pages end above the bottom navigation so their last card can be scrolled into view.
const fs = require('node:fs'), assert = require('node:assert/strict');
const built = process.argv.includes('--built');
const html = fs.readFileSync(__dirname + (built ? '/user/index.html' : '/user-src/index.html'), 'utf8');
const server = fs.readFileSync(__dirname + '/server.js', 'utf8');
const admin = fs.readFileSync(__dirname + '/admin-src/index.html', 'utf8');
let n = 0; const ok = (c, m) => { n++; assert.ok(c, m); };
ok(/<span class="ld-txt"[^>]*>Loading \. \. \.<\/span>/.test(html), 'the loader says "Loading . . ."');
ok(/#loadingScreen\{[^}]*url\('\/api\/public\/loader-image'\)/.test(html), 'the loader background is the admin picture');
ok(/@keyframes ldBounce\{.*translateY\(-34px\)/.test(html) && /animation:ldBounce/.test(html), 'the word bounces in a small area');
ok((html.match(/ld-txt[^{]*\{[^}]*animation:/g) || []).length === 2, 'one bounce animation (plus its reduced-motion off switch), nothing else');
ok(/ld-txt\{[^}]*font-family:'Noto Serif'[^}]*font-size:36px[^}]*letter-spacing:\.16em/.test(html), 'bold serif, 36 px, wide spacing (the owner\'s sample)');
ok(/ld-txt\{[^}]*color:#fff/.test(html), 'colour stays white (not specified by the owner)');
ok(/\.sr-only\{/.test(html), 'the screen-reader word is hidden');
ok(/body\.sheet-open \.sheet-bg\{bottom:var\(--nav-h\);\}/.test(html), 'secondary pages end above the bottom navigation');
ok(/'profilelogo', 'loaderbg'\]/.test(server) && /app\.get\('\/public\/loader-image'/.test(server), 'server stores and serves the loader picture');
ok(/id="loaderBgFile"/.test(admin) && /wireSodaImageSlot\('loaderbg'/.test(admin), 'admin can upload and remove it');
const mod = fs.readFileSync(__dirname + '/user-src/original_module.js', 'utf8');
ok(!/type="password"/.test(html + mod), 'no masked password field anywhere: what a member types stays visible');
ok(!/toggleWitPin|toggleStyle|aria-label="Show password"/.test(html + mod), 'no show/hide eye');
ok(!/walOtpGroup|confirmWalletOtp|bankOtpRequired/.test(mod), 'saving a wallet has no OTP step');
ok(!/id="sOtpVerification"|id="sBankOtp"|id="sAnnEnabled"|id="sReturnMult"/.test(admin), 'admin no longer shows the OTP, announcement-switch and return-multiple settings');
ok(/setTimeout\(startArtwork, 8000\)/.test(mod) && !/_artPromise = Promise\.all\(\[ api\('\/public\/announcement-image'\), api\('\/public\/soda-images'\) \]\)\n/.test(mod.split('async function boot()')[1].split('async function')[0]), 'pictures are fetched after the loading screen, not beside the account request');
ok(/const s = await pSettings;/.test(mod) && !/Promise\.all\(\[ pSettings, pProducts, pBanner \]\)/.test(mod), 'the loading screen waits for the settings only, not for the asset pictures or the banner');
ok(!/fileToLogoPng|background connected to the image edge/.test(admin) && /wireSodaImageSlot\('logo', 'brandLogoFile'/.test(admin), 'the brand logo is uploaded as it is (no background removal)');
ok(/var NAV_LOADER = '<span class="nav-loading">Loading \. \. \.<\/span>'/.test(mod) && !/MINI_RING_LOADER|mini-ring-loader|ringSweep/.test(html + mod), 'pages show the same "Loading . . ." word while data arrives, no ring spinner is left');
ok((mod.match(/NAV_LOADER/g) || []).length >= 6, 'Income, Team, Team members, Balance Record and Messages all use it');
console.log(`PASS: loader and page bottom (${n} checks${built ? ', built bundle' : ''})`);
