/* SPACE8 ASSISTANT — TRAINING CORPUS
   Real member phrasings mapped to the intent that must answer them.

   This is the assistant's training data AND its regression suite. Every
   utterance here is asserted by test-assistant-corpus.js to route to the
   intent that owns it. That guard is what makes growing the intent set safe:
   keyword/phrase collisions between intents grow roughly with the SQUARE of
   the intent count, and they are silent -- a colliding intent does not throw,
   it just quietly answers the wrong question. Four such collisions were found
   by hand at 100 intents (including "how do I delete my account" answering
   with withdrawal-account instructions). Beyond that scale, hand-checking
   stops being viable, so it is done here mechanically instead.

   Adding an intent WITHOUT adding its utterances here is how the assistant
   silently regresses. Add both together.

   Deliberately included: misspellings, missing punctuation, lowercase,
   Ugandan-English phrasings, terse fragments -- because that is what members
   actually type, and the engine's typo/fuzzy handling needs to be held to it.  */

module.exports = {
  security_secret: ["what is my pin", "whats my pin", "tell me my pin", "show me my password", "can you see my pin", "what is my password"],
  greeting: ["hi", "hello", "hey", "hi there", "hello there", "good morning", "good afternoon", "good evening", "yo", "hey there", "hallo", "howdy", "hey bro", "hi bro", "hello sir", "good day", "hi space8", "morning", "evening"],
  howareyou: ["how are you", "how are you doing", "hows it going", "how is it going", "wassup"],
  thanks: ["thanks", "thank you", "thanks a lot", "much appreciated", "i appreciate it", "thank you so much", "thanks bro", "ok thanks", "thank u", "tnx", "appreciate it"],
  bye: ["bye", "goodbye", "cya", "see you later", "bye bye", "ok bye", "later", "goodnight", "talk later"],
  whoami: ["who are you", "what are you", "are you a robot", "are you human", "are you a bot", "are you ai", "are you real", "what are you exactly", "is this a human", "are you a machine"],
  capability: ["what can you do", "what can you help with", "what do you know", "help me with something", "what else can you do", "how can you help me", "what questions can i ask", "what are you for"],
  deposit: ["how do i deposit", "how to deposit money", "i want to deposit", "how do i add funds", "how to top up", "how do i recharge my wallet", "add money to wallet", "how do i fund my account", "depost money", "how do i put money in", "deposit process", "i want to add money", "how to load my wallet", "how can i deposit", "teach me how to deposit", "deposit steps", "how do i pay in", "i need to deposit"],
  withdraw: ["how do i withdraw", "how to withdraw money", "i want to cash out", "how do i cashout", "how to take my money out", "withdraw funds", "how do i get my money", "withdrawl process", "how to withraw", "withdraw process", "how can i withdraw", "teach me how to withdraw", "i need to withdraw", "how do i cash out my money", "steps to withdraw", "withdraw my balance"],
  withdraw_timing: ["how long does a withdrawal take", "when will i get my money", "when do i receive my withdrawal", "how long until i get paid out", "withdrawal time", "how soon will i be paid", "how many hours for withdrawal", "when does withdrawal arrive", "time taken to withdraw"],
  fees: ["what are the fees", "what is the fee", "how much do you charge", "what charges apply", "is there a cost", "any charges", "what fees do you take", "tell me about charges", "how much is the charge"],
  why_fee: ["why is there a fee", "why do you charge a fee", "why do you deduct from my withdrawal", "why charge on withdrawals", "why do i pay a fee", "reason for the fee", "why the deduction"],
  invest: ["how do i invest", "i want to invest", "how do investments work", "tell me about the plans", "what products do you have", "how do i buy a plan", "show me the plans", "invesment options", "how to buy a product", "how do i start investing", "investment process", "i want to buy a satellite", "how to purchase a plan", "teach me to invest"],
  maturity: ["what happens when my plan matures", "when do i get paid", "when does my plan finish", "what happens when my investment ends", "when does it mature", "what is maturity", "when is my payout", "end of cycle what happens"],
  multi_invest: ["can i buy more than one plan", "can i invest in multiple plans", "how many plans can i have", "can i hold several investments", "can i own two plans", "more than one investment", "several plans at once"],
  cancel: ["can i cancel my investment", "can i get a refund", "i want to undo my purchase", "i changed my mind about the plan", "i want a refund", "cancel my plan", "can i take my money back from a plan"],
  referral: ["how do referrals work", "tell me about commission", "how do i invite people", "what is the referral program", "how do i earn from my team", "refferal info", "downline commission", "how to refer people", "referral system", "invite friends", "commission structure", "how do i grow my team"],
  milestone: ["what is task center", "tell me about missions", "what are milestones", "referral milestone rewards", "explain missions", "what are the tasks", "mission rewards"],
  checkin: ["what is check in", "tell me about daily bonus", "how does the streak work", "daily reward", "daily check in", "how do i check in", "checkin bonus info", "what is the daily reward"],
  pin: ["what is the pin for", "tell me about the withdrawal pin", "why do i need a pin", "what is the security pin", "about the pin", "why pin is needed", "purpose of the pin"],
  balance: ["what is my balance", "how much do i have", "show my wallet", "how much have i earned", "what is my wallet balance", "how much have i invested", "my balance please", "check my balance", "what do i have in my wallet", "current balance"],
  banned: ["why is my account banned", "my account is suspended", "why am i blocked", "account locked", "am i banned", "why is my account restricted", "account disabled"],
  support: ["how do i contact support", "i need help from someone", "customer care", "i have a complaint", "contact customer service", "i need support", "help me please", "who do i talk to", "support contact"],
  giftcode: ["what is a gift code", "how do i redeem a code", "where do i enter a promo code", "i have a voucher", "gift code", "redeem code", "promo code", "i have a gift code"],
  security_general: ["is my account secure", "how secure is this", "do you use encryption", "is there two factor", "is this platform secure", "account security", "how do you protect my account"],
  about: ["what is space8", "tell me about space8", "is space8 legit", "is this safe", "is this a scam", "can i trust this platform", "what is this app", "tell me about this platform", "is this genuine", "is this real"],
  deposit_pending: ["my deposit is pending", "deposit is stuck", "my deposit is not showing", "i paid but nothing happened", "money deducted but no deposit", "deposit failed", "deposit still pending", "my money was deducted", "paid but wallet not updated", "deposit not credited"],
  withdraw_pending: ["my withdrawal is pending", "withdrawal is stuck", "my cashout is still processing", "withdrawal not received yet", "withdrawal still pending", "cash out pending", "my withdrawal is sending"],
  commission_missing: ["my commission is missing", "i did not get my referral commission", "commission not paid", "referral bonus not credited", "my commission is zero", "no commission received", "commission did not come", "referral money missing"],
  investment_missing: ["my investment is missing", "my plan is not showing", "my plan disappeared", "money deducted but no plan", "plan not appearing", "i bought but no plan", "purchase not showing"],
  payout_account: ["how do i bind a payout account", "how do i add a withdrawal account", "change my withdrawal account", "remove a payout account", "withdrawal account setup", "bind my number", "save my mobile money number", "add payout number", "register withdrawal number"],
  password: ["i forgot my password", "cant login", "can't sign in", "login problem", "password issue", "i cannot log in", "login failed", "wrong password"],
  history: ["where is my transaction history", "how do i see my records", "where are my receipts", "show my transactions", "my records", "transaction records", "see my history", "where is records"],
  notifications: ["what are notifications", "tell me about alerts", "the bell icon", "push notifications", "notification settings", "why no alerts"],
  maintenance: ["is the site under maintenance", "is the app offline", "why is it unavailable", "downtime", "are you under maintenance", "system maintenance", "is the platform down"],
  rules: ["what are the rules", "show me the terms", "platform policy", "rules and regulations", "terms and conditions", "platform rules", "where are the terms"],
  announcement: ["is there an announcement", "any news", "any updates", "latest announcement", "platform news", "any notice"],
  network_error: ["network error", "connection failed", "server error", "something went wrong", "the network is down", "server unavailable", "connection problem", "it says network error", "cannot connect"],
  mobile_networks: ["do you support mtn", "is airtel supported", "which mobile money networks", "mtn or airtel", "is mtn supported", "airtel money", "what networks do you accept"],
  welcome_bonus: ["what is the welcome bonus", "registration bonus", "signup reward", "do i get a joining gift", "joining bonus", "new user bonus", "do i get free money when i join"],
  referral_not_applied: ["my referral code didnt apply", "i forgot to enter the referral code", "can i add a referral code later", "referral code did not work", "i did not use a referral code", "code not applied at signup", "add invite code now"],
  phone_change: ["how do i change my phone number", "my registered phone is wrong", "i registered with the wrong number", "update my phone", "wrong phone number on account", "correct my number", "change registered number"],
  howworks: ["how does space8 work", "how does the platform work", "explain space8", "how does this work", "explain how it works", "how does this platform operate", "how do i make money here"],
  install_app: ["how do i install the app", "can i download the app", "add to home screen", "is there an app", "get the app", "download app", "install space8", "apk", "play store"],
  cumulative_earnings: ["what is cumulative earnings", "how are cumulative earnings counted", "how is total earnings calculated", "cumulative earning meaning", "total earnings meaning", "what counts as earnings", "earnings explained"],
  account_id: ["what is my account id", "where is my user id", "what is my member id", "whats my id", "my id number", "account number", "where is my id"],
  telegram_community: ["do you have a telegram group", "telegram channel", "how do i join the community", "join telegram", "telegram link", "whatsapp group", "community group", "social media"],
  giftcode_case: ["my gift code is not working", "the promo code is invalid", "code not working", "gift code failed", "code says invalid", "gift code rejected", "promo code error"],
  multi_withdrawal_accounts: ["can i have more than one withdrawal account", "add a second payout account", "multiple withdrawal accounts", "two payout numbers", "several withdrawal numbers", "another mobile money account"],
  checkin_streak_reset: ["my streak reset", "i missed a day of checkin", "streak broken", "i lost my streak", "streak went to zero", "lost my checkin streak", "why did my streak reset"],
  min_deposit_specific: ["what is the minimum deposit", "least i can deposit", "lowest deposit amount", "minimum amount to deposit", "smallest deposit", "min deposit"],
  min_withdraw_specific: ["what is the minimum withdrawal", "least i can withdraw", "lowest withdrawal amount", "minimum amount to withdraw", "smallest withdrawal", "min withdrawal"],
  max_withdraw_limit: ["what is the maximum withdrawal", "is there a withdrawal limit", "how many withdrawals per day", "daily withdrawal limit", "how much can i withdraw per day", "withdrawal cap"],
  multiple_deposits_per_day: ["can i deposit more than once", "can i deposit twice in a day", "multiple deposits", "deposit again today", "two deposits same day"],
  deposit_confirmation: ["how do i know my deposit worked", "did my deposit go through", "how to confirm payment succeeded", "was my deposit successful", "check if deposit worked"],
  wrong_network_deposit: ["i selected the wrong network", "i chose the wrong network for my deposit", "wrong network on deposit", "picked wrong network", "network mismatch on deposit"],
  plan_comparison: ["which plan is best", "compare the plans", "what plan do you recommend", "which plan should i buy", "best plan to buy", "which one is better", "recommend a plan"],
  cheapest_plan: ["what is the cheapest plan", "smallest plan", "lowest plan", "least expensive plan", "minimum plan price", "cheapest product"],
  priciest_plan: ["what is the biggest plan", "most expensive plan", "largest plan", "highest plan", "highest priced plan", "top plan", "biggest investment"],
  daily_income_explain: ["what is daily income", "how does daily cashback work", "how is daily income calculated", "explain daily payout", "how is daily calculated", "daily cashback meaning"],
  total_return_explain: ["what is total return", "what do i get back", "total payout meaning", "how much will i get in total", "total profit explained"],
  cycle_explain: ["what is a cycle", "what does cycle mean", "what is the cycle", "how long is a cycle", "cycle duration", "what is the plan period"],
  compounding: ["does it compound", "does my profit reinvest itself", "is cashback compounded automatically", "is it compounded", "does interest compound"],
  reinvest_earnings: ["can i reinvest", "can i reinvest my earnings", "use my cashback to buy another plan", "invest my profits again", "buy another plan with earnings"],
  plan_upgrade: ["can i upgrade my plan", "can i switch plans", "change my investment plan", "move to a bigger plan", "upgrade investment"],
  after_maturity: ["what happens after my plan matures", "does my plan auto renew", "what after maturity", "after the cycle ends", "does it renew automatically", "plan finished what next"],
  how_share_referral: ["how do i share my referral link", "how do i share my referral", "share invite link", "send my referral link", "copy referral link", "how to invite"],
  referral_levels_explain: ["what are level 1 2 3", "what does level 2 mean", "explain the levels", "level one two three", "what is level 3", "levels meaning"],
  self_referral: ["can i refer myself", "can i use my own referral code", "refer myself", "use my own code", "refer my own account"],
  referral_code_lookup: ["what is my referral code", "where is my referral code", "whats my invite code", "my invite code", "find my referral code", "referral code please"],
  team_size_view: ["how do i see my team", "how many people have i referred", "where is my team list", "my team members", "see my downline", "team list"],
  task_center_claim_how: ["how do i claim a mission", "how to claim my task reward", "claim milestone reward", "claim my reward", "how to claim task", "claim mission"],
  task_center_types: ["what types of missions are there", "what kinds of tasks", "what missions exist", "kinds of missions", "mission categories"],
  checkin_reset_time: ["what time does checkin reset", "when does the streak reset", "when can i check in again", "checkin reset time", "when is the next check in"],
  checkin_amount_specific: ["how much is the checkin bonus", "checkin reward amount", "how much do i get for checking in", "daily bonus amount", "how much per check in"],
  checkin_twice: ["can i check in twice", "claim checkin again", "check in multiple times", "check in again today", "two check ins in one day"],
  security_tips: ["give me safety tips", "how do i stay safe", "how do i avoid getting scammed", "security advice", "how to protect my account", "safety advice", "stay secure"],
  phishing_warning: ["someone asked for my pin", "i got a fake link", "is this a scam message", "someone messaged me asking for my password", "someone wants my password", "suspicious message", "is this link safe"],
  multiple_accounts_allowed: ["can i have multiple accounts", "can i open a second account", "more than one account", "two accounts", "register twice", "second account"],
  account_deletion: ["how do i delete my account", "close my account", "deactivate my account", "remove my account", "remove my account", "i want to quit", "delete profile"],
  data_privacy: ["is my data safe", "what data do you collect", "privacy policy", "what information do you store", "do you sell my data", "personal information", "data protection"],
  currency_support: ["do you support usd", "can i use dollars", "is it only ugx", "other currencies", "do you accept dollars", "currency", "is it in shillings"],
  country_support: ["is this available outside uganda", "does it work in other countries", "only in uganda", "kenya", "tanzania", "can foreigners use it"],
  support_hours_check: ["what are your support hours", "when is support available", "is support 24 hours", "are you open now", "working hours", "support time"],
  response_time: ["how fast do you respond", "response time", "how long until support replies", "how long to get a reply", "when will support answer"],
  app_update_how: ["how do i update the app", "is there a new version", "how to get the latest version", "update space8", "latest app version"],
  clear_cache_stale: ["the app looks old", "my app is outdated", "app is not updating", "showing old data", "old version showing", "app not refreshing", "stale app"],
  offline_usage: ["can i use the app offline", "does it work without internet", "no internet", "works without data", "use offline"],
  notification_permission: ["im not getting notifications", "notifications not working", "notifications are off", "enable push", "allow notifications", "turn on alerts"],
  dark_mode_question: ["is there a dark mode", "night mode", "dark theme", "black mode"],
  language_support: ["do you support other languages", "can you speak luganda", "translate", "can you speak swahili", "do you translate", "another language", "english only", "other language support"],
  minimum_age: ["what is the minimum age", "how old do i have to be", "can a minor use this", "age limit", "can i use it at 17"],
  tax_question: ["do i pay tax", "what about taxes", "does space8 deduct tax", "is it taxed", "tax on earnings"],
  company_info: ["who owns space8", "who is the founder", "who runs this platform", "who is the ceo", "company details", "who is behind this", "management"],
  investment_risk: ["is it risky", "can i lose my money", "what is the risk", "how risky is it", "risk level", "can i lose everything"],
  guaranteed_returns: ["are returns guaranteed", "is the return guaranteed", "guaranteed profit", "is profit guaranteed", "sure returns"],
  plan_quantity_limit: ["is there a limit on buying the same plan", "how many times can i buy a plan", "limit on purchases", "cap on purchases", "how many times can i buy the same one"],
  giftcode_where: ["where do i get a gift code", "how do i get a promo code", "where to find gift codes", "source of gift codes", "how to find promo codes"],
  giftcode_value: ["how much is a gift code", "gift code value", "how much is a gift code worth", "gift code amount", "how much do codes give"],
  money_format_why: ["why dont you use k for money", "why show full numbers"],
  deposit_max: ["what is the maximum deposit", "is there a deposit limit", "most i can deposit", "upper deposit limit", "max i can deposit"],
  deposit_someone_else: ["can someone else deposit for me", "deposit from another number", "can my friend pay for me", "deposit using my wife number", "another person deposits for me", "use my brother number to deposit"],
  deposit_reference: ["what is the deposit reference", "where do i find the reference number", "reference id", "transaction reference", "ref number", "where is the reference"],
  deposit_not_in_records: ["my deposit is not in records", "deposit missing from history", "records missing my deposit", "deposit not listed in records", "not in my history"],
  deposit_wrong_amount: ["i deposited the wrong amount", "i deposited too much", "deposited by mistake", "sent more than i wanted", "wrong deposit amount"],
  deposit_charges: ["is there a deposit fee", "do you charge to deposit", "deposit charge", "deposit charges", "cost to deposit"],
  withdraw_cancel: ["can i cancel my withdrawal", "stop my withdrawal", "undo withdrawal", "reverse my cashout", "cancel cash out", "i want to stop the withdrawal"],
  withdraw_name_mismatch: ["the account name does not match", "name mismatch on withdrawal", "wrong account name", "names do not match", "account name is different"],
  withdraw_other_network: ["can i withdraw to a different network", "withdraw to another network", "withdraw to airtel instead", "different network payout"],
  withdraw_rejected: ["my withdrawal was rejected", "withdrawal declined", "cashout was refused", "withdrawal failed", "payout declined"],
  withdraw_weekend: ["do you process withdrawals on weekends", "withdrawal on sunday", "can i withdraw at night", "weekend payout", "withdraw on a holiday"],
  withdraw_history_where: ["where do i see my withdrawals", "withdrawal history", "where to check my cashouts", "see my withdrawals", "past withdrawals"],
  withdraw_to_bank: ["can i withdraw to my bank", "bank transfer withdrawal", "withdraw to bank account", "send to my bank", "bank payout"],
  my_plans_where: ["where do i see my plans", "where are my investments", "my products", "where to find my plans", "see my active plans", "my portfolio", "where are my products"],
  plan_progress: ["how do i track my plan progress", "how many days are left", "how far is my plan", "plan day count", "progress of my investment"],
  buy_without_deposit: ["can i buy a plan without depositing", "invest without money", "buy with no balance", "invest with zero balance", "purchase without funds"],
  partial_investment: ["can i invest a partial amount", "can i invest any amount", "half a plan", "invest small amount", "custom investment amount"],
  beginner_plan: ["which plan is good for a beginner", "what plan should i start with", "first time investor plan", "good plan for starters", "best plan to begin with"],
  plan_sold_out: ["why is a plan sold out", "what does upcoming mean on a plan", "plan is unavailable", "why is it upcoming", "product not purchasable"],
  same_plan_again: ["can i buy the same plan again", "two of the same plan", "repeat the same plan", "buy it twice"],
  referral_link_vs_code: ["what is the difference between the referral link and code", "link or code", "code vs link", "should i share link or code"],
  referral_earnings_where: ["where do i see my commission", "how much commission have i earned", "where to check referral earnings", "my commission total", "check referral income"],
  referral_expire: ["does a referral expire", "how long does a referral last", "do referrals stop", "do referrals expire", "referral validity"],
  team_not_counting: ["my referral is not counting", "i referred someone but they are not showing", "team member missing", "my referral did not show", "team member not added"],
  how_many_referrals: ["how many people can i refer", "is there a referral limit", "max referrals", "how many can i invite"],
  milestone_already_claimed: ["i already claimed this mission", "can i claim a milestone twice", "claimed already", "mission already done"],
  milestone_not_showing: ["task center is not showing", "my missions are missing", "task center is blank", "missions not loading", "no missions visible"],
  milestone_progress_source: ["how is mission progress counted", "how are team deposits counted for missions", "how is progress measured", "mission counting"],
  forgot_pin: ["i forgot my pin", "i lost my pin", "reset my pin", "cannot remember my withdrawal pin", "pin forgotten", "i dont remember my pin", "recover pin"],
  change_pin: ["how do i change my pin", "i want a new pin", "change withdrawal pin", "set a new pin", "update my pin"],
  pin_weak_rule: ["my pin was rejected", "why cant i use 1111", "pin too easy", "pin not accepted", "pin rejected", "why cant i use 0000", "weak pin"],
  multiple_devices: ["can i login on another phone", "use two devices", "sign in on a second device", "another device login", "two phones"],
  session_expired: ["my session expired", "why was i logged out", "it logged me out", "signed out automatically", "session ended"],
  change_password: ["how do i change my password", "i want a new password", "reset password", "set new password"],
  change_name: ["how do i change my name", "change my display name", "update my profile name", "edit my name", "name change"],
  account_hacked: ["my account was hacked", "someone is using my account", "unauthorized access", "someone stole my money", "account compromised", "someone accessed my account", "i was hacked"],
  pyramid_scheme: ["is this a pyramid scheme", "is this a ponzi", "is this mlm", "is it a ponzi scheme", "pyramid", "network marketing"],
  how_platform_earns: ["how does space8 make money", "how do you earn money", "where does the money come from", "your revenue model", "how do you profit"],
  platform_closes: ["what if the platform closes", "what happens if space8 shuts down", "if you shut down", "platform closure"],
  regulated: ["are you regulated", "do you have a license", "are you a registered company", "bank of uganda", "licensed", "legally registered", "regulation"],
  testimonials: ["has anyone been paid", "do others get paid", "does it really pay", "proof of payment", "anyone paid", "real withdrawals"],
  app_slow: ["the app is slow", "app is lagging", "the page is freezing", "very slow app", "loading slowly", "laggy"],
  blank_screen: ["i see a blank screen", "white screen", "nothing loads", "the page is empty", "screen is white", "app shows nothing"],
  button_not_working: ["the button is not working", "tapping does nothing", "button unresponsive", "cant tap the button", "button dead"],
  balance_wrong: ["my balance is wrong", "wallet is incorrect", "my balance did not update", "balance is not right", "balance not correct", "wrong wallet amount"],
  how_to_refresh: ["how do i refresh", "how to reload the app", "update my data", "refresh data", "reload page"],
  report_bug: ["i found a bug", "i want to report an error", "something is broken", "report a glitch", "there is an error", "report problem", "bug report"],
  suggest_feature: ["i have a suggestion", "feature request", "you should add something", "i have an idea", "my suggestion", "please add a feature"],
  are_you_sure: ["are you sure", "is that correct", "are you certain", "is that right", "really", "for sure", "you certain"],
  talk_to_human: ["i want to talk to a human", "can i speak to a person", "connect me to an agent", "real person please", "human support", "agent please", "speak to staff"],
  sorry_apology: ["sorry", "my bad", "apologies", "am sorry", "sorry about that"],
  compliment: ["you are great", "thats helpful", "good job", "nice work", "you are smart", "well done", "you are helpful", "nice one"],
  complaint_frustration: ["this is useless", "this is rubbish", "i am frustrated", "this is terrible", "i am angry", "this is bad", "very disappointed"],
  joke_smalltalk: ["tell me a joke", "are you bored", "whats up", "say something funny", "how is your day"],
  repeat_answer: ["what", "repeat", "say that again", "come again", "pardon", "again", "huh", "sorry what"],
  nothing_else: ["no", "nope", "nothing", "thats all", "im good", "no thanks", "none", "that is all"],
  yes_ack: ["yes", "yeah", "yep", "sure", "okay", "alright"]
};
