services:
  - type: web
    name: chocomcc-server
    runtime: node
    rootDir: choco-mcc
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: MARZPAY_KEY
        sync: false

  - type: web
    name: chocomcc-app
    runtime: static
    rootDir: choco-mcc/user
    buildCommand: "echo no build needed"
    staticPublishPath: .
    autoDeploy: true
    headers:
      - path: /sw.js
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: chocomcc-admin
    runtime: static
    rootDir: choco-mcc/admin
    buildCommand: "echo no build needed"
    staticPublishPath: .
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
