#!/usr/bin/env python3
"""Batch 9 of the admin panel's string table: the OPERATOR INSTRUCTIONS, part 2.

Continues admin-rows-8.py -- read its header first; the caution about the three
Bantu columns applies here at least as much, since these paragraphs cover the
payment screens, the auto-approval loop and the manual-deposit flow.

Brand and product names (MarzPay, LipaPay, PesaJet, Android, PNG, MP4, H.264,
WhatsApp, Telegram, CHIPZ), the "PAY A"/"PAY B" labels members actually see,
and the {{number}} / {{amount}} placeholders are left exactly as they are.

[english, lg, sw, fr, rw, nyn]
"""
ROWS = [
    ['One cash-out at a time, always. A member with a request still Pending, Sending or Processing cannot start another until it is paid or rejected. That is not a setting.',
     'Okuggyamu ssente kumu buli mulundi, bulijjo. Omuntu alina okusaba okukyali Kulindiriddwa, Kusindikibwa oba Kukolebwa tasobola kutandika kulala okutuusa nga kusasuddwa oba kugaanidwa. Kino si kya kutereeza.',
     'Utoaji mmoja kwa wakati, daima. Mwanachama mwenye ombi ambalo bado Linasubiri, Linatumwa au Linashughulikiwa hawezi kuanzisha lingine hadi lilipwe au likataliwe. Hili si mpangilio.',
     'Un seul retrait à la fois, toujours. Un membre dont la demande est encore En attente, En envoi ou En traitement ne peut pas en lancer une autre tant qu\'elle n\'est pas payée ou refusée. Ce n\'est pas un réglage.',
     'Kubikuza kumwe icyarimwe, buri gihe. Umunyamuryango ufite ubusabe bukiri ku Butegereje, Bwoherezwa cyangwa Butunganywa ntashobora gutangira ubundi kugeza bwishyuwe cyangwa bwanzwe. Ibi si igenamiterere.',
     'Okwihamu sente kumwe aha mwanya, obutoosha. Omuntu oine okushaba okukiri Kurikutegyerezibwa, Kurikutumwa nari Kurikukorwaho tarikubaasa kutandika okundi okuhitsya obu kushashwiirwe nari kwangirwe. Eki ti kya kutebeka.'],

    ['Paste a web address to find out which country it shows, and why. Use this whenever a subdomain behaves oddly — wrong currency, a correct password refused, or a referral code rejected.',
     'Teeka endagiriro y\'omukutu okumanya ggwanga ki ly\'eraga, n\'ensonga lwaki. Kozesa kino buli lwe subdomain bw\'ekola bubi — ssente ez\'ekyamu, ekisumuluzo ekituufu okugaanidwa, oba koodi y\'okuyita okugaanidwa.',
     'Bandika anwani ya wavuti ili kujua ni nchi gani inaonyesha, na kwa nini. Tumia hii kila mara kikoa kidogo kinapofanya vibaya — sarafu isiyo sahihi, nenosiri sahihi kukataliwa, au msimbo wa mwaliko kukataliwa.',
     'Collez une adresse web pour savoir quel pays elle affiche, et pourquoi. Utilisez ceci chaque fois qu\'un sous-domaine se comporte bizarrement — mauvaise devise, mot de passe correct refusé, ou code de parrainage rejeté.',
     'Komeka aderesi ya interineti kugira ngo umenye igihugu igaragaza, n\'impamvu. Koresha ibi igihe cyose urubuga rwungirije rukora nabi — ifaranga ritari ryo, ijambobanga ryiza ryanzwe, cyangwa kode yo gutumira yanzwe.',
     'Ta endagiriro y\'omutandaao kugira ngo omanye eihanga eri kworeka, n\'ahabw\'enki. Koresa eki obwiraaboona subdomain neekora kubi — sente ezitari zo, ekishumuruzo ekihikire kyangirwe, nari koodi y\'okweta yaangirwe.'],

    ['Paste any link (e.g. a WhatsApp group invite, https://chat.whatsapp.com/...) directly into the message -- it becomes tappable text automatically, right where you typed it.',
     'Teeka ekkubo lyonna (ng\'ekyokulabirako okuyita mu ggwanika lya WhatsApp, https://chat.whatsapp.com/...) butereevu mu bubaka -- lifuuka ebiwandiiko ebikwatibwako bwokka, mu kifo we walitadde.',
     'Bandika kiungo chochote (mfano mwaliko wa kikundi cha WhatsApp, https://chat.whatsapp.com/...) moja kwa moja kwenye ujumbe -- huwa maandishi yanayogusika chenyewe, pale pale ulipoandika.',
     'Collez n\'importe quel lien (par exemple une invitation à un groupe WhatsApp, https://chat.whatsapp.com/...) directement dans le message -- il devient automatiquement un texte cliquable, là où vous l\'avez tapé.',
     'Komeka umurongo uwo ari wo wose (urugero ubutumire bw\'itsinda rya WhatsApp, https://chat.whatsapp.com/...) mu butumwa -- uhita uba inyandiko ikandwa, aho wanditse.',
     'Ta omuhanda gwoona (nk\'eky\'okureeberaho okweta omu kibiina kya WhatsApp, https://chat.whatsapp.com/...) omu butumwa -- niguhinduka ebihandiiko ebirikukwatwaho gwonka, aho oguteire.'],

    ['Phones that already installed the app keep the old icon. Android copies the icon onto the home screen at install time and does not go back for it. To see a new icon on a phone that already has the app, remove it and install it again. New installs get the new icon straight away.',
     'Essimu ezaateekawo dda app zisigala n\'akafaananyi ak\'edda. Android ekoppa akafaananyi n\'akateeka ku lupapula olusooka nga app eteekebwawo, era teddayo kukanoonya. Okulaba akafaananyi akapya ku ssimu erina dda app, ggyawo app ogiteekewo nate. Ezitandikawo obuggya zifuna akafaananyi akapya amangu.',
     'Simu ambazo tayari zimesakinisha programu hubaki na aikoni ya zamani. Android hunakili aikoni kwenye skrini ya nyumbani wakati wa usakinishaji na hairudi kuichukua tena. Ili kuona aikoni mpya kwenye simu iliyo na programu tayari, iondoe kisha isakinishe upya. Usakinishaji mpya hupata aikoni mpya mara moja.',
     'Les téléphones qui ont déjà installé l\'application gardent l\'ancienne icône. Android copie l\'icône sur l\'écran d\'accueil au moment de l\'installation et ne revient jamais la chercher. Pour voir une nouvelle icône sur un téléphone qui a déjà l\'application, désinstallez-la puis réinstallez-la. Les nouvelles installations reçoivent tout de suite la nouvelle icône.',
     'Telefoni zimaze gushyiraho porogaramu zigumana agashushondanga ka kera. Android ikoporora agashushondanga kuri ecran y\'ibanze igihe cyo gushyiraho kandi ntisubira kukazana. Kugira ngo ubone agashushondanga gashya kuri telefoni isanzwe ifite porogaramu, uyikureho hanyuma uyisubizeho. Abashya bahita babona agashushondanga gashya.',
     'Enyabarugo ezaataireho puroguramu nizisigara n\'akashushani aka ira. Android neekopa akashushani ekakata aha rupapura orw\'omuka obu puroguramu erikutairweho kandi tegarukayo kukashaka. Kugira ngo oreebe akashushani akasya aha nyabarugo eyine puroguramu, gyiihaho oigarukyemu. Ezirikutandika obusya nizitunga akashushani akasya ahonaaho.'],

    ['Replaces the CHIPZ wordmark on the manual-deposit flow\'s own 2 screens. An empty slot keeps the wordmark. Saved as PNG, so a logo with no background stays that way.',
     'Kiddira mu kifo ky\'akabonero ka CHIPZ ku mpapula 2 ez\'okuteekamu ssente n\'engalo. Ekifo ekyereere kireka akabonero nga bwe kali. Kiterekebwa nga PNG, kale akafaananyi akatalina mabega kasigala nga bwe kali.',
     'Inachukua nafasi ya nembo ya maneno ya CHIPZ kwenye skrini 2 za mtiririko wa amana ya mkono. Nafasi tupu huacha nembo ile ile. Huhifadhiwa kama PNG, kwa hivyo nembo isiyo na mandharinyuma hubaki hivyo.',
     'Remplace le logotype CHIPZ sur les 2 écrans propres au parcours de dépôt manuel. Un emplacement vide garde le logotype. Enregistré en PNG, donc un logo sans fond le reste.',
     'Isimbura ikirango cy\'amagambo CHIPZ ku mapaji 2 y\'inzira yo gushyiramo amafaranga n\'intoki. Umwanya usa ureka ikirango uko kiri. Kibikwa nka PNG, bityo ikirango kidafite inyuma kiguma gityo.',
     'Nikitwara omwanya gw\'akamanyiso ka CHIPZ aha mapaaji 2 g\'omuhanda gw\'okuta sente n\'engaro. Omwanya ogwo busha nigureka akamanyiso. Nikibikwa nka PNG, n\'ahabw\'ekyo ekirango ekitaine nyima nikiguma kityo.'],

    ['Shown on the manual-deposit code screen once the member picks that network. Use {{number}} and {{amount}} anywhere in the steps -- both are replaced with that member\'s own real account number and order amount. Leave a network blank to hide the section for it.',
     'Kiraga ku lupapula lwa koodi ey\'okuteekamu ssente n\'engalo ng\'omuntu amaze okulonda netiwaka eyo. Kozesa {{number}} ne {{amount}} wonna mu ntambula -- byombi biddizibwa nnamba ya akawunti y\'omuntu oyo ne ssente z\'asaba. Leka netiwaka nga yereere okukweka ekitundu kyayo.',
     'Huonyeshwa kwenye skrini ya msimbo wa amana ya mkono mara tu mwanachama anapochagua mtandao huo. Tumia {{number}} na {{amount}} popote kwenye hatua -- vyote hubadilishwa kuwa namba halisi ya akaunti ya mwanachama huyo na kiasi cha oda yake. Acha mtandao wazi ili kuficha sehemu yake.',
     'Affiché sur l\'écran du code de dépôt manuel dès que le membre choisit ce réseau. Utilisez {{number}} et {{amount}} n\'importe où dans les étapes -- les deux sont remplacés par le vrai numéro de compte de ce membre et le montant de sa commande. Laissez un réseau vide pour masquer sa section.',
     'Bigaragara ku ipaji rya kode yo gushyiramo amafaranga n\'intoki iyo umunyamuryango ahisemo urwo rusobe. Koresha {{number}} na {{amount}} ahantu hose mu ntambwe -- byombi bisimburwa na nimero nyayo ya konti y\'uwo munyamuryango n\'umubare w\'ubusabe bwe. Reka urusobe ubusa kugira ngo uhishe igice cyarwo.',
     'Nikireeberwa aha rupapura rwa koodi y\'okuta sente n\'engaro obu omuntu arikucwamu neetiweeki egyo. Koresa {{number}} na {{amount}} hoona omu ntambura -- byombi nibigaruzibwamu namba ya akaunti y\'omuntu ogwo n\'omuhendo gw\'ebi arikushaba. Reka neetiweeki eri busha kugira ngo oshereke akacweka kaayo.'],

    ['Only if you put the file in the same upload as the app — type its name (for example banner.mp4), or paste a full https:// link to a video file. Saving here replaces an uploaded video, and uploading replaces this.',
     'Kyokka bw\'oba oteeka fayiro mu kuteeka kwe kumu n\'app — wandiika erinnya lyayo (ng\'ekyokulabirako banner.mp4), oba oteeka ekkubo ekijjuvu erya https:// eridda ku fayiro ya vidiyo. Okutereka wano kiddira mu kifo kya vidiyo eyateekebwa, ate okuteeka vidiyo kiddira mu kifo kya kino.',
     'Ni tu ikiwa umeweka faili katika upakiaji ule ule wa programu — andika jina lake (mfano banner.mp4), au bandika kiungo kamili cha https:// cha faili ya video. Kuhifadhi hapa hubadilisha video iliyopakiwa, na kupakia hubadilisha hii.',
     'Seulement si vous mettez le fichier dans le même téléversement que l\'application — tapez son nom (par exemple banner.mp4), ou collez un lien https:// complet vers un fichier vidéo. Enregistrer ici remplace une vidéo téléversée, et téléverser remplace ceci.',
     'Gusa niba washyize dosiye mu bwoherezwa bumwe na porogaramu — andika izina ryayo (urugero banner.mp4), cyangwa ukomeke umurongo wuzuye wa https:// werekeza kuri dosiye ya videwo. Kubika hano bisimbura videwo yashyizweho, no gushyiraho bisimbura ibi.',
     'Kwonka ku oraate eifaira omu kuta kumwe na puroguramu — handiika eiziina ryayo (nk\'eky\'okureeberaho banner.mp4), nari ota omuhanda ogwijwire ogwa https:// ogurikuza aha ifaira ya vidiyo. Okubika hanu nikitwara omwanya gwa vidiyo eyatairweho, kandi okuta vidiyo nikitwara omwanya gw\'eki.'],

    ['MP4 (H.264), up to 4 MB. That cap is about your members, not the database: the clip downloads onto every phone that opens the app. A few silent seconds is what belongs here. Uploaded once, it is then served from its own cached address, so a member downloads it one time and replays it from their phone after that.',
     'MP4 (H.264), okutuuka ku 4 MB. Ekkomo eryo likwata ku bantu bo, si ku ttereka: vidiyo ekkakkanyizibwa ku buli ssimu eyiggula app. Obudde obutono obutaliimu maloboozi bwe busaanira wano. Bw\'emala okuteekebwa, eweerezebwa okuva ku ndagiriro yaayo, kale omuntu agikkakkanya omulundi gumu n\'oluvannyuma agizanyisa okuva ku ssimu ye.',
     'MP4 (H.264), hadi 4 MB. Kikomo hicho kinahusu wanachama wako, si hifadhidata: klipu hupakuliwa kwenye kila simu inayofungua programu. Sekunde chache zisizo na sauti ndizo zinazofaa hapa. Ikishapakiwa mara moja, hutolewa kutoka anwani yake iliyohifadhiwa, kwa hivyo mwanachama huipakua mara moja kisha huicheza tena kutoka simu yake.',
     'MP4 (H.264), jusqu\'à 4 Mo. Cette limite concerne vos membres, pas la base de données : le clip se télécharge sur chaque téléphone qui ouvre l\'application. Quelques secondes sans son, voilà ce qui a sa place ici. Une fois téléversé, il est servi depuis sa propre adresse mise en cache, donc un membre le télécharge une seule fois et le rejoue ensuite depuis son téléphone.',
     'MP4 (H.264), kugeza kuri 4 MB. Uwo mupaka ureba abanyamuryango bawe, si ububikoshingiro: agace ka videwo kamanurwa kuri buri telefoni ifungura porogaramu. Amasegonda macye adafite ijwi ni yo akwiriye hano. Iyo yamaze gushyirwaho, itangwa iva kuri aderesi yayo bwite, bityo umunyamuryango ayimanura rimwe akongera kuyireba ava kuri telefoni ye.',
     'MP4 (H.264), okuhika aha 4 MB. Ekikomo ekyo nikikwata aha bantu baawe, ti aha bubiiko: vidiyo neeihurwa aha buri nyabarugo erikwigura puroguramu. Obwire obukye obutaine maraka nibwo bushemereire hanu. Ku erikuba etairweho, neeheebwa kuruga aha ndagiriro yaayo, n\'ahabw\'ekyo omuntu naagyihura omurundi gumwe reero akagizaanisa kuruga aha nyabarugo ye.'],

    ['Members now see up to 2 payment options on the Recharge screen, labelled neutrally "PAY A" and "PAY B" (no "manual"/"automatic" wording is ever shown to them) -- enable either one alone, or both at once so the member picks. PAY A is the automatic gateway (MarzPay, LipaPay or PesaJet, chosen below) -- instant, no admin numbers needed, and no network to select either: the gateway detects it from the phone number. PAY B is manual -- assigns the member one of the numbers below to send money to by hand, matched to their order by your phone\'s SMS forwarder (or by the member pasting their own confirmation text if the forwarder is slow).',
     'Abantu kati balaba engeri 2 ez\'okusasula ku lupapula lw\'okuteekamu ssente, nga ziyitibwa "PAY A" ne "PAY B" (tebalaba bigambo bya "n\'engalo" oba "bwokka") -- ssobozesa emu yokka, oba zombi omuntu alonde. PAY A gwe mulyango ogwekolera (MarzPay, LipaPay oba PesaJet, ezirondebwa wansi) -- gwa mangu, tegwetaaga nnamba za bakulembeze, era tewali netiwaka ya kulonda: omulyango gugizuula okuva ku nnamba y\'essimu. PAY B gwa ngalo -- guwa omuntu emu ku nnamba eziri wansi asobole okusindika ssente n\'engalo, nga zikwatagana n\'okusaba kwe okuyita mu SMS forwarder y\'essimu yo (oba omuntu bw\'ateeka obubaka bwe obukakasa singa forwarder elwawo).',
     'Wanachama sasa huona hadi njia 2 za malipo kwenye skrini ya Kuweka Pesa, zikiitwa "PAY A" na "PAY B" (hawaonyeshwi kamwe maneno "kwa mkono"/"kiotomatiki") -- washa moja pekee, au zote mbili ili mwanachama achague. PAY A ni lango la kiotomatiki (MarzPay, LipaPay au PesaJet, lililochaguliwa hapa chini) -- la papo hapo, halihitaji namba za msimamizi, wala hakuna mtandao wa kuchagua: lango hulitambua kutoka namba ya simu. PAY B ni la mkono -- humpa mwanachama mojawapo ya namba zilizo hapa chini ili atume pesa kwa mkono, zikilinganishwa na oda yake na kisambazaji cha SMS cha simu yako (au kwa mwanachama kubandika ujumbe wake wa uthibitisho ikiwa kisambazaji ni cha polepole).',
     'Les membres voient maintenant jusqu\'à 2 options de paiement sur l\'écran de Recharge, étiquetées neutrement "PAY A" et "PAY B" (aucune mention de "manuel" ou "automatique" ne leur est jamais montrée) -- activez l\'une seule, ou les deux à la fois pour que le membre choisisse. PAY A est la passerelle automatique (MarzPay, LipaPay ou PesaJet, choisie ci-dessous) -- instantanée, sans numéros d\'administrateur, et sans réseau à sélectionner : la passerelle le détecte depuis le numéro de téléphone. PAY B est manuel -- il attribue au membre l\'un des numéros ci-dessous pour envoyer l\'argent à la main, rapproché de sa commande par le transfert SMS de votre téléphone (ou par le membre qui colle son propre message de confirmation si le transfert est lent).',
     'Abanyamuryango ubu babona uburyo bwo kwishyura bugera kuri 2 ku ipaji ryo Kongeramo, bwitwa "PAY A" na "PAY B" (nta jambo "n\'intoki" cyangwa "byikora" bigeze bibereka) -- fungura bumwe gusa, cyangwa bwombi kugira ngo umunyamuryango ahitemo. PAY A ni irembo ryikora (MarzPay, LipaPay cyangwa PesaJet, ryatoranyijwe hasi) -- ryihuta, ntirisaba nimero z\'ubuyobozi, kandi nta rusobe rwo guhitamo: irembo rurubona kuri nimero ya telefoni. PAY B ni ubwo n\'intoki -- buha umunyamuryango imwe muri nimero zikurikira kugira ngo yohereze amafaranga n\'intoki, bihuzwa n\'ubusabe bwe n\'icyoherezabutumwa cya telefoni yawe (cyangwa umunyamuryango akomeka ubutumwa bwe bwemeza igihe icyoherezabutumwa gitinze).',
     'Abantu hati nibareeba emiringo 2 y\'okushashura aha rupapura rw\'Okuta Sente, nerwetwa "PAY A" na "PAY B" (tibarikureeberwa ebigambo "n\'engaro" nari "kyenka") -- igurira emwe yonka, nari yombi kugira ngo omuntu acwemu. PAY A n\'omuryango ogurikwekorera (MarzPay, LipaPay nari PesaJet, egirikucwamu ahansi) -- gwa mbago, tigurikwetenga namba z\'abebembezi, kandi tihariho neetiweeki y\'okucwamu: omuryango nigugishanga kuruga aha namba y\'esimu. PAY B n\'ogw\'engaro -- niguha omuntu emwe aha namba eziri ahansi kugira ngo atume sente n\'engaro, nizihuzibwa n\'ebi arikushaba n\'ekitumi kya SMS eky\'esimu yaawe (nari omuntu yaata obutumwa bwe oburikuhamya ku ekitumi kirikuguma).'],

    ['Payments are set to Manual, so payouts do not go through any automatic gateway. Send the money yourself from an admin mobile money phone to the destination number on the row, then tap Mark as paid. Marking a row paid only records a payment you have already made, it never sends anything. Auto-approve is ignored while this mode is on.',
     'Okusasula kuteekeddwa ku Manual, kale okusasula tekuyita mu mulyango gwonna ogwekolera. Sindika ssente ggwe kennyini okuva ku ssimu y\'omukulembeze ey\'ssente ez\'oku ssimu okudda ku nnamba eri ku lunyiriri, oluvannyuma onyige Laga nga kisasuddwa. Okulaga olunyiriri nga lusasuddwa kuwandiika bwawandiisi okusasula kwe wamaze okukola, tekusindika kintu kyonna. Okukkiriza okwekolera tekussibwako mmere nga eno ekola.',
     'Malipo yamewekwa kuwa ya Mkono, kwa hivyo malipo hayapiti kwenye lango lolote la kiotomatiki. Tuma pesa wewe mwenyewe kutoka simu ya pesa ya msimamizi kwenda namba ya lengo iliyo kwenye safu, kisha gusa Weka alama kuwa imelipwa. Kuweka alama kwenye safu hurekodi tu malipo uliyokwisha fanya, hakutumi chochote. Kuidhinisha kiotomatiki hupuuzwa wakati hali hii imewashwa.',
     'Les paiements sont réglés sur Manuel, donc les versements ne passent par aucune passerelle automatique. Envoyez l\'argent vous-même depuis un téléphone mobile money d\'administrateur vers le numéro de destination indiqué sur la ligne, puis touchez Marquer comme payé. Marquer une ligne comme payée ne fait qu\'enregistrer un paiement que vous avez déjà effectué, cela n\'envoie jamais rien. L\'approbation automatique est ignorée tant que ce mode est actif.',
     'Kwishyura byashyizwe kuri Manual, bityo kwishyura ntibinyura mu irembo iryo ari ryo ryose ryikora. Ohereza amafaranga ubwawe uvuye kuri telefoni y\'ubuyobozi y\'amafaranga ujya kuri nimero igaragara ku murongo, hanyuma ukande Shyiraho ko byishyuwe. Gushyiraho ko umurongo wishyuwe byandika gusa kwishyura wamaze gukora, ntibyohereza ikintu na kimwe. Kwemeza byikora ntibyitabwaho igihe ubu buryo bukoresha.',
     'Okushashura kutairwe aha Manual, n\'ahabw\'ekyo okushashura tikurikurabira omu muryango gwoona ogurikwekorera. Tuma sente iwe omwene kuruga aha simu y\'omwebembezi ey\'esente z\'aha simu okuza aha namba eri aha murongo, reero okande Manyisa ngu kishashwiirwe. Okumanyisa omurongo ngu gushashwiirwe nikihandiika kwonka okushashura oku waaba omazire kukora, tikirikutuma kintu. Okwikiriza kwenka tikurikutwarwaho ku ogu murikukora.'],

    ['Server-driven: while on, every incoming withdrawal request first waits the interval below (measured from the moment it was requested, even a single request always waits the full interval, it\'s never approved instantly) before the server approves and sends it. It checks every few seconds, and every request that\'s old enough at that moment is approved and sent back-to-back in the same pass, not spaced apart from each other. No tap needed per request. It reuses the exact same send logic as the approve button on the Withdrawals tab (whichever provider that currently sends through), so it can never double-pay a request or act on one that isn\'t still genuinely pending.',
     'Kikolebwa sseva: nga kikola, buli kusaba okuggyamu ssente kusooka kulinda ekiseera ekiri wansi (okubalirwa okuva lwe kusabiddwa, ne bwe kuba kumu kulinda ekiseera kyonna, tekukkirizibwa mangu) sseva nga tennakukkiriza n\'okukusindika. Ekebera buli sekonda ntono, era buli kusaba okumaze ekiseera ekimala mu kaseera ako kukkirizibwa ne kusindikibwa kumpi na kunnaakwo mu mulundi gwe gumu, si nga kwawukanyiziddwa. Tewali kunyiga kwetaagisa ku buli kusaba. Kikozesa enkola y\'okusindika y\'emu n\'eya bbaatani ey\'okukkiriza ku ttabu lya Okuggyamu (ne provider gw\'ekozesa mu kiseera ekyo), kale tekiyinza kusasula mulundi gwa kubiri oba okukola ku kusaba okutakyali mu kulindirira.',
     'Inaendeshwa na seva: ikiwa imewashwa, kila ombi la utoaji linalowasili kwanza husubiri muda ulio hapa chini (unaohesabiwa tangu ombi lilipowekwa, hata ombi moja husubiri muda wote, halikubaliwi papo hapo) kabla seva haijaidhinisha na kulituma. Hukagua kila sekunde chache, na kila ombi lililokomaa wakati huo huidhinishwa na kutumwa mfululizo katika pasi ile ile, si kwa kutenganishwa. Hakuna kugusa kunakohitajika kwa kila ombi. Hutumia mantiki ile ile ya kutuma kama kitufe cha kuidhinisha kwenye kichupo cha Utoaji (mtoa huduma yeyote anayetumika wakati huo), kwa hivyo haiwezi kamwe kulipa ombi mara mbili au kushughulikia lile ambalo halisubiri kweli.',
     'Piloté par le serveur : lorsqu\'il est actif, chaque demande de retrait entrante attend d\'abord l\'intervalle ci-dessous (compté depuis le moment de la demande ; même une demande isolée attend toujours l\'intervalle complet, elle n\'est jamais approuvée instantanément) avant que le serveur ne l\'approuve et ne l\'envoie. Il vérifie toutes les quelques secondes, et chaque demande assez ancienne à ce moment-là est approuvée et envoyée à la suite dans le même passage, sans être espacée. Aucun appui nécessaire par demande. Il réutilise exactement la même logique d\'envoi que le bouton d\'approbation de l\'onglet Retraits (quel que soit le prestataire qui envoie actuellement), il ne peut donc jamais payer deux fois une demande ni agir sur une demande qui n\'est plus réellement en attente.',
     'Biyoborwa na seriveri: iyo bikoresha, buri busabe bwo kubikuza buhageze butegereza mbere igihe kiri hasi (kibarwa uhereye igihe bwasabwe; n\'ubusabe bumwe buhora butegereza igihe cyose, ntibwemezwa ako kanya) mbere y\'uko seriveri ibwemeza ikanabwohereza. Igenzura buri masegonda macye, kandi buri busabe bwakuze icyo gihe bwemezwa bukoherezwa bukurikiranye muri iyo nzira imwe, atari mu buryo butandukanyije. Nta gukanda bikenewe kuri buri busabe. Ikoresha uburyo bwo kohereza bumwe n\'ubwa buto bwo kwemeza bwo ku gice cy\'Ukubikuza (uwo ari we wese utanga serivisi icyo gihe), bityo ntibishobora kwishyura ubusabe kabiri cyangwa gukora ku bwo butakiri ku butegereje koko.',
     'Nikikorwa seeva: ku erikuba erikukora, buri kushaba okwihamu sente kurikwija nikubanza kutegyereza obwire oburi ahansi (nibubarwa kuruga obu kwashabirwe; n\'okushaba kumwe nikutegyereza obwire bwoona, tikurikwikirizibwa ahonaaho) seeva etakakwikiriize n\'okukutuma. Neekyebera buri sekonda nkye, kandi buri kushaba okumazire obwire obuhikire aha kaanya ako nikwikirizibwa kikatumwa nikukuratana omu muringo gumwe, ti nikwahukanisibwa. Tihariho kukanda okurikwetengwa aha buri kushaba. Nikikoresa omuringo gw\'okutuma ogwo gumwe nk\'ogwa akabatuni k\'okwikiriza aha kacweka k\'Okwihamu (ou arikuheereza aha kaanya ako), n\'ahabw\'ekyo tikirikubaasa kushashura okushaba emirundi ebiri nari kukora aha okutakiri omu kutegyerezibwa buzima.'],

    ['Shown centered over Home every time a member opens or returns to it. Dark background, matching the Home activity ticker. The optional image (if set) shows above the message and scrolls together with it if the dialog\'s content runs long. The OK button opens Telegram group above (falls back to the channel link if group is blank) and closes the dialog; the X in the corner just closes it.',
     'Kiraga wakati ku Home buli lwe omuntu aggula oba adda ku yo. Emabega eddugavu, nga lifaanagana n\'olukalala lw\'ebikolebwa ku Home. Ekifaananyi ekiyinza okuteekebwa (bwe kiba kiriwo) kiraga waggulu w\'obubaka era kiseerera nakyo singa ebiri mu kabokisi biba biwanvu. Bbaatani ya OK egguka ggwanika lya Telegram eriri waggulu (bw\'eba nga terimu, egguka ekkubo ly\'omukutu) era eggalawo akabokisi; X eri ku nsonda ekaggalawo kyokka.',
     'Huonyeshwa katikati juu ya Nyumbani kila mara mwanachama anapofungua au kurudi. Mandharinyuma meusi, yanayolingana na mstari wa shughuli wa Nyumbani. Picha ya hiari (ikiwekwa) huonyeshwa juu ya ujumbe na husogea pamoja nao ikiwa maudhui ya kisanduku ni marefu. Kitufe cha SAWA hufungua kikundi cha Telegram hapo juu (hurudi kwenye kiungo cha chaneli ikiwa kikundi ni tupu) na hufunga kisanduku; X iliyo pembeni huifunga tu.',
     'Affiché centré par-dessus l\'Accueil chaque fois qu\'un membre l\'ouvre ou y revient. Fond sombre, assorti au bandeau d\'activité de l\'Accueil. L\'image facultative (si elle est définie) apparaît au-dessus du message et défile avec lui si le contenu de la boîte est long. Le bouton OK ouvre le groupe Telegram ci-dessus (et revient au lien du canal si le groupe est vide) puis ferme la boîte ; le X dans le coin ne fait que la fermer.',
     'Bigaragara hagati hejuru ya Ahabanza buri gihe umunyamuryango afunguye cyangwa agarutseho. Inyuma yijimye, ihuye n\'umurongo w\'ibikorwa wo Ahabanza. Ishusho itari itegeko (niba yashyizweho) igaragara hejuru y\'ubutumwa kandi inyerera hamwe na bwo iyo ibiri mu kazu ari byinshi. Buto ya OK ifungura itsinda rya Telegram riri haruguru (igasubira ku murongo w\'umuyoboro iyo itsinda risa) hanyuma igafunga akazu; X iri ku mpera ihita ikafunga gusa.',
     'Nikireeberwa ahagati aha Home buri obu omuntu arikwigura nari kugarukaho. Enyima ekwatsiire, erikushushana n\'orurongo rw\'ebirikukorwa aha Home. Ekishushani ekirikubaasa kutairweho (ku kiraabe kiriho) nikireeberwa haiguru y\'obutumwa kandi nikigyenda nabwo ku ebiri omu kabokisi biraabe biri bireingwa. Akabatuni ka OK nikigura ekibiina kya Telegram ekiri haiguru (kikagaruka aha muhanda gw\'omuhanda ku ekibiina kiraabe kiri busha) reero kikakinga akabokisi; X eri aha nsonda neekinga kwonka.'],

    ['Set per product, not here — open Products, edit a product, and use its "Turntable spins from this product" section to set how many spins it earns and what each can win. That way every product can pay differently.',
     'Kiteekebwa ku buli kyamaguzi, si wano — ggulawo Ebyamaguzi, kyusa ekyamaguzi, era okozese ekitundu kyakyo ekya "Turntable spins from this product" okuteeka okukyusa kwe kiwa n\'ekyo buli kumu kwe kuyinza okuwangula. Mu ngeri eyo buli kyamaguzi kisobola okusasula mu ngeri yaakyo.',
     'Huwekwa kwa kila bidhaa, si hapa — fungua Bidhaa, hariri bidhaa, kisha tumia sehemu yake ya "Turntable spins from this product" kuweka mizunguko inayopatikana na kila mmoja anaweza kushinda kiasi gani. Kwa njia hiyo kila bidhaa inaweza kulipa tofauti.',
     'À régler par produit, pas ici — ouvrez Produits, modifiez un produit, et utilisez sa section "Turntable spins from this product" pour définir combien de tours il rapporte et ce que chacun peut gagner. Ainsi chaque produit peut payer différemment.',
     'Bishyirwaho kuri buri gicuruzwa, atari hano — fungura Ibicuruzwa, uhindure igicuruzwa, hanyuma ukoreshe igice cyacyo cya "Turntable spins from this product" kugira ngo ushyireho inzunguruka gitanga n\'ibyo buri imwe ishobora gutsindira. Muri ubwo buryo buri gicuruzwa gishobora kwishyura ukundi.',
     'Nikitebekwa aha buri kyamaguzi, ti hanu — igura Ebyamaguzi, ohindure ekyamaguzi, reero okoreese akacweka kaakyo aka "Turntable spins from this product" kugira ngo ote okuzunguka oku kirikuha n\'eki buri kumwe kurikubaasa kutunga. Omu muringo ogwo buri kyamaguzi nikibaasa kushashura kwahukanye.'],
]
