#!/usr/bin/env python3
"""Batch 4 of the admin panel's own string table: the captions and tooltips,
plus the panel's {0}-templates.

These are the sentences under a control that say what it does, and the
title= tooltips on the buttons that act on real money or real accounts.
They are the ones worth most to an operator who does not read English --
and the ones where a careless translation costs the most, so the three
Bantu columns want a native speaker's eye before launch, exactly as the
member app's own table says.

[english, lg, sw, fr, rw, nyn]
"""
ROWS = [
    ['Auto-refresh the current tab as new activity arrives', 'Ddamu ozze oddamu olupapula luno nga ebikolwa ebipya bituuse', 'Onyesha upya ukurasa huu shughuli mpya zinapofika', 'Actualiser cet onglet dès qu\'une nouvelle activité arrive', 'Kuvugurura uru rupapuro igihe ibikorwa bishya bigeze', 'Garuka oyongyere orupapura ruru ebikorwa bisya ku birikuhika'],
    ['Direct contact (Telegram), shown as "Customer Service"', 'Endagiriro ey\'obutereevu (Telegram), erabika nga "Obuweereza eri Abaguzi"', 'Mawasiliano ya moja kwa moja (Telegram), yanaonyeshwa kama "Huduma kwa Wateja"', 'Contact direct (Telegram), affiché comme « Service client »', 'Aho wahamagara ako kanya (Telegram), byerekanwa nka "Serivisi z\'abakiriya"', 'Endagiriro y\'obuhango (Telegram), neeyorekwa nka "Obuheereza aha Baguzi"'],
    ['Full upline-to-root and downline tree, not just L1/L2/L3', 'Omuti gwonna okuva waggulu okutuuka wansi, si mitendera 1/2/3 yokka', 'Mti kamili kutoka juu hadi chini, si ngazi 1/2/3 tu', 'Arbre complet, vers le haut et vers le bas, pas seulement N1/N2/N3', 'Igiti cyuzuye kuva hejuru kugeza hasi, atari urwego rwa 1/2/3 gusa', 'Omuti gwona kuruga ahaiguru kuhitsya ahansi, tiy\'emirengo 1/2/3 yoonka'],
    ['Tell members what\'s new, or invite them to your Telegram group…', 'Buulira abakozesa ekipya, oba bayite mu kibiina kyo ekya Telegram…', 'Waambie wanachama kipya, au wakaribishe kwenye kikundi chako cha Telegram…', 'Dites aux membres ce qui est nouveau, ou invitez-les sur votre groupe Telegram…', 'Bwira abanyamuryango ibishya, cyangwa ubatumire mu itsinda ryawe rya Telegram…', 'Gambira abakozesa ekisya, nari obayete omu kibiina kyawe kya Telegram…'],
    ['Mint five at once -- what moving arrivals between addresses needs', 'Kola ttaano mu kiseera kimu -- kye kyetaagisa okukyusa abatuuka mu ndagiriro', 'Tengeneza tano kwa mara moja -- ndivyo kuhamisha wanaofika kati ya anwani kunahitaji', 'Créer cinq d\'un coup -- ce qu\'exige le déplacement des arrivants entre adresses', 'Gukora eshanu icyarimwe -- ni byo kwimura abaza hagati y\'aderesi bisaba', 'Hanga itaano omu kaanya kamwe -- nikyo okwimura abarikuhika omu ndagiriro kirikwetenga'],
    ['The most recent 200 sensitive actions across the panel, newest first.', 'Ebikolwa 200 ebisembayo eby\'obwegendereza ku lupapula lwonna, ebipya bisooka.', 'Vitendo 200 vya hivi karibuni nyeti katika paneli nzima, vipya kwanza.', 'Les 200 actions sensibles les plus récentes du panneau, les plus récentes d\'abord.', 'Ibikorwa 200 bya vuba byitondewe muri paneli yose, bishya mbere.', 'Ebikorwa 200 eby\'obwegyendereza eby\'obwire obuhingwire, ebisya bikatandika.'],
    ['Mint a new short address for this country, e.g. g26e.chipz-platform.com', 'Kola endagiriro empya ennyimpi ey\'eggwanga lino, okugeza g26e.chipz-platform.com', 'Tengeneza anwani fupi mpya kwa nchi hii, mfano g26e.chipz-platform.com', 'Créer une nouvelle adresse courte pour ce pays, ex. g26e.chipz-platform.com', 'Gukora aderesi ngufi nshya y\'iki gihugu, urugero g26e.chipz-platform.com', 'Hanga endagiriro empya engufu y\'ihanga eri, nk\'okugyera g26e.chipz-platform.com'],
    ['Recompute this member\'s streak from their real check-in history right now', 'Ddamu obale olunyiriri lw\'okukyalira kw\'omukozesa ono okuva mu byafaayo bye kaakano', 'Hesabu upya mfululizo wa mwanachama huyu kutoka historia yake halisi sasa hivi', 'Recalculer la série de ce membre à partir de son historique réel, maintenant', 'Kongera kubara uruhererekane rw\'uyu munyamuryango uhereye ku mateka ye nyayo ubu', 'Garuka obare omunyororo gw\'okwoleka kw\'omukozesa ogu kuruga omu byafaayo bye hati'],
    ['Uploading a picture saves it immediately. Opacity and blur need this button.', 'Okuteekamu ekifaananyi kikitereka mangu ago. Obuzibu n\'okusiikuula byetaaga akapeesa kano.', 'Kupakia picha huihifadhi papo hapo. Uzito na ufifishaji vinahitaji kitufe hiki.', 'Téléverser une image l\'enregistre aussitôt. L\'opacité et le flou demandent ce bouton.', 'Gushyiramo ishusho biyibika ako kanya. Ubwijime n\'ukwijima bisaba iyi buto.', 'Okutaamu ekishushani nikikibiika ahonaaho. Obuzibu n\'okusiikuura nibyetenga akapeera aka.'],
    ['Shown under Account → Rules & Regulation. Blank leaves the page empty in the app.', 'Kirabika wansi wa Akawunti → Amateeka. Bwe kiba kyereere olupapula lusigala nga lwereere mu pulogulaamu.', 'Inaonyeshwa chini ya Akaunti → Sheria na Kanuni. Tupu huacha ukurasa mtupu kwenye programu.', 'Affiché sous Compte → Règles et règlement. Vide laisse la page vide dans l\'application.', 'Bigaragara munsi ya Konti → Amategeko n\'amabwiriza. Ubusa busiga urupapuro rutariho muri porogaramu.', 'Nikyorekwa ahansi ya Akaunti → Ebiragiro. Ku kiraaba kitariho orupapura nirusigara rutariho omu porogaraamu.'],
    ['Shown at the top of the Home tab in the app. An empty slot uses the built-in default artwork.', 'Kirabika waggulu ku lupapula olusooka mu pulogulaamu. Ekifo ekyereere kikozesa ekifaananyi ekitongole.', 'Inaonyeshwa juu ya ukurasa wa nyumbani kwenye programu. Nafasi tupu hutumia mchoro wa chaguo-msingi.', 'Affiché en haut de l\'onglet Accueil dans l\'application. Un emplacement vide utilise l\'illustration par défaut.', 'Bigaragara hejuru ku rupapuro rw\'ahabanza muri porogaramu. Umwanya utariho ukoresha ishusho isanzwe.', 'Nikyorekwa ahaiguru aha rupapura rw\'omuka omu porogaraamu. Ekyanya ekitariho nikikozesa ekishushani ekitairweho.'],
    ['Shown at the top of the app\'s Referral tab, above the share link. An empty slot uses the built-in gradient artwork.', 'Kirabika waggulu ku lupapula lw\'okuyita, waggulu w\'ekinywanyizo ky\'okugabana. Ekifo ekyereere kikozesa ekifaananyi eky\'langi ekitongole.', 'Inaonyeshwa juu ya ukurasa wa mialiko, juu ya kiungo cha kushiriki. Nafasi tupu hutumia mchoro wa rangi wa chaguo-msingi.', 'Affiché en haut de l\'onglet Parrainage, au-dessus du lien de partage. Un emplacement vide utilise le dégradé par défaut.', 'Bigaragara hejuru ku rupapuro rwo gutumira, hejuru y\'umurongo wo gusangiza. Umwanya utariho ukoresha amabara asanzwe.', 'Nikyorekwa ahaiguru aha rupapura rw\'okweta, ahaiguru y\'omukwate gw\'okugabana. Ekyanya ekitariho nikikozesa amarangi agatairweho.'],
    ['Shown at the top of the app\'s Help Centre page, above the Telegram/support links below. Square corners by design, no rounding.', 'Kirabika waggulu ku lupapula lw\'obuyambi, waggulu w\'ebinywanyizo bya Telegram. Enkonvuba za kkona, tezeetoolooza.', 'Inaonyeshwa juu ya ukurasa wa usaidizi, juu ya viungo vya Telegram. Pembe za mraba kwa muundo, hakuna kuzungusha.', 'Affiché en haut de la page Centre d\'aide, au-dessus des liens Telegram. Coins carrés par conception, sans arrondi.', 'Bigaragara hejuru ku rupapuro rw\'ubufasha, hejuru y\'imirongo ya Telegram. Impande zifite inguni, ntizizengurutswa.', 'Nikyorekwa ahaiguru aha rupapura rw\'obuhwezi, ahaiguru y\'emikwate ya Telegram. Enkoona z\'obunywani, tizirikuzengurutsibwa.'],
    ['Find any member here -- tap the result to see their team size and their team\'s total deposits.', 'Zuula omukozesa yenna wano -- kubako ku kivudde mu kunoonya olabe obunene bw\'ekibiina kye n\'ssente ze baateekamu.', 'Pata mwanachama yeyote hapa -- gusa matokeo kuona ukubwa wa timu yake na jumla ya amana za timu.', 'Trouvez n\'importe quel membre ici -- touchez le résultat pour voir la taille de son équipe et ses dépôts totaux.', 'Shakisha umunyamuryango uwo ari we wese hano -- kanda igisubizo urebe ingano y\'ikipe ye n\'ubwishyu bwayo bwose.', 'Sherura omukozesa weena hanu -- teera aha kirugiremu oreebe obwingi bw\'ekibiina kye na sente ezi baateiremu.'],
    ['Rebuild every user\'s deposit/earning/invested totals AND check-in streaks from the real ledger', 'Ddamu ozimbe omugatte gw\'ssente eziteekeddwamu, ezifunibwa n\'eziteekeddwa mu bizinensi awamu n\'okukyalira okuva mu bitabo ebituufu', 'Jenga upya jumla za amana/mapato/uwekezaji NA mifululizo ya kuhudhuria kutoka daftari halisi', 'Reconstruire les totaux de dépôt/gains/investissement ET les séries de pointage depuis le registre réel', 'Kongera kubaka ibiteranyo by\'ubwishyu/inyungu/ishoramari N\'uruhererekane rwo kwiyandikisha bivuye mu gitabo nyacyo', 'Garuka oyombeke omugatte gwa sente ezitairwemu/ezitungirwe/ezitairwe omu byamaguzi N\'okwoleka kuruga omu bitabo ebihikire'],
    ['Wipes every registered device -- each one (including yours) needs to tap "Notify" again afterward.', 'Kisangula buli kyuma ekiwandiisiddwa -- buli kimu (ne kikyo) kyetaaga okuddamu okukuba ku "Manyisa".', 'Inafuta kila kifaa kilichosajiliwa -- kila kimoja (pamoja na chako) kinahitaji kugusa "Arifa" tena baadaye.', 'Efface tous les appareils enregistrés -- chacun (y compris le vôtre) devra retoucher « Notifier ».', 'Bisiba buri gikoresho cyanditswe -- buri kimwe (harimo n\'icyawe) kigomba kongera gukanda "Menyesha".', 'Nikirihamu buri kyoma ekihandiikirwe -- buri kimwe (n\'ekyaawe) nikyetenga kugaruka kuteera aha "Manyisa".'],
    ['A now-fixed bug could turn saving product-1 into a SEPARATE product1 -- this finds and merges any it made', 'Ensobi eyaatereezebwa yasobola okufuula okutereka product-1 okuba product1 eyawukana -- kino kizuula era kigatta ezo ze yakola', 'Hitilafu iliyorekebishwa ingeweza kugeuza kuhifadhi product-1 kuwa product1 TOFAUTI -- hii inapata na kuunganisha zozote ilizotengeneza', 'Un bug désormais corrigé pouvait transformer l\'enregistrement de product-1 en un product1 SÉPARÉ -- ceci les trouve et les fusionne', 'Ikibazo cyakosowe cyashoboraga guhindura kubika product-1 mu product1 ITANDUKANYE -- ibi birabishakisha kandi bikabihuza', 'Enshobe eyaayerurwa ekaba nebaasa kuhindura okubiika product-1 okuba product1 eyaahukaine -- eki nikisherura kandi kikagyemesa ezi ekahanga'],
    ['Owner: leave username blank and enter your admin key. Staff: enter the username and password you were given.', 'Nannyini: leka erinnya ly\'omukozesa nga lyereere oteekemu ekisumuluzo kyo eky\'obuduumizi. Abakozi: teekamu erinnya n\'ekisumuluzo bye mwaweebwa.', 'Mmiliki: acha jina la mtumiaji tupu na weka ufunguo wako wa msimamizi. Wafanyakazi: weka jina na nenosiri mliyopewa.', 'Propriétaire : laissez le nom d\'utilisateur vide et saisissez votre clé admin. Personnel : saisissez le nom et le mot de passe fournis.', 'Nyir\'ubwite: siga izina ry\'umukoresha ubusa maze wandike urufunguzo rwawe rw\'ubuyobozi. Abakozi: andika izina n\'ijambobanga mwahawe.', 'Nyineeka: reka eiziina ry\'omukozesa ritariho otemu ekisumuruzo kyawe eky\'obwebembezi. Abakozi: tamu eiziina n\'ekisumuruzo ebi mwahairwe.'],
    ['Username (leave blank if you\'re the owner)', 'Erinnya ly\'omukozesa (leka nga lyereere bw\'oba nannyini)', 'Jina la mtumiaji (acha tupu ikiwa wewe ni mmiliki)', 'Nom d\'utilisateur (laissez vide si vous êtes le propriétaire)', 'Izina ry\'umukoresha (siga ubusa niba uri nyir\'ubwite)', 'Eiziina ry\'omukozesa (reka ritariho ku oraabe ori nyineeka)'],
    ['Only fixes their profile phone (search/display/referral matching) -- they still log in exactly how they always have.', 'Kitereeza essimu ku profayiro yokka (okunoonya/okulaga/okugeraageranya kw\'okuyita) -- bakyayingira nga bwe baabanga.', 'Inarekebisha simu ya wasifu tu (kutafuta/kuonyesha/kulinganisha mialiko) -- bado wanaingia jinsi walivyozoea.', 'Corrige uniquement le téléphone du profil (recherche/affichage/parrainage) -- la connexion reste exactement la même.', 'Ikosora gusa telefone y\'umwirondoro (gushakisha/kwerekana/guhuza gutumira) -- baracyinjira uko basanzwe.', 'Nigyerurura esimu aha profairo yoonka (okusherura/okworeka/okugyeranisa okweta) -- nibakyataaha nk\'oku bakaba nibataaha.'],
    ['Permanently deletes the login and personal data. Investments/transactions/withdrawals are kept as financial records.', 'Kisazaamu olubeerera okuyingira n\'ebikwata ku muntu. Ebyamaguzi, emirimu gy\'ssente n\'okuggyamu bisigala nga byafaayo by\'ssente.', 'Inafuta kabisa kuingia na data binafsi. Uwekezaji/miamala/utoaji vinahifadhiwa kama kumbukumbu za kifedha.', 'Supprime définitivement la connexion et les données personnelles. Investissements/transactions/retraits sont conservés comme pièces comptables.', 'Isiba burundu kwinjira n\'amakuru bwite. Ishoramari/ibikorwa/kubikuza bibikwa nk\'inyandiko z\'imari.', 'Nirihamu kimwe okutaaha n\'ebirikukwata ahamuntu. Ebyamaguzi/emirimo ya sente/okwihamu nibisigara nk\'ebyafaayo bya sente.'],
    ['Broadcast to every member\'s in-app Messages inbox. Leave the ID blank to post a new message; fill it to edit an existing one.', 'Kisindikibwa mu bubaka bwa buli mukozesa mu pulogulaamu. Leka namba nga yereere okuteeka obubaka obupya; gijjuze okukyusa obuliwo.', 'Hutumwa kwa kisanduku cha ujumbe cha kila mwanachama. Acha kitambulisho tupu kutuma ujumbe mpya; kijaze kuhariri uliopo.', 'Diffusé dans la boîte Messages de chaque membre. Laissez l\'ID vide pour publier un nouveau message ; remplissez-le pour en modifier un.', 'Bwoherezwa mu gasanduku k\'ubutumwa bwa buri munyamuryango. Siga indangamuntu ubusa kugira wohereze ubutumwa bushya; uyuzuze kugira uhindure ubusanzwe.', 'Nibutumirwa omu butumwa bwa buri mukozesa omu porogaraamu. Reka namba etariho kutuma obutumwa businga; ogyijuze kuhindura oburiho.'],
    ['Members can only cash out in steps of this — 5,000 allows 5,000 / 10,000 / 25,000 and so on. Set 0 to allow any amount above the minimum.', 'Abakozesa basobola okuggyamu ssente mu bigero bino byokka — 5,000 kikkiriza 5,000 / 10,000 / 25,000 n\'ebirala. Teeka 0 okukkiriza omuwendo gwonna oguyisa ogusinga obutono.', 'Wanachama wanaweza kutoa pesa kwa hatua hizi tu — 5,000 inaruhusu 5,000 / 10,000 / 25,000 na kadhalika. Weka 0 kuruhusu kiasi chochote juu ya kiwango cha chini.', 'Les membres ne peuvent retirer que par multiples de ceci — 5 000 autorise 5 000 / 10 000 / 25 000, etc. Mettez 0 pour autoriser tout montant au-dessus du minimum.', 'Abanyamuryango bashobora kubikuza gusa mu bipimo nk\'ibi — 5.000 byemera 5.000 / 10.000 / 25.000 n\'ibindi. Shyiraho 0 kwemerera umubare uwo ari wo wose hejuru y\'umuto.', 'Abakozesa nibabaasa kwihamu sente omu bigyero ebi byonka — 5,000 nikikiriza 5,000 / 10,000 / 25,000 n\'ebindi. Taho 0 kwikiriza omubaro gwoona ogurikukira ogukye.'],
    ['The real float sitting in MarzPay\'s own account -- what payouts actually get sent from, distinct from members\' own wallet balances above.', 'Ssente entuufu eziri ku akawunti ya MarzPay -- ze zisasulwamu, nga zaawukana ku ssente z\'abakozesa eziri waggulu.', 'Fedha halisi iliyo katika akaunti ya MarzPay -- ndizo malipo hutoka, tofauti na salio za pochi za wanachama hapo juu.', 'Le solde réel du compte MarzPay -- c\'est de là que partent les paiements, distinct des soldes des membres ci-dessus.', 'Amafaranga nyayo ari kuri konti ya MarzPay -- ni yo ibyishyurwa biva, bitandukanye n\'amafaranga y\'abanyamuryango hejuru.', 'Sente ezihikire eziri aha akaunti ya MarzPay -- nizo okushashura kurikuruga, ezahukaine na sente z\'abakozesa eziri ahaiguru.'],
    ['Account ids are 5 digits now. This rewrites ids issued while they were 6 (000001 -> 00001). Ids that genuinely need 6 digits are left alone.', 'Namba z\'akawunti kaakano za nnamba 5. Kino kikyusa ezaaweebwa nga ziri 6 (000001 -> 00001). Ezo ezeetaaga nnamba 6 zisigala nga bwe ziri.', 'Vitambulisho vya akaunti sasa ni tarakimu 5. Hii inaandika upya vilivyotolewa vikiwa 6 (000001 -> 00001). Vinavyohitaji tarakimu 6 kweli vinaachwa.', 'Les identifiants de compte font 5 chiffres désormais. Ceci réécrit ceux émis à 6 (000001 -> 00001). Ceux qui ont vraiment besoin de 6 sont laissés tels quels.', 'Indangamuntu za konti ubu ni imibare 5. Ibi byandika bushya izatanzwe zifite 6 (000001 -> 00001). Izikeneye koko imibare 6 zisigara uko ziri.', 'Namba za akaunti hati n\'embaro 5. Eki nikihindura ezi baahairwe zaaba 6 (000001 -> 00001). Ezirikwetenga embaro 6 buzima nizisigara nk\'oku ziri.'],
    ['How fast the scrolling deposit/withdraw activity strip on the user Home screen flows right to left. Higher is faster; 160 is the current default.', 'Sipiidi olukalala lw\'ebikolwa lwe lutambulira okuva ku ddyo okudda ku kkono ku lupapula olusooka. Omuwendo omunene gwe mwangu; 160 gwe gutongole.', 'Kasi ambayo mkanda wa shughuli za amana/utoaji kwenye ukurasa wa nyumbani unatembea kulia kwenda kushoto. Kubwa ni haraka zaidi; 160 ndiyo chaguo-msingi.', 'La vitesse à laquelle le bandeau d\'activité défile de droite à gauche sur l\'accueil. Plus élevé = plus rapide ; 160 est la valeur par défaut.', 'Umuvuduko umurongo w\'ibikorwa ugenda uva iburyo ujya ibumoso ku rupapuro rw\'ahabanza. Munini ni wihuta; 160 ni cyo gisanzwe.', 'Obwiru orukoora rw\'ebikorwa oru rurikugyendera kuruga aha buryo kuza aha bumosho aha rupapura rw\'omuka. Omubaro omwingi nigwo gw\'obwiru; 160 nigwo ogutairweho.'],
    ['Updates price/cycle/expectedReturn on any saved product back to the current code defaults -- leaves images, active/coming-soon, and order untouched', 'Kikyusa ebbeeyi, ebbanga n\'ebisuubirwa ku kyamaguzi kyonna ekitereddwa okudda ku ntereka entongole -- ebifaananyi, embeera n\'entegeka tebikyusibwa', 'Inasasisha bei/mzunguko/marejesho yanayotarajiwa kwa bidhaa yoyote iliyohifadhiwa hadi chaguo-msingi -- picha, hali, na mpangilio haviguswi', 'Remet le prix/cycle/retour attendu de tout produit enregistré aux valeurs par défaut -- images, état et ordre restent inchangés', 'Ivugurura igiciro/uruziga/inyungu bitegerejwe ku gicuruzwa cyose cyabitswe bigasubira ku bisanzwe -- amashusho, imimerere n\'urutonde ntibihinduka', 'Nihindura ekiingana/obwire/ebirikutebeekanisibwa aha kyamaguzi kyoona ekibiikirwe kigaruke aha bitairweho -- ebishushani, embeera n\'entegyeka tibirikuhindurwa'],
    ['The round logo on the app\'s Account profile card. An empty slot shows the CHIPZ wordmark instead. Square images work best -- it is cropped to a circle.', 'Akabonero akeetoolooze ku kaadi ya profayiro mu pulogulaamu. Ekifo ekyereere kiraga erinnya CHIPZ. Ebifaananyi ebya kkona bye bisinga -- kisalibwa okuba enkulungo.', 'Nembo ya duara kwenye kadi ya wasifu wa akaunti. Nafasi tupu inaonyesha jina CHIPZ badala yake. Picha za mraba ni bora -- inakatwa kuwa duara.', 'Le logo rond sur la carte de profil du compte. Un emplacement vide affiche le mot CHIPZ à la place. Les images carrées conviennent le mieux -- elle est recadrée en cercle.', 'Ikirango kizengurutse ku ikarita y\'umwirondoro wa konti. Umwanya utariho werekana izina CHIPZ. Amashusho afite impande zingana ni yo meza -- ikatwa mu ruziga.', 'Ekimanyiso ekizengurukire aha kaadi ya profairo ya akaunti. Ekyanya ekitariho nikyoreka eiziina CHIPZ. Ebishushani by\'enkoona nibyo birikukira -- nikishaarwa kuba oruzengurukiro.'],
    ['Check every user\'s wallet balance/deposited/earned/invested against the real records, plus duplicate deposit credits, negative balances, and stuck registrations', 'Kebera ssente za buli mukozesa eziri mu nsawo, eziteekeddwamu, ezifunibwa n\'eziteekeddwa mu bizinensi ng\'ozigeraageranya n\'ebyafaayo ebituufu, n\'ssente eziweereddwa emirundi ebiri, n\'okwewandiisa okukwataganye', 'Angalia salio la pochi/amana/mapato/uwekezaji la kila mtumiaji dhidi ya kumbukumbu halisi, pamoja na amana zilizolipwa mara mbili, salio hasi, na usajili uliokwama', 'Vérifier le solde/dépôts/gains/investissements de chaque utilisateur face aux registres réels, plus les dépôts crédités deux fois, les soldes négatifs et les inscriptions bloquées', 'Genzura amafaranga ari mu mufuka/yabitswe/yinjiye/yashowe ya buri mukoresha ugereranyije n\'inyandiko nyazo, hamwe n\'ubwishyu bwishyuwe kabiri, amafaranga ari munsi ya zero, n\'iyandikwa ryanyuranye', 'Reeba sente za buri mukozesa eziri omu nsaho, ezitairwemu, ezitungirwe n\'ezitairwe omu byamaguzi n\'ozigyeranisa n\'ebyafaayo ebihikire, na sente ezihairwe emirundi ebiri, n\'okwehandiisa okukwatiine'],
    ['Set a new login password for this user via Firebase', 'Teekawo ekisumuluzo ekipya eky\'okuyingira ku mukozesa ono ng\'oyita mu Firebase', 'Weka nenosiri jipya la kuingia kwa mtumiaji huyu kupitia Firebase', 'Définir un nouveau mot de passe de connexion pour cet utilisateur via Firebase', 'Shyiraho ijambobanga rishya ryo kwinjira kuri uyu mukoresha binyuze kuri Firebase', 'Taho ekisumuruzo kisya eky\'okutaaha aha mukozesa ogu orikuraba omu Firebase'],
    ['"Telegram group" and "Direct contact" also show as the two buttons on the app\'s Help Centre page. Leave either blank to hide its button.', '"Ekibiina kya Telegram" ne "Endagiriro ey\'obutereevu" nabyo birabika ng\'obupeesa bubiri ku lupapula lw\'obuyambi. Leka kimu nga kyereere okukweka akapeesa kaakyo.', '"Kikundi cha Telegram" na "Mawasiliano ya moja kwa moja" pia huonyeshwa kama vitufe viwili kwenye ukurasa wa usaidizi. Acha chochote tupu kuficha kitufe chake.', '« Groupe Telegram » et « Contact direct » apparaissent aussi comme les deux boutons de la page Centre d\'aide. Laissez l\'un vide pour masquer son bouton.', '"Itsinda rya Telegram" na "Aho wahamagara ako kanya" na byo bigaragara nk\'buto ebyiri ku rupapuro rw\'ubufasha. Siga kimwe ubusa kugira uhishe buto yacyo.', '"Ekibiina kya Telegram" na "Endagiriro y\'obuhango" nabyo nibyorekwa nk\'obupeera bubiri aha rupapura rw\'obuhwezi. Reka kimwe kitariho kusherekyera akapeera kaakyo.'],
]

PATTERNS = [
    # Counted headers. The figure is copied across untouched; only the word
    # moves, and where a language puts the count differently the {0} moves
    # with it.
    ['Users ({0})', 'Abakozesa ({0})', 'Watumiaji ({0})', 'Utilisateurs ({0})', 'Abakoresha ({0})', 'Abakozesa ({0})'],
    ['Countries ({0})', 'Amawanga ({0})', 'Nchi ({0})', 'Pays ({0})', 'Ibihugu ({0})', 'Amahanga ({0})'],
    ['Referrals ({0})', 'Okuyita ({0})', 'Mialiko ({0})', 'Parrainages ({0})', 'Gutumira ({0})', 'Okweta ({0})'],
    ['Plans ({0})', 'Enteekateeka ({0})', 'Mipango ({0})', '=', 'Gahunda ({0})', 'Enteekateeka ({0})'],
    ['Deposits ({0})', 'Ssente eziteekeddwamu ({0})', 'Amana ({0})', 'Dépôts ({0})', 'Ubwishyu bwinjiye ({0})', 'Sente ezitairwemu ({0})'],
    ['Withdrawals ({0})', 'Okuggyamu ssente ({0})', 'Utoaji ({0})', 'Retraits ({0})', 'Kubikuza ({0})', 'Okwihamu sente ({0})'],
    ['Transactions ({0})', 'Emirimu gy\'ssente ({0})', 'Miamala ({0})', '=', 'Ibikorwa ({0})', 'Emirimo ya sente ({0})'],
    ['Products ({0}) · {1}', 'Ebyamaguzi ({0}) · {1}', 'Bidhaa ({0}) · {1}', 'Produits ({0}) · {1}', 'Ibicuruzwa ({0}) · {1}', 'Ebyamaguzi ({0}) · {1}'],
    ['Rates & limits · {0}', 'Ebigero n\'obukomo · {0}', 'Viwango na mipaka · {0}', 'Taux et limites · {0}', 'Ibipimo n\'imipaka · {0}', 'Ebigyero n\'emigyendo · {0}'],
    ['Referral code: {0}', 'Koodi y\'okuyita: {0}', 'Msimbo wa mwaliko: {0}', 'Code de parrainage : {0}', 'Kode yo gutumira: {0}', 'Koodi y\'okweta: {0}'],
    ['Account status: {0}', 'Embeera ya akawunti: {0}', 'Hali ya akaunti: {0}', 'Statut du compte : {0}', 'Imimerere ya konti: {0}', 'Embeera ya akaunti: {0}'],
    ['Newest first, {0} total.', 'Ebipya bisooka, omugatte {0}.', 'Vipya kwanza, jumla {0}.', 'Les plus récents d\'abord, {0} au total.', 'Bishya mbere, byose {0}.', 'Ebisya bikatandika, omugatte {0}.'],
    ['Pays {0}', 'Esasula {0}', 'Inalipa {0}', 'Rapporte {0}', 'Itanga {0}', 'Neeshashura {0}'],
]
