# Round: network logos, and both deposit paths (PAY A and PAY B) sharing one
# network-selector screen -- new admin-panel copy in Settings -> Manual
# payments / Network logos. The two long paragraphs are whole-BLOCK keys
# (their only element child is an inline <i>/<b> mark, per the i18n engine's
# block-translate rule), extracted EXACT via dump-admin-blocks.py rather than
# retyped by hand, so the key here is guaranteed to match what the engine
# actually looks up.
#
# The three Bantu columns are a good-faith first pass, same as every other
# long paragraph in this table -- want a native speaker's eye before launch,
# like the rest of this file already says.
#
# Six columns: English, Luganda, Kiswahili, French, Kinyarwanda, Runyankore.
ROWS = [
    ['Network logos',
     "Ebifaananyi by'emikutu", 'Nembo za mitandao', 'Logos des réseaux',
     "Amashusho y'imiyoboro", "Ebishushani by'emiyoboro"],

    ['Network name',
     "Erinnya ly'omukutu", 'Jina la mtandao', 'Nom du réseau',
     "Izina ry'umuyoboro", "Eiziina ry'omuyoboro"],

    ['No network logos uploaded yet.',
     "Tewali kifaananyi kya mukutu kyateekebwaayo.", 'Hakuna nembo za mtandao zilizopakiwa bado.',
     'Aucun logo de réseau téléchargé pour le moment.',
     "Nta shusho y'umuyoboro yashyizweho kugeza ubu.", "Tihariho kishushani ky'omuyoboro ekyateekyweho."],

    ['e.g. MTN Mobile Money',
     'gamba nga MTN Mobile Money', 'mfano MTN Mobile Money', 'p. ex. MTN Mobile Money',
     'urugero MTN Mobile Money', "nk'eky'okurorraho MTN Mobile Money"],

    ['Members now see up to 2 payment options on the Recharge screen, labelled neutrally "PAY A" and "PAY B" (no "manual"/"automatic" wording is ever shown to them) -- enable either one alone, or both at once so the member picks. Both now collect a network and phone number on the same screen, using each country\'s own network list and the logos set below. PAY A is the automatic gateway (MarzPay, LipaPay or PesaJet, chosen below) -- instant, no admin numbers needed. PAY B is manual -- assigns the member one of the numbers below to send money to by hand, matched to their order by your phone\'s SMS forwarder (or by the member pasting their own confirmation text if the forwarder is slow).',
     'Abakozesa kaakano balaba emikisa egy\'okusasula okutuuka ku 2 ku layini ya Recharge, nga giyitibwa awatali kusosola "PAY A" ne "PAY B" (tewali kigambo kya "kya bukwakkulizo" oba "ekyokka kyokka" ekibalagibwa). Kkindiza emu yokka, oba zombi ziri ne omukozesa alondamu. Zombi kati zikuŋŋaanya omukutu n\'ennamba ya essimu ku layini emu, nga zikozesa olukalala lw\'omukutu olw\'ensi eyo n\'ebifaananyi ebiteekeddwa wansi. PAY A ye layini eyeekola yokka (MarzPay, LipaPay oba PesaJet, eyalondeddwa wansi) -- ya mangu, tewali nnamba za admin zeetaagisa. PAY B ya mukono -- ewa omukozesa emu ku nnamba ez\'awansi okusindika ssente mu mukono, ekigeraageranyizibwa n\'oda ye okuyita mu SMS forwarder ya ssimu yo (oba omukozesa yekka ng\'ateeka obubaka bwe obw\'okukakasa singa forwarder mpolampola).',
     'Wanachama sasa wanaona chaguo hadi mbili za malipo kwenye skrini ya Recharge, zikiitwa kwa kutoegemea upande "PAY A" na "PAY B" (hakuna neno "la mkono"/"kiotomatiki" linaloonyeshwa kwao) -- washa moja peke yake, au zote mbili ili mwanachama achague. Zote mbili sasa hukusanya mtandao na nambari ya simu kwenye skrini moja, kwa kutumia orodha ya mitandao ya nchi yenyewe na nembo zilizowekwa hapa chini. PAY A ni lango la kiotomatiki (MarzPay, LipaPay au PesaJet, lililochaguliwa hapa chini) -- la papo hapo, hakuna namba za msimamizi zinazohitajika. PAY B ni ya mkono -- humpa mwanachama mojawapo ya namba zilizo hapa chini ili atume pesa kwa mkono, ikilinganishwa na oda yake kupitia kisambazaji cha SMS cha simu yako (au mwanachama mwenyewe akibandika maandishi yake ya uthibitisho ikiwa kisambazaji ni cha polepole).',
     'Les membres voient désormais jusqu\'à 2 options de paiement sur l\'écran Recharge, appelées neutrement « PAY A » et « PAY B » (aucun mot « manuel »/« automatique » ne leur est jamais montré) -- activez l\'une seule, ou les deux à la fois pour que le membre choisisse. Les deux collectent désormais un réseau et un numéro de téléphone sur le même écran, en utilisant la propre liste de réseaux de chaque pays et les logos définis ci-dessous. PAY A est la passerelle automatique (MarzPay, LipaPay ou PesaJet, choisie ci-dessous) -- instantanée, aucun numéro admin requis. PAY B est manuel -- il attribue au membre l\'un des numéros ci-dessous pour envoyer l\'argent à la main, rapproché de sa commande par le transfert SMS de votre téléphone (ou en collant lui-même son texte de confirmation si le transfert est lent).',
     'Abanyamuryango none babona amahitamo y\'ubwishyu kugeza kuri 2 kuri ecran ya Recharge, yitwa "PAY A" na "PAY B" nta vy\'uko (nta jambo "gukorwa n\'intoke"/"otomatike" ribagaragarira) -- fungura imwe gusa, cyangwa zombi kugira umunyamuryango ahitemo. Zombi ubu zikusanya umuyoboro n\'inomero ya telefoni ku ecran imwe, hifashishijwe urutonde rw\'imiyoboro y\'igihugu ubwacyo n\'amashusho ashyizweho hepfo. PAY A ni umuyoboro wikora ubwawo (MarzPay, LipaPay cyangwa PesaJet, watoranyijwe hepfo) -- ako kanya, nta nomero z\'umuyobozi zikenewe. PAY B ni iy\'intoke -- iha umunyamuryango imwe mu nomero ziri hepfo kugira ngo ayoherereze amafaranga mu ntoke, ihuzwa n\'itumizwa rye binyuze muri SMS forwarder ya telefoni yawe (cyangwa umunyamuryango asomeka ubwe ubutumwa bwe bw\'emeza niba forwarder igenda buhoro).',
     "Abemeezi n'obu nibareeba emiringo y'okusasura kuhika 2 aha screen ya Recharge, ekyeeteibwa \"PAY A\" na \"PAY B\" (tihariho ekigambo kya \"okukorwa n'engaro\"/\"otomatiki\" ekirikubareeberwa). Shumurira emwe yonka, nari zombi kugira ngu omwegyendesyereza yeecweho. Zombi hati nizikwata omuyoboro n'enamba ya esimu aha screen emwe, nizikoresa orutonde rw'emiyoboro rw'ihanga ryonka n'ebishushani ebiteekyweho hansi. PAY A niyo automatic gateway (MarzPay, LipaPay nari PesaJet, eyacwirweho hansi) -- yangu, tihariho enamba za admin ezirikwetagisibwa. PAY B n'ey'engaro -- neeha omwegyendesyereza emwe aha namba eziri hansi kutwaza sente omu ngaro, ekigeraniisibwa n'oda ye okuraba omuri SMS forwarder ya esimu yaawe (nari omwegyendesyereza yenka nayeetekyera obubaka bwe obw'okukakasa forwarder erikugyenda buhoro)."],

    ['Members now pick a network (MTN, Airtel, Orange, M-Pesa...) on the Recharge and manual-payment screens, on BOTH PAY A and PAY B -- and each country only shows the networks you gave it under Countries → Networks this country offers. Upload one logo per network NAME here (not per country) — "MTN Mobile Money" is used by every country whose list has that exact name, since the logo belongs to the network, not to any one country\'s list. A network with no logo shows a plain letter tile instead of a blank one.',
     "Abakozesa kaakano balonda omukutu (MTN, Airtel, Orange, M-Pesa...) ku layini za Recharge n'ez'okusasula mu mukono, ku PAY A ne PAY B zombi -- era buli nsi elaga mikutu gyo gyawadde bwokka wansi wa Countries → Emikutu eggwanga lino gye liwa. Teeka ekifaananyi kimu ku mukutu buli GUYE wano (si buli nsi) -- \"MTN Mobile Money\" ekozesebwa ensi zonna ezirina erinnya eryo ddala, kubanga ekifaananyi kya mukutu, si nsi emu. Omukutu ogutalina kifaananyi gulaga akabonero k'ennukuta mu kifo ky'ekifaananyi ekyereere.",
     'Wanachama sasa huchagua mtandao (MTN, Airtel, Orange, M-Pesa...) kwenye skrini za Recharge na malipo ya mkono, kwenye zote mbili PAY A na PAY B -- na kila nchi huonyesha tu mitandao uliyoipa chini ya Countries → Mitandao nchi hii inayotoa. Pakia nembo moja kwa kila JINA la mtandao hapa (si kwa kila nchi) -- "MTN Mobile Money" hutumika na kila nchi ambayo orodha yake ina jina hilo hasa, kwa kuwa nembo ni mali ya mtandao, si ya orodha ya nchi moja. Mtandao usio na nembo huonyesha kigae cha herufi badala ya kigae tupu.',
     'Les membres choisissent désormais un réseau (MTN, Airtel, Orange, M-Pesa...) sur les écrans Recharge et paiement manuel, sur PAY A ET PAY B -- et chaque pays n\'affiche que les réseaux que vous lui avez donnés sous Countries → Réseaux offerts par ce pays. Téléchargez un logo par NOM de réseau ici (pas par pays) -- « MTN Mobile Money » est utilisé par chaque pays dont la liste contient exactement ce nom, car le logo appartient au réseau, pas à la liste d\'un pays. Un réseau sans logo affiche une simple tuile-lettre au lieu d\'une tuile vide.',
     "Abanyamuryango none bahitamo umuyoboro (MTN, Airtel, Orange, M-Pesa...) kuri ecran za Recharge n'iz'ubwishyu bw'intoke, kuri PAY A na PAY B zombi -- kandi buri gihugu kigaragaza gusa imiyoboro wagihaye munsi ya Countries → Imiyoboro iki gihugu gitanga. Shyiraho ishusho imwe kuri IZINA ry'umuyoboro hano (atari kuri buri gihugu) -- \"MTN Mobile Money\" ikoreshwa n'ikindi gihugu cyose ururutonde rwaco rufite iryo zina neza, kuko ishusho ari iy'umuyoboro, atari iy'urutonde rw'igihugu kimwe. Umuyoboro udafite ishusho werekana agasanduku k'inyuguti aho gusanduku busa.",
     "Abemeezi hati nibacwera omuyoboro (MTN, Airtel, Orange, M-Pesa...) aha screen za Recharge n'ez'okusasura n'engaro, aha PAY A na PAY B zombi -- kandi buri ihanga nirioreka emiyoboro yawaguhaire yonka omuri Countries → Emiyoboro eiri ihanga rirakuha. Teekaho ekishushani kimwe aha EIZIINA ry'omuyoboro hanu (tihali aha buri ihanga) -- \"MTN Mobile Money\" nekoresibwa buri ihanga eryine orutonde rurimu eiziina eryo shaho, ahakuba ekishushani n'eky'omuyoboro, tikwo eky'orutonde rw'ihanga rimwe. Omuyoboro ogutaine kishushani nigworeka akabonero k'omuharufu omu mwanya gw'akabonero akatalimu kintu."],
]
